### ISSUE TITLE
Components to replace ToolActions in 1.21+?

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#1005]
The thought came from here:
https://github.com/neoforged/NeoGradle/issues/189

While tags are not a suitable replacement for ToolActions, what about Components? We can add or remove components off of itemstacks so in theory, we could convert each toolaction into separate components provided by NeoForge. Then modders would add the component to their itemstacks when they want a specific action supported and other modders can check for presence of the Neoforge component on the itemstack.

Thoughts?

Bonus, when we add a component ingredient for recipes, it can then target these toolaction components as well.

**Comment by Shadows-of-Fire** [comment]
I don't *think* Components are applicable for this purpose due to the way that Components sync.  For starters, I'm not sure we can even add new component types while maintaining vanilla compatibility, and even if we could do that from the server side, we would need to also have a system that pretends they exist on the client side when on a vanilla server.

**Comment by KnightMiner** [comment]
The other thing is this just sounds like a pain to maintain. With tool actions, its easy enough for my item stack to just redirect tool action queries to my mod specific NBT/components. If I am required to duplicate my custom data into Neo actions, its going to become a pain to ensure they are properly removed if the data that granted the action gets removed (as its possible the action comes from more than one source in my custom data).

I don't see why you are so adamant to get rid of tool actions to be honest. The system is very cheap and has unique benefits that no other current system has. If anything we should be getting rid of tool tags that are redundant to tool actions so we can ensure people are not relying conditioning tool behaviors on NBT insensitive logic.

**Comment by TelepathicGrunt** [comment]
> you are so adamant to get rid of tool actions to be honest.

I wasn’t adamant about removing it. I was curious to see if components could be a suitable system to move it to if it had benefits. If not, the current system can stay. Hence why it’s a discussion post lol

**Comment by KnightMiner** [comment]
Sorry, misread who posted this issue. Thought the original issue (where it was stated tags won't work) and the followup (talking about tool actions) were the same author.

**Comment by FiniteReality** [comment]
Components won't work, because they're, to my knowledge, effectively final. A capability COULD work, but I don't think it's necessary to change one API for another.

**Comment by KnightMiner** [comment]
It's also worth noting, you can add custom tool actions without a compile time dependency on another mod, they are equivalent by name; this is an essential feature for the system. In addition, a new tool action can be added at any time, meaning a tool action could be defined through datapack contents. Both are features I make use of

I don't think both of those are possible with capabilities or tool actions.

**Comment by TelepathicGrunt** [comment]
It could've been a component that hold a list of strings of the tool actions and modders would just add more or remove entries from the list. I think the fact there could be issues with the server connecting to vanilla client and vice versa for components pretty much kills the idea anyway and would be more cumbersome.
