### ISSUE TITLE
[1.20.4/6] New loot table set in `LootTableLoadEvent` via setter or cancelling the event is ignored

### ISSUE THREAD

**Issue by Fuzss** [neoforged/NeoForge#1021]
`LootTableLoadEvent` allows for replacing existing loot tables in two ways: setting a replacement via the setter, or cancelling the event, in which case the existing table is replaced with an empty one.

Both currently fail, as the event is hooked in in the wrong place. The loot table is only replaced for validation, but not in the actual loot tables map. The faulty patch can be found here: https://github.com/neoforged/NeoForge/blob/523d3d7efe14bab81b046cc6d198419df4ea7497/patches/net/minecraft/world/level/storage/loot/LootDataType.java.patch#L51

An alternative would be to patch the event in at `LootDataType::deserializeOrDefault` and modify the return value of that method.

Modifying loot pools on a loot table via the event is not affected and does work fine, as the loot table instance itself is altered.

**Comment by TelepathicGrunt** [comment]
Question, when you use LootTableLoadEvent to replace a loot table with another, how are you getting the second loot table for the replacement? The event doesn't seem to give enough data to get the other loot table. Mainly curious as now I'm wondering if the setTable method on the event is unusable too

**Comment by Fuzss** [comment]
Yeah there is no way to get another already existing loot table, but I don't think that's necessary.
Being able to replace a loot table is useful for supplying a brand new loot table constructed on the fly via `LootTable$Builder` instead.
