### ISSUE TITLE
BuildCreativeModeTabContentsEvent uses wrong hashing strategy for entries

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#1040]
`EventHooks#onCreativeModeTabBuildContents` wraps the vanilla creative mode tab contents collection as part of the event, then allows you to enter new entries to the wrapped collection before passing it back.

In 1.20.5 however, vanilla changed the hashing strategy of the underlying collection to `ItemStackLinkedSet#TYPE_AND_TAG`. NeoForge has not followed this, resulting in the event being able to accept duplicate stacks that vanilla cannot, causing an undetectable `IllegalStateException`

Reproduction:
1. Hook `BuildCreativeModeTabContentsEvent`
2. Add two stacks of the same item but with different DataComponents
3. Profit

**Comment by dhyces** [comment]
Vanilla should allow you to add two stacks of the same item with different data components though. Otherwise, things like enchanted books wouldn't be legal. So how is that a repro case?
