### ISSUE TITLE
Minecraft's title display position is incorrect

### ISSUE THREAD

**Issue by alazeprt** [neoforged/NeoForge#105]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.70

**Logs:** [latest.log](https://github.com/neoforged/NeoForge/files/12364558/latest.log)

**Steps to Reproduce:**
1. Automatically install NeoForge 47.1.70 using third-party launcher
2. Install JEI and JourneyMap mods
3. start games

**Description of issue:**
When the game was loading (small window), the Minecraft icon displayed an error and a portion was split to the right.
<img width="428" alt="minecraft_loading_error" src="https://github.com/neoforged/NeoForge/assets/92018941/54dcd325-3c99-4912-b0d2-c6917207848b">

**Comment by DaemonUmbra** [comment]
Can the issue be reproduced by using the installer we provide and the official Mojang launcher?

If so, please do so and provide the ``installer.log`` our installer generates, as well as the ``launcher_log.txt`` that can be found in ``.minecraft`` after running the launcher.

**Comment by alazeprt** [comment]
This bug did not appear on the official launcher
