### ISSUE TITLE
Replace reference equality check with value equality in ItemStack#addModifierTooltip

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#1052]
With 1.20.6 moving attributes to the datacomponent system, it is now no longer possible to modify a sword (or any other item that uses attack damage/attack speed modifiers)'s attributes without it breaking the tooltip.

When the item is instantiated, it is done so on both sides, which allows the tooltip handler to use reference parity to do a special-case on attack damage & speed

![image](https://github.com/neoforged/NeoForge/assets/7098525/7cc19fbe-3e57-4b60-b8a2-55a9bec0b33b)

However if you try to modify the attributes at any time during gameplay, the game syncs down the attribute values through network, which causes the reference parity to be lost, and breaking the tooltip's value and appearance, even if you remove the modifier afterwards.

Normal tooltip:
![image](https://github.com/neoforged/NeoForge/assets/7098525/2a4e24e0-1f4d-44d6-9249-433b631cb0c3)

After replacing the modifier with itself (no-changes)
![image](https://github.com/neoforged/NeoForge/assets/7098525/c0cf30e5-911a-4e57-9484-29eca0f5d81e)

**Comment by Shadows-of-Fire** [comment]
Seems like its time for me to PR all that attribute tooltip handling code then...

**Comment by Tslat** [comment]
> Seems like its time for me to PR all that attribute tooltip handling code then...

noting that they changed it again in 1.21, including patching this themselves

**Comment by TelepathicGrunt** [comment]
@Shadows-of-Fire Would you be alright if I assign this issue to you then? Just to make sure no one else accidentally picks up doing this work and steps on your toes

**Comment by Tslat** [comment]
This is not a bug in 1.21, applies to 1.20.6 and below

**Comment by TelepathicGrunt** [comment]
Gonna close this as we are focusing on 1.21 right now. If someone wants to make a PR to fix the issue in 1.20.6 or below, we can merge the PR and release. But for now, the main Neo maintainers are going to focus their efforts on 1.21 for now
