### ISSUE TITLE
Let mods depend on Java version

### ISSUE THREAD

**Issue by UpcraftLP** [neoforged/NeoForge#1058]
It would be nice for mods to declare what version of Java they require.

Perhaps take inspiration from Fabric/Quilt and inject a dummy mod container with id `java`?

**Comment by AterAnimAvis** [comment]
Isn't this already doable via the Feature system? Both OpenGL and Java version are available.

<https://docs.neoforged.net/docs/gettingstarted/modfiles#features> for reference.

**Comment by shartte** [comment]
Yes, I think we can close this, since it's already possible

**Comment by UpcraftLP** [comment]
I blame @gigaherz :p

**Comment by gigaherz** [comment]
My bad, I didn't realize the feature system was actually used for anything other than opengl version.
