### ISSUE TITLE
`MobEffectInstance` decoded from NBT without `neoforge:cures` specified do not have default cures

### ISSUE THREAD

**Issue by RaymondBlaze** [neoforged/NeoForge#1060]
**Steps to Reproduce:**
 1. Get a potion with a custom effect and no `neoforge:cures` specified using command: `/give @s minecraft:potion[minecraft:potion_contents={custom_effects:[{id:"minecraft:poison",duration:1200}]}]`.
 2. Drink the potion.
 3. Use honey bottle or milk bucket.
 4. The poison effect is not cured in NeoForge, while cured as expected in vanilla.

**Description of issue:**

The current implementation of `EffectCure` does not have **real** builtin default values for `MobEffectInstance`, the default cures from `IMobEffectExtension#fillEffectCures` are always encoded and can be superseded by any decode result, even without `neoforge:cures` being specified in the data to be decoded.

The reproduce test case shows that this will lead to inconsistency with vanilla. And even without such inconsistency, always encoding the default cures sounds like a bad idea, a mod could change its effects' default cures in an update, but it will find effects granted in old saves are not curable as the old cures are saved into persistent data and supersedes the new ones.

**Possible Solution:**

Since `MobEffectInstance.Details#cures` is already of `Optional<Set<EffectCure>>`, we may simply take `Optional.empty()` as "using the default value from `IMobEffectExtension#fillEffectCures`", and thus `MobEffectInstance#asDetails` should check if the current cures matches the default value using `Set#equals`.

Modders overriding `IMobEffectExtension#fillEffectCures` should ensure that the behavior is consistent between calls for the same `MobEffectInstance` object so the default value check won't fail.

**Comment by Matyrobbrt** [comment]
Cures have to be rewritten after vanilla changes in 1.21.2 due to the component-ization of items. Effects are now cured using `ConsumeEffect`s.
An attempt at reimplementing the cure system is #1603. However, any new system will fundamentally not have effect-specific cures. Therefore, this specific issue is no longer present in newer versions.
