### ISSUE TITLE
[1.20.6] Wolf armor cannot be sheared off with custom shear

### ISSUE THREAD

**Issue by cech12** [neoforged/NeoForge#1062]
I am the mod developer of 2 shears mods [WoodenShears](https://github.com/cech12/WoodenShears) and [CeramicShears](https://github.com/cech12/CeramicShears) and and I am working on updating my mods to 1.20.6.

In Neoforge 20.6.111-beta there were some changes I waited on and there is only one small issue I found during testing my mod in the new environment: Wolf armor cannot be sheared off. This feature was added in Minecraft 1.20.5: https://minecraft.wiki/w/Java_Edition_1.20.5#Items

I think in the `Wolf` entity `mobInteract` method there should be added a check for a tools action. Maybe `SHEARS_HARVEST` could be reused or a new action should be added for this purpose.

Thanks for your help! :)

**Comment by RaymondBlaze** [comment]
`IShearable` feels like a more suitable place to add the support, though moving the interaction from `Wolf#mobInteract` to `IShearable` may cause inconsistency with vanilla if not carefully implemented.

**Comment by cech12** [comment]
That could also be done with the `IShearable` interface. It would be great if that could be supported at least in 1.21 :)

Thanks for all your work!
