### ISSUE TITLE
1.20.1 version of Better Combat wants v47.2 when the 1.20.1 version of NeoForge only goes to 47.1

### ISSUE THREAD

**Issue by Zippomoon** [neoforged/NeoForge#1067]
**Minecraft Version:** 1.20.1

**NeoForge Version:** 47.1.06

**Description of issue:**
Unfortunately Create hasn't been updated past 1.20.1 so I can't just update to a newer version of Minecraft.

**Comment by ChampionAsh5357** [comment]
As far as I'm aware, Better Combat and Create are on Forge which, although mostly compatible with NeoForge 1.20.1, uses a different versioning schema. I would suggest using Forge if you want to play these mods and wait for the 1.20.2+ releases if you want to use NeoForge, assuming if both mods will support NeoForge in the future.
