### ISSUE TITLE
Update checker isn't working

### ISSUE THREAD

**Issue by Leonmmcoset** [neoforged/NeoForge#1074]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.223

**Logs:** [latest.log](https://github.com/user-attachments/files/15748630/latest.log)

**Steps to Reproduce:**
1.Open your Minecraft
2.You can see it in your log.

**Description of issue:**
Update JSON isn't working,
have errors:javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by TelepathicGrunt** [comment]
Just to be clear and help with reproducing, can you elaborate on your exact setup? Is this a workspace for neoforge or mcreator? Are you using any mod launcher and if so, which? Etc. The whole 9 yards so we have the exact steps you're doing to maximize our chances of reproducing the issue

**Comment by shartte** [comment]
@Leonmmcoset can you also please try to run with the following VM argument: `-Djavax.net.debug=ssl:handshake`

**Comment by Leonmmcoset** [comment]
I use mcreator to create mod,then I see NeoForge's docs and create a json file on https://github.com/Leonmmcoset/Mod-Update-JSON
Then on mcreator : Workspace -> Workspace Settings -> Advanced Settings -> Check Update URL
When I write the URL,I run the Minecraft on mcreator,then error coming up.
To @TelepathicGrunt

**Comment by Leonmmcoset** [comment]
Maybe I don't using github to storge the JSON files

**Comment by Leonmmcoset** [comment]
I will change another

**Comment by tmvkrpxl0** [comment]
Can you check the url? It should be https://raw.githubusercontent.com/Leonmmcoset/Mod-Update-JSON/main/messymod.json in your case

**Comment by sciwhiz12** [comment]
There is the slight possibility that something is intercepting the HTTP request and doing a [man-in-the-middle](https://en.wikipedia.org/wiki/Man-in-the-middle_attack) with a certificate that your OS and browser trusts but Java doesn't (since it has its own certificate trust store).

I would suggest checking the certificate served for the site in your browser, just to eliminate that possibility.

**Comment by Leonmmcoset** [comment]
> 有一种可能性是，某些东西正在拦截 HTTP 请求，并使用您的操作系统和浏览器信任但 Java 不信任的证书进行[中间人](https://en.wikipedia.org/wiki/Man-in-the-middle_attack)操作（因为它有自己的证书信任存储）。
> 
> 我建议在浏览器中检查为该站点提供的证书，以消除这种可能性。

This licence is from GitHub

**Comment by Matyrobbrt** [comment]
This is not a NeoForge issue, and is more than likely caused by a network attack, a firewall, or other configuration issues on your side. If you still encounter this problem, please reach out to use on [Discord](https://discord.neoforged.net) as GitHub is not the correct place for support.
