### ISSUE TITLE
`MapDecoration.java.patch` Add the patch, or remove it

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#1075]
https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/level/saveddata/maps/MapDecoration.java.patch

https://github.com/neoforged/NeoForge/blob/ef52a013d85b1b713904f80c121bf061e9596079/patches/net/minecraft/world/level/saveddata/maps/MapDecoration.java.patch#L7

https://github.com/neoforged/NeoForge/blob/ef52a013d85b1b713904f80c121bf061e9596079/patches/net/minecraft/world/level/saveddata/maps/MapDecoration.java.patch#L8

This patch seems to be useless, is it possible to check why the file still exists?

**Comment by Minecraftschurli** [comment]
Why is it not needed? `shouldRenderForIndex` got removed and replaced by a comment stating to reevaluate it.
