### ISSUE TITLE
In the interface where loaded mods are listed (more precisely, to choose how to sort the list), there seems to be one pixel more than expected

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#108]
![image](https://github.com/neoforged/NeoForge/assets/68275908/df350078-0f65-4fbd-8c89-12cf9d88b6ae)

**Comment by sciwhiz12** [comment]
Note for the exacting eye: the pictured button is the `Z-A` button on the mods list screen. It is half a pixel (relative to the background) jutting to the right, if we assume the correct positioning would have the right edges of the button and the mod selection highlight be aligned.

The search bar also seems to be one pixel short (missing half a pixel on either side).
![image](https://github.com/neoforged/NeoForge/assets/21304337/be751c29-9a0d-427e-84da-0db4fbeb57ca)

**Comment by tmvkrpxl0** [comment]
I'm surprised that anyone could even notice that
