### ISSUE TITLE
NeoFormRecompile

### ISSUE THREAD

**Issue by TubikPaw** [neoforged/NeoForge#1081]
Executing Gradle task: idePostSync
Build info: MCreator 2024.1.15821, neoforge-1.20.4, 64-bit, 32490 MB, Windows 10, JVM 17.0.11, JAVA_HOME: C:\Program Files\Java\jdk-17, started on: 2024-04-19-14:39:55
Loaded APIs: jei

> Task :cacheLauncherMetadata UP-TO-DATE
> Task :cacheVersionManifest1.20.4 UP-TO-DATE
> Task :cacheVersionExecutableClient1.20.4 UP-TO-DATE
> Task :cacheVersionExecutableServer1.20.4 UP-TO-DATE
> Task :cacheVersionMappingsClient1.20.4 UP-TO-DATE
> Task :cacheVersionMappingsServer1.20.4 UP-TO-DATE
> Task :neoFormForgesAccessTransformerProvider_script_neoforge.cfg UP-TO-DATE
> Task :neoFormForgesAccessTransformerProvideraccesstransformer.cfg UP-TO-DATE
> Task :neoFormListLibraries UP-TO-DATE
> Task :neoFormStripClient UP-TO-DATE
> Task :neoFormExtractServer UP-TO-DATE
> Task :neoFormStripServer UP-TO-DATE
> Task :neoFormMerge UP-TO-DATE
> Task :neoFormMergeMappings UP-TO-DATE
> Task :neoFormRename UP-TO-DATE
> Task :neoFormApplyForgesAccessTransformer UP-TO-DATE
> Task :neoFormDecompile UP-TO-DATE
> Task :neoFormInject UP-TO-DATE
> Task :neoFormPatch UP-TO-DATE
> Task :neoFormPatchUserDev UP-TO-DATE
> Task :neoFormApplyOfficialMappings UP-TO-DATE
> Task :create1.20.4ClientExtraJar UP-TO-DATE
> Task :selectRawArtifactNet.minecraft_client_1.20.4_client-extra UP-TO-DATE
> Task :neoFormRecompile FAILED
Error: Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain
Caused by: java.lang.ClassNotFoundException: worker.org.gradle.process.internal.worker.GradleWorkerMain
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':neoFormRecompile'.
> Failed to run Gradle Worker Daemon
 > Process 'Gradle Worker Daemon 1' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 11s
24 actionable tasks: 1 executed, 23 up-to-date

BUILD FAILED
Task completed in 11 seconds
 This is mcreator.
Deleting floder Gradle don't helping.
(Sorry I bad know English.)

**Comment by thomasglasser** [comment]
MCreator is not supported by NeoForge, you'll need to make an issue with the MCreator developers
