### ISSUE TITLE
QuadBakingVertexConsumer clears quad's vertex array after baking

### ISSUE THREAD

**Issue by screret** [neoforged/NeoForge#1082]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.0-alpha.1.21-pre4.20240609.093716

**Logs:** none

**Steps to Reproduce:**
 1. bake quad
 2. look at quad
 3. quad empty?? guh?

**Description of issue:**

https://github.com/neoforged/NeoForge/blob/6c8d9c9e220e4f0948c744c50d233748ec6fb0dd/src/main/java/net/neoforged/neoforge/client/model/pipeline/QuadBakingVertexConsumer.java#L143 clears the vertex data array used in the BakedQuad after it's created, presumably to prepare for another quad. this can be fixed by cloning the `quadData` array on line 140.

**Comment by XFactHD** [comment]
Fixed in #1076
