### ISSUE TITLE
Single jar file startup support is required

### ISSUE THREAD

**Issue by RhythmNz** [neoforged/NeoForge#1084]
like forge new installer

If you need to select a jar file, upload your Forge server install (all files in the folder this readme is in) and
select the shim jar file.

**Comment by AterAnimAvis** [comment]
This was attempted in the past and isn't possible without breaking ModLauncher/JPMS or causing additional issues.

Use the included `.sh` or `.bat`, if your using a hosting solution that doesn't support the modern Java way of launching, please consider updating/changing.

**Comment by Technici4n** [comment]
JPMS should not be a problem here.

**Comment by AterAnimAvis** [comment]
From memory the only way it didn't cause JPMS issues was forking the VM which then caused issues with things like keep-alive/auto-restart, saying that it has been a couple of years so may be misremembering.

**Comment by RhythmNz** [comment]
> From memory the only way it didn't cause JPMS issues was forking the VM which then caused issues with things like keep-alive/auto-restart, saying that it has been a couple of years so may be misremembering.

forge now can be it

**Comment by AterAnimAvis** [comment]
Yes, by starting to remove/break JPMS support, which isn't something we're going to do. Forge and Neo have already diverged quite widely under the hood, comparing certain features implented like this isn't useful.
