### ISSUE TITLE
trying to make a mod for Neoforge but: Execution failed for task ':supplyRawJarForneoFormJoined1.20.4-20231207.154220'.

### ISSUE THREAD

**Issue by ff6f8d68** [neoforged/NeoForge#1086]
**Minecraft Version:** {1.20.4}
1.20.4
**NeoForge Version:** {1.20.4-20231207.154220}
1.20.4-20231207.154220
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
https://mclo.gs/8DuWsgY
**Steps to Reproduce:**
1. use macOS
2. install mcreator 2024.1.18518
3. make new project
4. select neoforge
5. create project
**Description of issue:**
error: execution failed for task ':supplyRawJarForneoFormJoined1.20.4-20231207.154220'

**Comment by ChampionAsh5357** [comment]
The line underneath the error message explains the issue: `No space left on device`. As such, I will be closing this as a user error.
