### ISSUE TITLE
PlayerDestroyItemEvent doesn't trigger for Fishing Rods

### ISSUE THREAD

**Issue by Insane96** [neoforged/NeoForge#111]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.0

**Logs:** None

**Steps to Reproduce:**
 1. Subscribe to `PlayerDestroyItemEvent`
 2. /give @p fishing_rod{Damage:200}
 3. Use and retrieve the bobber
 4. The event is not triggered

**Description of issue:**
As the title says, `PlayerDestroyItemEvent` is not triggered for Fishing Rods.

Issue cloned from MinecraftForge

Comment from [ChampionAsh5357](https://github.com/ChampionAsh5357):

The event mentions it should be triggered on `ServerPlayerGameMode#useItem`; however, it isn't. While the event is called on the client, as the fishing rod is only removed on the server, it has no understanding that the item has changed. It looks like the change was never implemented server side, so I'm not sure why this was mentioned.

Regardless, it can be fixed by implementing the event within `ServerPlayerGameMode#useItem`, probably within the `ItemStack#isEmpty` check.

Confirmed by [MCStreetguy](https://github.com/MCStreetguy) that the issue applies to 1.20.1 too

**Comment by Su5eD** [comment]
Related fix from forge MinecraftForge/MinecraftForge#9729
