### ISSUE TITLE
Add `c:fertilizers` tag

### ISSUE THREAD

**Issue by ferriarnus** [neoforged/NeoForge#1135]
Add a common tag for fertilizers. Here I mean items that act like `bonemeal`, by calling the appropriate methods on the bonemealable block.

**Comment by TelepathicGrunt** [comment]
Alternative suggestion, `neoforge:fertilizers` tag that when added to, will automatically make the item act like bonemeal due to us patching all the bonemeal checks to check the tag instead

**Comment by dhyces** [comment]
If it's for behavior, I would prefer it be something like `neoforge:fertilizes`. I have an item that fertilizes stuff, but it itself should not be considered a fertilizer, rather it is a bag that holds fertilizers.

**Comment by TelepathicGrunt** [comment]
a container that holds another item to use would need its own special implementation. If in `neoforge:fertilizes` tag and we hook all the bonemeal stuff to use it, your item will get consumed on use if added to the tag as I'm sure in the bonemeal paths, it decrements the itemstack count

**Comment by TelepathicGrunt** [comment]
Took a look. Bonemealing is not handled by the item but by blocks implementing BonemealableBlock. Then anyone just instanceof check BonemealableBlock and call the bonemealing method on it to grow stuff. So there's no item tag functionality to hook anywhere. Makes sense for this to be a c tag actually. 

@ferriarnus did you make issue report on fabric side to see if they are interested?
