### ISSUE TITLE
RecipeWrapper should extend RecipeInput

### ISSUE THREAD

**Issue by JaisDK** [neoforged/NeoForge#1143]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.017

**Description of issue:**

`RecipeWrapper` should implement `RecipeInput`. As it is right now it can't be used for `RecipeManager.getRecipeFor` anymore.

**Comment by TelepathicGrunt** [comment]
@JaisDK What specifically do you need the RecipeWrapper for? Can you have your item handler implement RecipeInput instead? RecipeWrapper may not be needed anymore and Neo can delete it

**Comment by JaisDK** [comment]
I can probably implement it in my item handler instead

**Comment by TelepathicGrunt** [comment]
Heads up, we decided to keep RecipeWrapper and make it implement RecipeInput like you said. We also loosen the item handler type in it too

**Comment by JaisDK** [comment]
I saw that. Don't know if I need it anymore as I followed your advice and implemented RecipeInput in my handler instead.
