### ISSUE TITLE
[1.21] Adding a tint to and item makes the item invisible

### ISSUE THREAD

**Issue by JaisDK** [neoforged/NeoForge#1176]
**Minecraft Version:** 1.21
**NeoForge Version:** 21.0.32-beta

**Logs:** no crash

**Steps to Reproduce:**
 1. Register item
 2. Tint item with any color int
 3. Item appears invisible in game

**Description of issue:**

event handler
```
@EventBusSubscriber(modid = MODID, value = Dist.CLIENT, bus = EventBusSubscriber.Bus.MOD)
public class ClientEvents
{
    @SubscribeEvent
    public static void registerItemColors(final RegisterColorHandlersEvent.Item event) {
        event.register((pStack, pTintIndex) -> 56063, item);
    }
}
```
item model
```
{
  "parent": "minecraft:item/generated",
  "textures": {
    "layer0": "productivebees:item/honeycombs/base"
  }
}
```
![base](https://github.com/neoforged/NeoForge/assets/15868585/fc90bd4a-c193-48b4-9638-1f94da9dd48b)

**Comment by dhyces** [comment]
Not a neoforge problem, MC changed their system to accept alpha values, so you have to prefix your color with FF. in your case, change `56063` to `0xFF00DAFF`

**Comment by ChampionAsh5357** [comment]
> Not a neoforge problem, MC changed their system to accept alpha values, so you have to prefix your color with FF. in your case, change `56063` to `0xFF00DAFF`

This, so closing.
