### ISSUE TITLE
ScreenEvent.BackgroundRendered not called for AbstractContainerScreen

### ISSUE THREAD

**Issue by JaisDK** [neoforged/NeoForge#1182]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.37-beta

**Logs:** 

**Steps to Reproduce:**
 1. Extend `AbstractContainerScreen` and call `this.renderBackground`
 2. Subscribe to `ScreenEvent.BackgroundRendered`
 3. event does not fire

**Description of issue:**
`AbstractContainerScreen` now has a `renderBackground` method preventing `Screen.renderBackground`, where the event is fired, from being called

**Comment by Spinoscythe** [comment]
@JaisDK correct me if I'm wrong, but the event for container screens is `ContainerScreenEvent.Render.Background`?

**Comment by JaisDK** [comment]
That would probably work. I guess in 1.20.1 they were both fired.

**Comment by ChampionAsh5357** [comment]
Reopening this as it is an actual bug.

**Comment by ChampionAsh5357** [comment]
And now I'm closing again since it's a duplicate of #1077! Should really pay attention more. Sorry.
