### ISSUE TITLE
ArrowLooseEvent isn't fired when a bow is used

### ISSUE THREAD

**Issue by NewJumper** [neoforged/NeoForge#1188]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.37

**Logs:** No logs, just an event not being fired when a bow is used.

**Steps to Reproduce:**
 1. Subscribe to `ArrowLooseEvent`
 2. Shoot an arrow in game using a bow
 3. Event isn't fired

**Description of issue:**
When a bow is used, `ArrowLooseEvent` isn't fired. When a crossbow is used however, the event *is* fired.

**Comment by sciwhiz12** [comment]
Confirmed. It seems the patch was set aside [during 1.20.5 porting](https://github.com/neoforged/NeoForge/blob/acab30d512e2854d01f8c4539567d1ef85ba178a/patches/net/minecraft/world/item/BowItem.java.patch#L8) to be fixed later, which was never done.
