### ISSUE TITLE
Particles Causing Crashes

### ISSUE THREAD

**Issue by Likeabozz123** [neoforged/NeoForge#1196]
**Minecraft Version:** 1.20.6

**NeoForge Version:** 20.6.119

**Logs:** 

**Steps to Reproduce:**
 1. Create a particle (based on neoforge docs)
 2. Spawn it in game
 3. Crash 😔 

**Description of issue:**

![image](https://github.com/neoforged/NeoForge/assets/35073391/0fe35888-12f6-4de5-b21d-888e18c6f72e)

**Comment by ChampionAsh5357** [comment]
This a documentation issue. Not an issue with NeoForge itself. So, I will close this issue.
