### ISSUE TITLE
[1.21] `CustomizeGuiOverlayEvent$Chat` patch is missing, event never fires

### ISSUE THREAD

**Issue by Fuzss** [neoforged/NeoForge#1208]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.42-beta

**Description of issue:**
`CustomizeGuiOverlayEvent$Chat` used to fire from `ExtendedGui::renderChat`. The whole class has been removed from Neo for 1.21 in favor of extensive patches to `Gui` complementing vanilla's new layer system. Migrating `CustomizeGuiOverlayEvent$Chat` to `Gui` as well seems to have been missed.

The patch for firing the event should ideally be added back to `Gui::renderChat` which is the nearly identical vanilla counterpart to the old `ExtendedGui::renderChat`.

**Comment by sciwhiz12** [comment]
Confirmed. Issue description is substantially correct, except that `ExtendedGui` was removed in 1.20.5 (as it still exists in [`20.4-stable`](https://github.com/neoforged/NeoForge/blob/20.4-stable/src/main/java/net/neoforged/neoforge/client/gui/overlay/ExtendedGui.java) but not in [`20.5`](https://github.com/neoforged/NeoForge/blob/20.5/src/main/java/net/neoforged/neoforge/client/gui/overlay/ExtendedGui.java).
