### ISSUE TITLE
PlantType pull #971 appears to have made custom farmland unreliable

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#1209]
With the replacement of the PlantType system, it appears that custom farmland-type blocks can't natively support crops in a reliable way.

With the new system, it appears as though you're expected to use IBlockExtension#canSustainPlant in your farmland
![image](https://github.com/neoforged/NeoForge/assets/7098525/d6a152cb-a606-4214-b064-c2640e39ebb4)

However, CropBlock's implementation means that if you return true for this, you bypass the light check (and the super check, but that's mostly irrelevant here)
![image](https://github.com/neoforged/NeoForge/assets/7098525/ebdff3ba-8eb2-4a2f-b4f2-16a5b396670e)

So that would require you implement the light check yourself
![image](https://github.com/neoforged/NeoForge/assets/7098525/66081510-838f-4530-8b80-6df61c22987d)

There's two problems with this:
1. The method is protected, so it's not accessible without an additional AT we shouldn't need to have
2. The method requires a LevelReader, which canSustainPlant does not provide. You _could_ check & cast BlockGetter, however at that point you're basically saying that any time that method is called externally with a different BlockGetter, you can't check light

So ultimately I have two questions:
1. Should custom farmland now require an AT?
2. Should custom farmland now be unable to check base functionality (light) reliably in its own interface

**Comment by TelepathicGrunt** [comment]
Just a heads up, with Farmland specifically, [this PR](https://github.com/neoforged/NeoForge/pull/1197) will allow you to have your soil block extend FarmBlock and work out of the box with all vanilla crops and possibly other mods too (with light level respected as well)

For other non-farmland cases where light checks is wanted, I'll still investigate this for solutions

**Comment by Tslat** [comment]
> Just a heads up, with Farmland specifically, [this PR](https://github.com/neoforged/NeoForge/pull/1197) will allow you to have your soil block extend FarmBlock and work out of the box with all vanilla crops and possibly other mods too (with light level respected as well)
> 
> For other non-farmland cases where light checks is wanted, I'll still investigate this for solutions

Question - could this have been better suited as a tag?

**Comment by TelepathicGrunt** [comment]
Did some investigation, the hooks for the soil patches only have BlockGetter available and thus, I cannot change the level to something higher. So my recommendation is modders do `instanceof BlockAndTintGetter` in the soil  and use that for light checks. The hasSufficientLight method in CropBlock will be AT'ed in https://github.com/neoforged/NeoForge/pull/1197 so that light checking method can be used for various stuff easier.

> Question - could this have been better suited as a tag?

It was originally and then another maintainer pointed out vanilla client issues:
![image](https://github.com/neoforged/NeoForge/assets/40846040/01bac743-5f37-48c4-bdbb-20dac0714702)

**Comment by Tslat** [comment]
fk
