### ISSUE TITLE
Data Attachment Changes desync MobEffects on Players (possibly other entities too?)

### ISSUE THREAD

**Issue by GaunerDev** [neoforged/NeoForge#1217]
**Minecraft Version:** 1.21.0

**NeoForge Version:** 21.0.50-beta

**Logs:** none, does not crash (i hope this is still the correct place to report this)

**Steps to Reproduce:**
 1. Have an easily modifyable Data Attachment
 2. Apply any number of mob effects on yourself
 3. Perform an action that modifies the Data Attachment on your Player Entity
 4. One MobEffect will be removed in the client only
 5. The particles will keep rendering, but when testing player.hasEffect(<some effect that should be there>) it returns false on the client
 6. (optional) waiting for a varying amount of time (usually a few seconds) will make the effect fully re-appear and become available in the client again

**Description of issue:**
There seems to be an order in which effects are temporary dropped from the client. In my testing I used Strength, Fire Resistance and Underwater Breathing. They always were removed in the same order of Fire Resistace -> Strength -> Underwater Breathing. I intentionally tested this with vanilla MobEffects applied by vanilla means to rule out implementation errors on my part. Since only one MobEffect gets dropped per DataAttachment update, it seems like an off-by-one somewhere in the logic that handles the data change, but thats just a guess on my part. Since I do not know where that stuff is handled I can't take a look myself :) Hope this helps

**Comment by XFactHD** [comment]
I cannot reproduce this with a simple test setup with the specified version, neither in singleplayer nor on a dedicated server:
- `AttachmentType<String>` (without owner capture of course)
- Apply the three effects listed above via commands
- Call `Player#setData()` with the above type and a random value on the server in `Item#use()`
- Spam action bar with a message indication whether the effects are present by calling `Player#hasEffect()` in `Item#inventoryTick()` on the client

This sounds like an issue with the implementation of your specific data attachment, so we'd need significantly more details on that.

**Comment by GaunerDev** [comment]
It appears that the issue is probably in one of my own systems interacting with MobEffects, sorry for the irrelevant issue. If you couldn't reproduce it im 99% certain this issue can be closed and is not a general thing applicable to the current build, but just an implementation error on my part. I went ahead and closed it - unless somebody else runs into similar behavior I don't see a point in re-opening it
