### ISSUE TITLE
The icons of the "Minecraft Realms" button are not correctly positioned.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#1222]
**NeoForge Version:** 21.0.52-beta

**Description of issue:**
The icons of the "Minecraft Realms" button are not correctly positioned.

NeoForge:
![2024-07-03_19 44 03](https://github.com/neoforged/NeoForge/assets/68275908/eec8258f-1500-4064-96b3-c0f436c847e8)

Vanilla:
![2024-07-03_19 44 52](https://github.com/neoforged/NeoForge/assets/68275908/23f060aa-0a31-433f-b09f-a94369c34315)

**Comment by ApexModder** [comment]
just to lessen the amount of variables at play, could you recreate the issue with your resource pack(s) disabled.

**Comment by Lolothepro** [comment]
> just to lessen the amount of variables at play, could you recreate the issue with your resource pack(s) disabled.

![2024-07-03_20 00 36](https://github.com/neoforged/NeoForge/assets/68275908/1e7b9322-1f4e-4397-8caa-1cb85aae2900)

**Comment by HenryLoenwind** [comment]
The icons are at `this.height / 4 + 48  + 48 + 2 + icon_specific_offset`in the notification screen that's used as overlay.

In TitleScreen the button goes to `this.height / 4 + 48 + 24 * 2` originally and to `this.height / 4 + 32 + 24 * 2` with the patch.

Ok, I got this one, simple fix to convoluted code.
