### ISSUE TITLE
Invalid path file for the logo crash the game

### ISSUE THREAD

**Issue by castilio20** [neoforged/NeoForge#1224]
**Minecraft Version:** {1.21}

**NeoForge Version:** {NeoForge version. 0.52*}

crashlog
https://mclo.gs/6WxORFU

#997

**Comment by sciwhiz12** [comment]
Confirmed. To remedy the lack of instructions in the original description:

1. Set the (root) `logoFile` property in the `neoforge.mods.toml` to a blank string.
2. Launch the game.
3. Go to the mods list tab, and select the mod which that property applies to. (For the `neoforge.mods.toml` in the NF-dev environment, that would be the NeoForge logo.)
	- Observe the game crashing.
