### ISSUE TITLE
It possible to support Velocity?

### ISSUE THREAD

**Issue by Sam-Chai** [neoforged/NeoForge#123]
We all know the Forge TEAM and Lex don't like Velocity or Waterfall bungee. But is it possible to support it in NeoForge?

**Comment by sciwhiz12** [comment]
Could you clarify on what you mean by "support"? As far as I know, there's no support insofar as there is nothing to give support with regards to Neo/Forge; issues are often proxy-specific, and therefore usually require fixing on the side of the server proxy.

What special compatibility would Velocity, Waterfall, or BungeeCord require, outside of the mechanisms imposed by vanilla? Would these compatibility mechanisms be useful for other proxies?

**Comment by Technici4n** [comment]
It should be supported fine starting from 1.20.2 with the introduction of the configuration phase.

**Comment by Shadows-of-Fire** [comment]
> Could you clarify on what you mean by "support"?

I assume they mean something like https://github.com/MinecraftForge/MinecraftForge/pull/9313, though the [Configuration phase](https://www.minecraft.net/en-us/article/minecraft-snapshot-23w31a) introduced by Mojang in 1.20.2 will provide such functionality, which leaves nothing to be done from our end aside from a proper implementation of the phase (which we will provide).

If you think there are additional things that need support beyond this, feel free to open issues detailing such needs, but I believe the new phase covers most of what proxy systems require for bouncing modded connections.
