### ISSUE TITLE
1.21 Armor is taking extra damage beyond what vanilla does when player is hit

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#1233]
My test was just netherite chestplate + husk, advanced tooltip, and watching the durability. It should match between vanilla and neo when same damage.

What I am seeing is vanilla drain durability by 1 for every Husk hit. In Neo, it is draining by 3. 

Neoforge 21.0.55.

Likely cause is the Damage pipeline work: https://github.com/neoforged/NeoForge/pull/792

**Comment by Inonedn** [comment]
Unbreaking may also not be working, and this is the intended vanilla behavior
![image](https://github.com/neoforged/NeoForge/assets/36087299/b29bfcd4-247f-4106-8e15-587d022d8422)
