### ISSUE TITLE
Steel

### ISSUE THREAD

**Issue by Teatime4tugboat** [neoforged/NeoForge#1234]
When you use 9 modern industrialisation steel  to craft a block and then use said block to craft back into 9 ingots it gives you 9 steel ingots from mekanisim rather than modern industrialisation not a huge issue but wanted to report it none the less

**Comment by Technici4n** [comment]
That's not a NeoForge problem, that's a Mekanism issue I would say. MI's uncrafting recipe will only accept MI ingots to prevent this exact issue.
