### ISSUE TITLE
[1.21 RFC] Removal of captureDrops patch in Entity

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#1237]
I noticed we have a patch for captureDrops in Entity class. However, upon looking closer at it, I don't see how exactly this is even useful at all. Or even possible to be used.
https://github.com/neoforged/NeoForge/blob/6b09a51cebd6ad6ddc838ddacafe93f03bab0f3f/patches/net/minecraft/world/entity/Entity.java.patch#L463-L479

It looks like if you shear a mob, drop item, villager drops bread, or arrow/trident hits a mob that is immune to damage, they all spawn an item entity in world and add it to the entity's captureDrops. Oddly, it looks like captureDrops never is cleared for villagers or arrow/tridents (but the last two get discarded anyway). So Villager's captureDrops just grows over time...

And for the player drop, the onPlayerTossEvent, it clears captureDrops, calls player drop method which sets the captureDrops, and then set captureDrops to null before firing the event. So like, how are you supposed to use captureDrops if it isn't even set when you use the toss event?

I guess you are supposed to use EntityJoinLevelEvent to detect the new ItemEntity, get the owner, and then get that owner's captureDrops to do something with it? But this is so janky.

Closest I can find for the reason for having captureDrops: https://github.com/MinecraftForge/MinecraftForge/pull/4673
![image](https://github.com/neoforged/NeoForge/assets/40846040/2c15f5ce-4af7-4ee7-8603-e97045063aff)

Perhaps we could do a scream test of removing this patch? And investigate how Sponge even works with this patch?

**Comment by TelepathicGrunt** [comment]
Hmm there seems to be a capturedDrops patched into Block class as well.

**Comment by pupnewfster** [comment]
Maybe things have changed since 1.20.1, but at least then, capture drops definitely made the logic for the shearing patches much cleaner. See #581

**Comment by TelepathicGrunt** [comment]
Did more research and yep, it is used in Shears logic. Seems to be that this is setup where by default, captureDrops is null and has no effect on vanilla behavior. It's when Neo is about to do some hook logic, that we assign a list to captureDrops, run the vanilla drop code, the non-null captureDrops then takes in the ItemEntity and prevents it from spawning, and then returns the list of captured ItemEntities to Neo. Then Neo sets captureDrops to null again and does the rest of its event or hook logic with the captured ItemEntities and spawn them in the world on Neo's side.

It's effectively a carrier of data to be used for Neo logic. That's why I was confused as I was looking for a Modder exposed side of it when this is more of an internal process for Neo.
