### ISSUE TITLE
Addition of MINABLE_WITH_SHEARS blocks tag

### ISSUE THREAD

**Issue by skiprocks999** [neoforged/NeoForge#124]
Hello,

I would like to request the inclusion of a MINEABLE_WITH_SHEARS block tag to be included officially with baseline Forge (or NeoForge as it's now known). Currently, the only way to reliably add a block that the shears can mine is by adding it to either BlockTags.LEAVES or to BlockTags.WOOL (or some cursed Mixin you get the idea). This of course has the downside of adding blocks to those tags and potentially giving them unwanted behavior, especially with crafting and world interaction. As all the other tools have such a tag, it makes sense that the shears would have its own mining tag too. I would be willing to implement the feature and pull it if needed.

**Comment by pupnewfster** [comment]
[We already replace](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/minecraftforge/common/data/ForgeLootTableProvider.java#L59) vanilla loot tables that require shears for breaking with checking if the stack has the `SHEARS_DIG` tool action. Is there some use case that is not covered by this change?

**Comment by skiprocks999** [comment]
To be honest I have been kind of winging it for tools since the 1.17 update; I was unaware that forge added this feature. So I would need to both add this to my loot tables for specific blocks and items, and also have my tool return true when said ToolAction is checked. This would satisfy all of my use case conditions.

**Comment by Random832** [comment]
> [We already replace](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/minecraftforge/common/data/ForgeLootTableProvider.java#L59) vanilla loot tables that require shears for breaking with checking if the stack has the `SHEARS_DIG` tool action. Is there some use case that is not covered by this change?

To my understanding the main issue is the effect on mining speed, not loot. Shears have hardcoded logic for *three different levels* increased mining speed for various types of block. do we want multiple tags to match? swords do the same for cobwebs, for that matter. Also, is there some reason I'm missing for why this can't be handled by the block in getDestroyProgress, as Bamboo does to make swords instamine it?

Also worth mentioning that most blocks whose vanilla loot tables care about shears have the IForgeShearable interface default implemented on their classes, something that is very different from the use of the interface on entities. Removing these was part of a failed PR I made a while back to rework shearing which would have only used the interface for dispenser logic [whereas right now we have no hooks for shears in dispensers]

**Comment by KnightMiner** [comment]
One of the problems with migrating shear mining logic to tags is it will break when a Forge server is connected to a vanilla client, as its possible a datapack will change the tag contents from the vanilla list. (Forge client on vanilla server shouldn't cause problems as long as tag defaulting still works)

`getDestroyProgress` is probably sufficient for handling this at a code level in my experience. It does lead to potential issues with modded shears, but proper use of tool actions prevents that from being a problem.

**Comment by Shadows-of-Fire** [comment]
Datapacks that modify forge tags are allowed to break vanilla, since the server owner has decided that they wish to install that datapack which knowingly modifies tags that are forge-specific.

Only datapacks which modify vanilla tags should not break vanilla compat.

**Comment by KnightMiner** [comment]
That has not been the case in the past with Forge, is this a change in policy for NeoForge?

Personally, it sounds problematic to me that server owners are required to know which Forge features cause desyncs just to install datapacks. Mods have the ability to reject an unmodded client, datapacks do not.
