### ISSUE TITLE
1.21 Attribute Modifiers added by enchantments.json are not functional

### ISSUE THREAD

**Issue by Kettle5000** [neoforged/NeoForge#1242]
When creating a new json file to add a new enchantment I noticed that it is possible to add attribute modifiers with this.
The tooltip in the item shows the attribute modifier but it doesnt do nothing.
Basically the modifier added is only visual.
Try this file in neoforge version 21.0.0-beta.
[vitality.json](https://github.com/user-attachments/files/16115078/vitality.json)
and check how your max hp never gets above 20.

**Comment by Shadows-of-Fire** [comment]
I am unable to reproduce this on 21.0.65 by checking with the Fire Protection enchantment.
![](https://i.imgur.com/iRLgzzL.png)

**Comment by TelepathicGrunt** [comment]
@Kettle5000 Testing your json file in neoforge 1.21 is working for me 
![image](https://github.com/neoforged/NeoForge/assets/40846040/e251f7c3-14f5-4bec-993f-3adab2302018)
![image](https://github.com/neoforged/NeoForge/assets/40846040/3a946b28-6c07-47e4-b187-f5f40e9ad47f)

**Comment by Kettle5000** [comment]
tested again in neoforge version 21.0.0-beta
![image](https://github.com/neoforged/NeoForge/assets/93736713/8008b164-fb7d-448c-b575-e9fcf5c95461)
![image](https://github.com/neoforged/NeoForge/assets/93736713/549396b6-0c26-4970-99a9-fb8226939c2b)
Gonna test it on 21.0.65

**Comment by TelepathicGrunt** [comment]
Yeah, generally if you notice a bug, trying the latest version of Neo is recommended as we did do lots of fixes and stuff. My test was with latest Neo at the time

**Comment by Kettle5000** [comment]
Fixed in 21.0.65
closed as fixed.

**Comment by TelepathicGrunt** [comment]
Another maintainer checked and pointed out the issue was fixed in 21.0.12 neoforge by this PR so all should be good yeah
https://github.com/neoforged/NeoForge/pull/1121
