### ISSUE TITLE
[ 1.20.1 ] Neoforge server idle load (expectation) load it is more (5000 ms)

### ISSUE THREAD

**Issue by steam9w** [neoforged/NeoForge#125]
Minecraft Version: 1.20.1

Forge Version: 47.1.76

Logs: spark
https://gist.github.com/steam9w/8ea233148b20e34e45fca3a2c67aab31

Steps to Reproduce:
NO MODS SERVER
New World
SERVER 1.20.1
neoforge server idle load (expectation) load it is more (5000 ms)
vanilla server minecraft (0.500 ms)

Description of issue:
![image (6)](https://github.com/neoforged/NeoForge/assets/89272603/282c1d14-e455-411f-860e-dd45a097664a)

**Comment by sciwhiz12** [comment]
Please provide logs (the `debug.log` and, if possible, a _full_ [spark](https://spark.lucko.me) report) for both the NeoForge server and the vanilla server. We cannot determine anything conclusive from the mere screenshot and copy-pasted snippet of the profiing report.

**Comment by sciwhiz12** [comment]
Due to lack of response from the author, I'm closing this issue as lacking enough information to take action on.
