### ISSUE TITLE
BuildCreativeModeTabContentsEvent has insertBefore and insertAfter reversed

### ISSUE THREAD

**Issue by Edivad99** [neoforged/NeoForge#1254]
If I use insertBefore it puts my item after the specified one and vice versa

**Comment by TelepathicGrunt** [comment]
AAAAAAAAAAAAAAA
![image](https://github.com/neoforged/NeoForge/assets/40846040/1d55496e-7212-4e79-8d5a-2be1d38d7f34)

will fix. Could've sworn I tested in game

**Comment by dhyces** [comment]
yeah, wonder why the tests didn't catch this either?

**Comment by TelepathicGrunt** [comment]
I see now. The unit test for the ordering was off. Gotta fix that and afterwards, we will never have this mixup again
