### ISSUE TITLE
Missing event firing when player changes dimension

### ISSUE THREAD

**Issue by CodexAdrian** [neoforged/NeoForge#1263]
**Minecraft Version:** 1.21
**NeoForge Version:** 21.0.61-beta

**Description of issue:**

In the base entity `changeDimension` method, the `EntityTravelToDimensionEvent` is always called once at the beginning of the method, even when the destination level is the same as the current level. In players however, this event is only called when the destination level is different than the current level. In fact, there seems to be no event whatsoever thats fired when the Player is teleported with `changeDimension` and the target level is the same.

**Comment by sciwhiz12** [comment]
Confirmed on https://github.com/neoforged/NeoForge/commit/5b7e7905f954438cacde60540e2c264a4f47666a / 21.0.77-beta. The call was moved to its current position from its previous position at the start of the `changeDimension` call during 1.21 porting.

Looking at the code, I think it would've been logical to assume that position is correct if we assume the event is only called when changing between different dimensions (not a mere intra-dimension teleport).

However, I do agree that the event should be called for the intra-dimension teleport to cover all calls to `changeDimension`, particularly in light of the call to `PostDimensionTransition#onTransition` whether it is an intra- or inter-dimension teleport.
