### ISSUE TITLE
[1.21] Rounding error causes pathfinding issues with certain entity sizes.

### ISSUE THREAD

**Issue by bconlon1** [neoforged/NeoForge#1274]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.40-beta

**Logs:** N/A

**Steps to Reproduce:**
 1. Create an entity, with an entity type that is sized with a width of a `0.95F`.
 2. Mark debugging breakpoints in `PathNavigation#followThePath()` to log the values of `this.maxDistanceToWaypoint`, `d0`, and `d2`; see: https://github.com/neoforged/NeoForge/blob/e7daacf1334347b8a2c8078fb2b390ae6f06245b/patches/net/minecraft/world/entity/ai/navigation/PathNavigation.java.patch#L7-L13
 3. Observe values; `this.maxDistanceToWaypoint` will compute to 0.475, while `d0` and `d2` will compute to a similar value with a rounding error 0.4750000238418579.

**Description of issue:**
The patch for `PathNavigation#followThePath()` seems to cause a rounding error in specific circumstances dependent on an entity type's sizing, assumedly from conversions between float and double. The effects of this are that it can cause an entity to be at its targeted pathfinding node and yet the check for that will fail due to the rounding error, so the path never advances and the entity will stay stuck (although the entity seems to be able to get unstuck when interacted with by another entity). 

Changing the entity type sizing to a different value seems to work as a developer solution to this issue, but it's not an easy issue to pinpoint the cause of, so some might not even realize that's what's going on here.

**Comment by embeddedt** [comment]
It might be necessary to add the `int` casts as was done here: https://github.com/MinecraftForge/MinecraftForge/pull/6456

Seems they were lost during the 1.15->1.16 update.

**Comment by TelepathicGrunt** [comment]
@embeddedt That seems to be for a different issue involving jittery/spinning movements. There was a time when entities got stuck in Forge too and that was fixed by this commit 
https://github.com/MinecraftForge/MinecraftForge/commit/a2bd95ca39a1908fa06e0859760d7482cf6fe23e

Issue is I am not sure why this "fix" stopped working. Or maybe it just moved the issue to a different size than the one in the original issue report

**Comment by embeddedt** [comment]
There were multiple patches needed for the full fix; the `int` casts are important as far as I know. It would be worth checking if they are enough to resolve the rounding error.
