### ISSUE TITLE
Namespace and Path switched in some RegisterGuiOverlaysEvent methods (1.20.2 to 1.20.4)

### ISSUE THREAD

**Issue by yurisuika** [neoforged/NeoForge#1275]
**Minecraft Version:**
1.20.2 to 1.20.4

**NeoForge Version:**
up to 20.4.237

**Description of issue:**
I noticed that the versions of the methods that take in a string and attempt to create a ResourceLocation have the arguments swapped for some of the methods.

Correctly, some are `new ResourceLocation(ModLoadingContext.get().getActiveNamespace(), id)`, but others are `new ResourceLocation(id, ModLoadingContext.get().getActiveNamespace())`, which would be like doing `hunger_restored:appleskin` instead of `appleskin:hunger_restored`.

I haven't checked 20.3, but I have noted this occurs in `registerBelowAll` in 20.2 and 20.4.

**Comment by Matyrobbrt** [comment]
String overloads for the event's register methods (now named `RegisterGuiLayersEvent`) no longer have plain string arguments, as they have been removed with the overlay refactor in 1.20.5. 
We're not actively maintaining 1.20.2 to 1.20.4, but if anyone would like to fix those methods they're welcome to send a Pull Request and we will accept the PR, as is the case with any older version.
