### ISSUE TITLE
CapabilityHooks#registerVanillaProviders overwrites Mod-registered Capabilities in some Scenarios

### ISSUE THREAD

**Issue by klikli-dev** [neoforged/NeoForge#1288]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.86-beta (but reproduces as early as .65-beta and probably all the way before too on 1.21

**Logs:** No logs but a related bug report https://github.com/klikli-dev/occultism/issues/1148

**Steps to Reproduce:**
 It reproduces consistently with this mod combination: https://github.com/klikli-dev/occultism/issues/1148#issuecomment-2223467526 but ONLY in production, e.g. on a curseforge profile, not if I have the same mods via cursemaven in the MDK.
However, I believe that to be only a happy accident, because the underlying issue seems to be the event registration order. If a 1:1 repro is needed anyway I can provide a curseforge pack defintion and a video.

**Description of issue:**
CapabilityHooks#registerVanillaProviders is added as listener with EventPriority.NORMAL.
Most mods will also add their listeners with this priority, especially for capabilities.

It seems the order of events with the same priority depends on factors that are not entirely deterministic from a modder's perspective (e.g. other mods present impact that?). 

As a result I had the situation that in the MDK, my item capability handler for my custom entity was added before the vanilla provider, which resulted in everything working.
In *some* modpacks, however (such as the above combination) my custom handler was added after the vanilla provider. Because the vanilla provider returns a capability for every living entity, my own handler is never returned (See EntityCapability#getCapability which returns on the first non-null cap) 

This can be solved by registering my handler with a higher priority, however I believe that that is not desired behaviour. The vanilla providers should likely be registered with a lower priority than normal, to avoid this "undetermined" behaviour if modders use the default priority.

**Comment by Technici4n** [comment]
Yes I agree. "Fallback" capability providers should be registered with a LOW priority.
