### ISSUE TITLE
says ... is not a valid mod file

### ISSUE THREAD

**Issue by ff6f8d68** [neoforged/NeoForge#1291]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.2-beta

**Logs:** 
https://mclo.gs/Z3qrSN4

**Steps to Reproduce:**
 1. install neoforge 20.4.2-beta, minecraft 1.20.4 in prismlauncher
 2. install these mods:
https://modrinth.com/mod/architectury-api
https://modrinth.com/mod/drippy-loading-screen
https://modrinth.com/mod/dynamic-fps
https://modrinth.com/mod/fancymenu
https://modrinth.com/mod/konkrete
https://modrinth.com/mod/melody
https://modrinth.com/mod/l1rj36Ob
 4. launch minecraft
**Description of issue:**
says <every mod installed> is not a valid mod file

**Comment by Matyrobbrt** [comment]
> Missing required field mandatory in dependency (architectury-11.1.17-neoforge.jar)

Please update to the latest NeoForge version, you're using an outdated one which architectury is not built for.

**Comment by ff6f8d68** [comment]
i am using prismlauncher and this is the newest 1.20.4 version there

**Comment by Matyrobbrt** [comment]
`20.4.237` is the latest NeoForge version for 1.20.4

**Comment by ff6f8d68** [comment]
in prismlauncher i sayed

**Comment by epicacrylic** [comment]
Same problem, but scrolling through the versions showed the `20.4.237` version. Might be an issue with PrismLauncher

**Comment by ff6f8d68** [comment]
ok
