### ISSUE TITLE
Some biome tag issues

### ISSUE THREAD

**Issue by Mechalopa** [neoforged/NeoForge#1300]
- `minecraft:frozen_river` is not contained in `c:is_cold/overworld` and `c:is_snowy` biome tags.
- `minecraft:sparse_jungle` is not contained in `c:is_sparse_vegetation/overworld` biome tag.

I hope I have not missed the reason why it was not contained intentionally....

**Comment by TelepathicGrunt** [comment]
https://github.com/neoforged/NeoForge/blob/ca2abd5d7b34a2cbcd2a4fd7ef787cf054c1bed2/src/generated/resources/data/c/tags/worldgen/biome/is_cold/overworld.json#L13

It's in cold overworld. It isn't in snowy as snowy is more about actual snow blocks on ground. I would expect people targeting snowy tag to not expect frozen river which has no snow. Just ice.

Just the sparse jungle is bugged
