### ISSUE TITLE
TransparentBlock is protected

### ISSUE THREAD

**Issue by Ioandar** [neoforged/NeoForge#1301]
**Minecraft Version:** {Minecraft version}
1,21

**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}
neo_version=21.0.86-beta

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
no logs
**Steps to Reproduce:**
Try to register a **TransparentBlock** It is protected in neoForge

**Description of issue:**

forge 1.21
```
 public TransparentBlock(BlockBehaviour.Properties p_312723_) {
        super(p_312723_);
    }
```

neoForge 1.21
```
    protected TransparentBlock(BlockBehaviour.Properties p_309186_) {
        super(p_309186_);
    }

**Comment by TelepathicGrunt** [comment]
I did some research. Forge added an AT for this in like 1.20.4. So this isn’t a regression on behavior. It’s really a feature request. 

I’ll audit all block constructors and add relevant ATs to this PR https://github.com/neoforged/NeoForge/pull/1244

**Comment by Ioandar** [comment]
I am unfamiliar with the procedures... should this remain open or should I close this?

**Comment by TelepathicGrunt** [comment]
Keep it open. This will be closed automatically when my PR with the AT (I am going to add) gets merged
