### ISSUE TITLE
Mod list renders special line ending characters

### ISSUE THREAD

**Issue by LostLuma** [neoforged/NeoForge#1316]
**Minecraft Version:** 1.21.0

**NeoForge Version:** 21.0.82-beta and above (tested up to 21.0.95-beta, current latest)

**Logs:** [latest.log](https://files.lostluma.net/U5CfQN.txt)

**Steps to Reproduce:**
 1. Install a mod that has newlines in the credits section
    In my case I installed this exact [Dynamic FPS version](https://modrinth.com/mod/dynamic-fps/version/AhFXokhh)
 2. Launch the game
 3. Open the mods list
 4. Click on the mod you downloaded
 5. See erroneous line ending characters rendered that should be invisible: [screenshot](https://files.lostluma.net/oSQJbE.png)

**Description of issue:**

Since `21.0.82-beta` the mod list renders the `cr` line ending character when viewing a mod which has a field with newlines.

**Comment by HenryLoenwind** [comment]
21.0.82 is #1239
