### ISSUE TITLE
Add a gradle task for generating ATs in Neo Dev

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#1317]
Was suggested this be done in neoDev instead of JST or AT repo. We currently have ATs that make the constructor of all non-abstract blocks be public and soon we will do the same for Particles. It would be nice to have a way to create ATs for constructors in bulk for these cases. How that looks, no idea. 

For PRs like this: https://github.com/neoforged/NeoForge/pull/1244

**Comment by ApexModder** [comment]
It was also recommended that my render type pr also have its AT changes be generated (https://github.com/neoforged/NeoForge/pull/842#issuecomment-2075084379), which would be nice to keep those ATs up to date as mojang add/remove render types in future versions
