### ISSUE TITLE
Hook for `BubbleColumnBlock#getColumnState`

### ISSUE THREAD

**Issue by skyjay1** [neoforged/NeoForge#132]
The problem: The method `BubbleColumnBlock#getColumnState(BlockState)` is hard coded to only support magma blocks and soul sand. It is not possible to create modded blocks that provide bubble columns with the current API.

The failed solution: In my testing I found that I could call `BubbleColumnBlock#updateColumn(LevelAccessor, BlockPos, BlockState, BlockState)` with a spoofed block state to place bubble columns, but the bubble column verifies itself later in its tick method, so we need a hook.

The proposed solution: add a method to `IForgeBlockState` and `IForgeBlock` to allow modded blocks to provide a bubble column block state. 

Option 1. The new method replicates the logic found in `BubbleColumnBlock#getColumnState(BlockState)` . The original method has a hook injected at the start which redirects to the block state hook.

Option 2. The new method has a return type of `BlockState` and returns null by default. The original method has a call to the new method, and if the result is not null, it immediately returns the result. If the result is null, the rest of the method executes as normal.

Option 3. The new method has a return type of `Boolean` and returns null by default. The original method has a call to the new method, and if the result is not null, it returns the bubble column block state with the `DRAG_DOWN` property set to the specified value. This ensures that the method is only used for bubble columns and not for anything else. If the result is null, the rest of the method executes as normal.

Option 3a. The same as Option 3 but with a return type of `java.util.Optional<Boolean>` and returns `Optional.empty()` by default.

Option 4. ??? Leave suggestions below

**Comment by ChampionAsh5357** [comment]
There's a lot more necessary than just adding that method. When I originally looked into that for the fluid API, there were a number of interactions with determining how bubble columns propagate within a single fluid and across multiple, which is tightly coupled along with the information being attached to a specific block to create the columns.
