### ISSUE TITLE
Add `c:enchantable` parent item tag for minecraft's enchantable tags

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#1325]
If you check vanilla, there is no `minecraft:enchantable` tag. 
https://github.com/misode/mcmeta/tree/data-json/data/minecraft/tags/item

It would make sense for us to add a parent tag for that under `c` that includes all the tags under enchantable folder. This would allow mods like Soulbound enchantment to apply to any item that is in any vanilla enchantable tag. And mods would add their enchantable items to this c tag if they don't add to a vanilla tag.

Good or no?

Fabric: https://github.com/FabricMC/fabric/issues/3947

**Comment by KnightMiner** [comment]
I feel like there is merit to consider making the tag `minecraft:enchantable` given all the other tags are subtags of it. That would make it work similarly to how `c:ingots` contains all `c:ingots/####`. This would also reduce the need for migration if vanilla ever added such a tag, which would only make sense for them to do under that name (unless vanilla devs have an adversion to a tag with the same name as a folder)

**Comment by TelepathicGrunt** [comment]
I do not feel it is the modloader's place to start shoving brand new tags under the minecraft namespace. It seems... wrong and against how modloader's operate around tags

**Comment by TelepathicGrunt** [comment]
Closing as I am an idiot and turns out we already collect these enchantments in our own parent tag lol
https://github.com/neoforged/NeoForge/blob/1.21.x/src/generated/resources/data/c/tags/item/enchantables.json

**Comment by KnightMiner** [comment]
> I do not feel it is the modloader's place to start shoving brand new tags under the minecraft namespace. It seems... wrong and against how modloader's operate around tags

Neo already shoves registry entries under `minecraft`, so this is nothing new. If its a problem for tags to be added under `minecraft:`, its a much bigger problem for registry entries to be added under `minecraft:`.

As for "against how modloader's operate around tags", its only against it because there has not been a usecase yet. This is a tag that is meant as a parent for many `minecraft:` tags, so it makes sense to be in `minecraft:`.

----

Not saying it needs to be moved for the record, just that this policy is not being applied consistently if there is one.

**Comment by TelepathicGrunt** [comment]
@KnightMiner 
> Neo already shoves registry entries under minecraft

Neo makes no tags under minecraft namespace. Never has and if so, will need to be removed or moved. Afaik, mojang does not want new datapack content put under minecraft namespace. It's specifically for vanilla. New tags and other datapackable content should be in a different namespace. Vanilla fields can be made to reference the other content if needed but the content should be under mc namespace.

Registry entries are different. Milk fluid still hated.

**Comment by TelepathicGrunt** [comment]
@KnightMiner Someone found the Mojang announcement about datapack contents: 
https://www.minecraft.net/en-us/article/minecraft-snapshot-17w43a

>Please always use your own namespace for anything new that you add, and only use other namespaces if you're explicitly overriding something else. Try not to add new things in minecraft, basically.

**Comment by KnightMiner** [comment]
Its a fair point that new content should not go under `minecraft:`, though I'd make the case this is not new content, its just a missing tag in vanilla that has everything around it defined. Its the same as if my datapack added a missing vanilla tag to a vanilla object. Though this debate is probably becoming off topic in this issue.

That said, nothing makes datapacks special here, its just that Mojang does not not currently support new registry entries being added outside of datapacks and mods should know better. So no, registry entries are not different. But yeah, thats also probably a discussion better suited elsewhere.
