### ISSUE TITLE
`ArrowLooseEvent` fired for `BowItem` passed in the wrong `ItemStack`

### ISSUE THREAD

**Issue by RaymondBlaze** [neoforged/NeoForge#1326]
Introduced by #1189 when trying to re-implement the event for `BowItem`.
```patch
 public void releaseUsing(ItemStack p_40667_, Level p_40668_, LivingEntity p_40669_, int p_40670_) {
         if (p_40669_ instanceof Player player) {
             ItemStack itemstack = player.getProjectile(p_40667_);
             if (!itemstack.isEmpty()) {
                 int i = this.getUseDuration(p_40667_, p_40669_) - p_40670_;
-                // PR #1189's implementation
-                i = net.neoforged.neoforge.event.EventHooks.onArrowLoose(itemstack, p_40668_, player, i, !itemstack.isEmpty());
+                // Correct implementation
+                i = net.neoforged.neoforge.event.EventHooks.onArrowLoose(p_40667_, p_40668_, player, i, !itemstack.isEmpty());
```
The PR mistakenly passed in the local variable `itemstack` (the projectile `ItemStack`) instead of the method parameter `p_40667_` (the bow `ItemStack`), while `ArrowLooseEvent` needs the bow/crossbow `ItemStack`.

As there's also discussions and confusions on the naming of the event in #1189, I suggest we look into rework the `ArrowNockEvent` and `ArrowLooseEvent` to provide a better support on `ProjectileWeaponItem` related events.

**Comment by Spinoscythe** [comment]
I'm making a new issue for the projectile event rework
