### ISSUE TITLE
Reimplement config accessors

### ISSUE THREAD

**Issue by Speiger** [neoforged/NeoForge#1336]
o/

Neo recently updated changes on config work and removed all the accessors that were in place.
I am fully aware that neoforge is planning to implement its own GUI at some point,
but that doesn't mean you don't have to block out the entire competition.

To make things work only 2 things have to be made accessible.
- 1: ModConfig#loadedConfig should be made accessible. Doesn't matter if the implementation itself is visible or not because the interface is enough.
- 2: ConfigTracker#configsByMods should have a readOnly accessor

These two things are enough to make neoforge compat with configs guis possible again.

**Comment by Technici4n** [comment]
Hey,

For 1. I thought that access via the ModConfigSpec should be enough. Is that not the case?
For 2. Does none of the ModConfigs methods work?

**Comment by Speiger** [comment]
hey @Technici4n 
For 1: There is no getter for it. How would i set/get entries without the ILoadingConfig? I know you can get the values out of the ModConfigSpec but that is immutable and using ConfigValue objects directly and try to ensure the type is correct is a whole different can of worms that just awaits to explode. So yeah not really an option.

For 2: Ok, i missed that but after looking over it you have to do like 2-3 function calls to achieve the same as just making a function: ``List<ModConfig> getConfigsByMod(String modId)``. Atm i would need to use getFileMap and use that to iterate over everything to then filter out every config by a specific mod if i wasn't using reflection. Since i just want to know the configs of a specific mod not a very specific config directly.

**Comment by Technici4n** [comment]
For 1. I would like to understand why you cannot use `ModConfigSpec#save` and `ModConfigSpec.ConfigValue#set`.

For 2. I opened https://github.com/neoforged/FancyModLoader/pull/185.

**Comment by Speiger** [comment]
@Technici4n It will simplify the code accross multiple systems. For example carbon config can also edit server/savefile configs.
Should i now implement 2-3 different GUI accessors so if it is client/common config (client side) that i use ConfigValue#set for those and for Common Configs (server side) and Server Configs a complete from scratch implementation because i can't load these ConfigValues without causing harm?
Also how would I load them?

The idea is just use the shared implementation with CommentedConfig and just change where the source is.

This is why i need deeper access than ConfigValue#set and the save function is basically just delivered with it but i am not sure if it is required or not. but calling loadingConfig#save at that point doesn't change a thing.

**Comment by Speiger** [comment]
About 2, thank you :)

**Comment by Speiger** [comment]
@Technici4n just in case, pinging for a response

**Comment by Technici4n** [comment]
Yeah, I did not forget but was rather busy. For 1) it is a bit more complicated; the config system is complicated, and letting users modify the raw config directly seems very error-prone to me. Carbon Config is such an overhaul/extension of the config system that it's different to cater to its needs with a simple and robust API.

**Comment by Speiger** [comment]
hmmm to be fair you have to go out of your way to even access the CommentedConfig and a simple reflection call makes it even accessible, since the mixins would even fail due to the class not being accessible.

While a robuster API would be awesome, a good accessor is really all everyone needs to get everything going ^^"
And also there are not that many Config gui mods.

**Comment by Technici4n** [comment]
Is all you need a getter in `ModConfigSpec`? Something like `@Nullable ILoadedConfig getLoadedConfig()`?

**Comment by Speiger** [comment]
@Technici4n 
These are the two reflections i use: 
- ILoadedConfig: https://github.com/Carbon-Config-Project/CarbonConfig/blob/1.21-neo/src/main/java/carbonconfiglib/gui/impl/forge/ForgeConfig.java#L67
- Map<String, List<ModConfig>>: https://github.com/Carbon-Config-Project/CarbonConfig/blob/1.21-neo/src/main/java/carbonconfiglib/gui/impl/forge/ForgeHelpers.java#L47

So yeah it would be enough :)
Though it would be nicer in ModConfig instead ModConfigSpec :)
