### ISSUE TITLE
[Loading UI] Add "Memory Usage" text on the green memory usage bar.

### ISSUE THREAD

**Issue by zyxkad** [neoforged/NeoForge#1337]
Someone is asking about why the green *loading* progress bar is jumping back. To make user more clear of what they are looking for, I suggest put a text on the bar.

![image](https://github.com/user-attachments/assets/c41ae15c-366a-405f-b635-116716ce974e)

**Comment by 3TUSK** [comment]
Technical wise, the term `Heap` and `OffHeap` shown in the screen stand for "heap memory" and "off-heap memory" respectively. 

Not sure if changing them to "heap memory" is too long to fit in. "heap mem." maybe?

**Comment by HenryLoenwind** [comment]
![image](https://github.com/user-attachments/assets/008929ab-5095-409d-bb86-8fae03cd1bdb)

Wasn't the amount inside the bar once or was this something I invented when I copied the bar for my mod?
