### ISSUE TITLE
Remove baby zombie config options in future MC version (1.21?)

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#134]
I came across this in the server config file for Neoforge which was in inherited from Forge. 
![image](https://github.com/neoforged/NeoForge/assets/40846040/b880e44a-12fa-4f1a-b648-88bfe5d4d6f5)

In my opinion, this is not the domain of a modloader API. Rather this zombie villager baby chance should be handled by a separate mod made by someone else that Neoforge loads just like any other mod when in mod folder. There's no reason for this config option to be in Neoforge itself. 

Thoughts?

Code:
https://github.com/neoforged/NeoForge/blob/0974ecc143f449087139a6923aa3f0823dce421d/src/main/java/net/minecraftforge/common/ForgeConfig.java#L26-L27

**Comment by TheCurle** [comment]
I concur. This seems within the purview of a mod like In Control! as opposed to the modloader.

**Comment by Shadows-of-Fire** [comment]
Yeah I have no idea why these were controls in the first place, they're _extremely_ old. They can be nuked next BC window.

**Comment by heipiao233** [comment]
And in my opinion, mod loaders should not fix vanilla bugs.

**Comment by AterAnimAvis** [comment]
It depends on the bug, some Vanilla bugs can adversely effect modding environments quite drastically. Fixing these at the Loader level makes sense.
However that isn't relevant in this case as this isn't a bug fix, this is an additional feature which falls in a category really outside our purview.

**Comment by heipiao233** [comment]
just btw

**Comment by TelepathicGrunt** [comment]
Also, this config isn’t even fixing any bugs. They are just… there… for no reason that I can see lol
