### ISSUE TITLE
Add Sprite Sheet animation support for particles

### ISSUE THREAD

**Issue by Anonymous2416** [neoforged/NeoForge#1344]
Instead of doing particle by splitting the sprite sheet up into multiple files, do it using 1 sprite sheet and animate it by rendering based on uv offsets 
![CleanShot 2024-07-19 at 01 00 36@2x](https://github.com/user-attachments/assets/49038831-e9c5-4349-83bc-bcbb256c207c)

**Comment by embeddedt** [comment]
FWIW, mods should already be able to do this by subclassing `TextureSheetParticle`/`SingleQuadParticle` and overriding the `getU0`, `getU1`, `getV0`, and `getV1` methods.

**Comment by XFactHD** [comment]
If the sprite needs to be selected according to the particle's age, then the solution described by embeddedt should be used. If the sprite just needs to change periodically but the starting point of the animation is not relevant, then the vanilla texture animation system can be used instead, which supports both single-column and grid sprite sheets.
As such I feel like this is out of scope for NeoForge since there are adequate solutions to this in vanilla itself.

**Comment by Anonymous2416** [comment]
> FWIW, mods should already be able to do this by subclassing `TextureSheetParticle`/`SingleQuadParticle` and overriding the `getU0`, `getU1`, `getV0`, and `getV1` methods.



> If the sprite needs to be selected according to the particle's age, then the solution described by embeddedt should be used. If the sprite just needs to change periodically but the starting point of the animation is not relevant, then the vanilla texture animation system can be used instead, which supports both single-column and grid sprite sheets. As such I feel like this is out of scope for NeoForge since there are adequate solutions to this in vanilla itself.

@embeddedt @XFactHD oh I see yea, using the get methods for the UV's I can do this based on the particles age. How would I do this though, im not very familiar with how UV's work and all that stuff, is there an example I can look at or can y'all guide me in the right direction. thanks

**Comment by XFactHD** [comment]
Please ask on the NeoForge Discord, it's easier to explain it there.

**Comment by Anonymous2416** [comment]
@XFactHD alright, thanks. can I ping you there?

**Comment by TelepathicGrunt** [comment]
@Anonymous2416 You can post in the modder-support-1.21 channel in the NeoForge Discord. Many people can jump in and help you out. I'll close this issue report since sprite animation is already possible with vanilla
