### ISSUE TITLE
unable to install the Neoforge for 1.21

### ISSUE THREAD

**Issue by Thaumarchaeota** [neoforged/NeoForge#1360]
**Minecraft Version: 1.21** {Minecraft version}

**NeoForge Version: 21.0.113-beta** {NeoForge version. *Version number, not latest/rb*}

**Logs: Failed to run processor: java.net.SocketException:Connection reset** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Description of issue: When running the installer**

**Comment by Tslat** [comment]
Unable to replicate, seems to work fine for me

**Comment by marchermans** [comment]
@Thaumarchaeota Please use our discord for support: https://discord.neoforged.net/
