### ISSUE TITLE
[1.21] Add `Player` parameter to `getCraftingRemainingItem` 

### ISSUE THREAD

**Issue by cech12** [neoforged/NeoForge#1377]
Hello,
I am using Neoforge for a while and during porting my mods I saw, that the damaging system in MC was changed in 1.21. I have fluid containers with a durability, which are damaged by using the FluidHandler as well when using them in a crafting recipe. 

Since 1.21 the `ServerLevel` is needed by the vanilla `ItemStack::hurtAndBreak` method. I managed to get the `Level` in each FluidHandler context execpt for the `getCraftingRemainingItem` method (Item, ItemStack).

I think the two methods `IItemExtension::getCraftingRemainingItem(ItemStack)` and `IItemStackExtension::getCraftingRemainingItem(ItemStack)` should get a new parameter `Player` 
https://github.com/neoforged/NeoForge/blob/d5cd24e815f630d8b2b8f7c8e15aef3997340038/src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java#L181-L194
https://github.com/neoforged/NeoForge/blob/d5cd24e815f630d8b2b8f7c8e15aef3997340038/src/main/java/net/neoforged/neoforge/common/extensions/IItemStackExtension.java#L57-L65

In `CommonHooks::getCraftingRemainingItem(ItemStack)` the crafting player is available and can be added to the method call.
https://github.com/neoforged/NeoForge/blob/d5cd24e815f630d8b2b8f7c8e15aef3997340038/src/main/java/net/neoforged/neoforge/common/CommonHooks.java#L728-L738

To avoid a breaking change the existing methods could be marked as deprecated and can get the player by the `CommonHooks::getCraftingPlayer()` methods. The new Player paremter can be added as new methods.

Please let me know what you think about this. :)

**Comment by TelepathicGrunt** [comment]
Note, these methods could be called in places that has no player. Like dispenser. Maybe Level would be a better param

**Comment by TelepathicGrunt** [comment]
actually, one second, why are you doing a hurt and break *inside* getCraftingRemainingItem? Some mods may call getCraftingRemainingItem just to inspect what the item's remainder form would be but not actually do the crafting. If you call hurt and break within there, you could be mutating an in-world state that shouldn't be mutated from a mod doing an inspection.

**Comment by cech12** [comment]
Only the returned itemstack has a lower durability. nothing is changed for the item stack parameter.

**Comment by TelepathicGrunt** [comment]
Couldn’t you set the durability data component on the itemstack directly to make it damaged instead of using hurtOrBreak?

**Comment by cech12** [comment]
I'm not at the computer at the moment. But that should have the same problem and needs the actual level if I want to use the unbreaking enchantments and similar calculations.

**Comment by TelepathicGrunt** [comment]
I would be very surprised if it did. Data component are just holders of data. In this case, the DAMAGE data component shoul only be holding an int for the damage. You would make a new damage data component object with the damage you want, take the returning item stack, and set the data component onto it. 

Level shouldn’t be involved. I think hurtAndBreak only needed the level to play sound I think

**Comment by cech12** [comment]
It is also needed for the randomized calculation of the unbreaking enchantment

**Comment by TelepathicGrunt** [comment]
Ah that blasted enchantment. Makes sense as a modder could have a tool that the remanded is the tool but damaged and they would want the unbreaking enchant to apply. Passing in level should do then

**Comment by Shadows-of-Fire** [comment]
Unfortunately this context is not known nor can it reliably be made available.  You can _try_ to retrieve it via the following steps, but we can't augment the hooks here since the call sites do not have the information in the first place.
1. You can attempt to retrieve a `Player` via `CommonHooks.getCraftingPlayer`.
2. If that fails, you will need to use `ServerLifecycleHooks` to retrieve the current server, pull the overworld, and use it for the relevant evaluation.
