### ISSUE TITLE
[1.21] NeoForge is downgrading libraries provided by Vanilla

### ISSUE THREAD

**Issue by shartte** [neoforged/NeoForge#1380]
One Example:

Vanilla 1.21 ships Gson `2.10.1`
NeoForges Vanilla Launcher profile ships with `2.10`

There are likely other examples, but this should be fixed in general across all libraries.

**Comment by Gaming32** [comment]
It occurs with Apache Commons IO as well, where I have personally experienced `NoClassDefFoundError`s on NeoForge.
