### ISSUE TITLE
Config section buttons have weird formatting

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [neoforged/NeoForge#1385]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.139-beta

**Description of issue:**
I'm working on getting the config screen working for Twilight Forest, and while it's been going great so far, one thing that stood out to me is the section buttons. 

First of all, the translation keys for them are honestly not the best. Our categories are named things like `"Dimension Settings"`, `"Portal Settings"`, etc. To translate the `Edit...` part of the button, the key will look something like `"Portal Settings.button"`. This causes a few problems, first being that other mods that have categories named like this will overlap if they both translate their buttons, another one being that something like this will be confusing for translators. I would recommend formatting the button based on the category's key, since you can change that as needed. For example, we format the section titles as `"config.twilightforest.portal_settings"`. Maybe have the key for the button be `"config.twilightforest.portal_settings.button"`?

My other gripe is with the addition of the ellipsis to the button name. I feel like some people may not want those added if they're translating the button name (I personally like it though), but if a button is being translated, I would ask that you let us decide if they should be there or not. Appending them causes issues with things like the upside-down language, so I would like to be able to place them in front of the word instead of behind in that scenario. An example of this can be seen below. 
![Ellipsis](https://github.com/user-attachments/assets/6165e173-0150-4443-b908-4436a83766b1)

I've also noticed that my client config lists can have their buttons translated, but not my common config ones? They're both done in the same way (using `defineListAllowEmpty`) so I don't quite know what's going on there. I would definitely appreciate any insight into that. 

Thanks for hearing me out! Im loving the reintroduction of the config screen, I just wanted to address the couple things I found while working with it. Everything else has been working really well!

**Comment by HenryLoenwind** [comment]
> the key will look something like "Portal Settings.button"

Confirmed bug. It should use the same key as the translation for the left column text (but with ".button" appended), not the raw config key.

> My other gripe is with the addition of the ellipsis to the button name.

That's been a UI standard for over thirty years. Vanilla Minecraft follows it, so we do too.

> upside-down language,

The ellipsis is `neoforge.configuration.uitext.section`, i.e. configurable for R-T-L languages.

> I've also noticed that my client config lists can have their buttons translated, but not my common config ones? 

Please post your builder command; there's nothing in the config screen that treats sections differently based on the config type. All the type does is determine when to enable the top-list buttons.
