### ISSUE TITLE
Configured mod problem and mod config crash problem

### ISSUE THREAD

**Issue by Rheckar** [neoforged/NeoForge#1392]
1.21 Minecraft version

21.0.143 NeoForge version

https://gist.github.com/Rheckar/e89c831f5bb9806fedfa709732bcd2ab

Steps to Reproduce:
 1. Install Neoforge
 2. Install Configured(2.5.0)
 3. Launch game.
 4. Game Crashes

Not sure how to describe this so here's the error;
An uncaught parallel processing error has occurred. 
java.lang.NoSuchMethodError: 'java.util.Map
net.neoforged.fml.config.ConfigTracker.config5ets0'

The sole problem is the configured mod. I get this error even if it's the only mod or there are 70 other mods with it. Also don't know if that's the cause but without the configured mod I can't press config on the mod list menu or the game crashes. Can't guarantee the absence of the mod configured is the problem because I haven't been able to run the game with Configured.

![aaaaaaaaaaaa](https://github.com/user-attachments/assets/6b5bf56b-0f2b-4c70-b83e-005317248a23)

**Comment by TelepathicGrunt** [comment]
Your log file shows configured crashing because it is not yet updated to handle all the breaking changes NeoForge has done. Please report to the modder so they know that Neo is now stable and they can update to the latest Neo safely. 

Many mods don’t yet have their config screen setup so removing configured will gray out a lot of mod’s config button until they opt in

If you are crashing without configured, please share that log

**Comment by Rheckar** [comment]
> Your log file shows configured crashing because it is not yet updated to handle all the breaking changes NeoForge has done. Please report to the modder so they know that Neo is now stable and they can update to the latest Neo safely.
> 
> Many mods don’t yet have their config screen setup so removing configured will gray out a lot of mod’s config button until they opt in
> 
> If you are crashing without configured, please share that log

Thanks for the reply, it doesn't crash without Configured, it only crashes if I try to config any mod.

https://gist.github.com/Rheckar/955f9855d0dda78e3c9786b27801ebf4

**Comment by Rheckar** [comment]
Checked Configured's issues and seems like a config nightconfig directory issue has been reported.
