### ISSUE TITLE
Incorrect format string in NetworkRegistry#checkPacket leads to incorrect exception

### ISSUE THREAD

**Issue by FiniteReality** [neoforged/NeoForge#1394]
See: <https://github.com/neoforged/NeoForge/blob/12f102053fbeea3800d91f8849170b6096e267d1/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L442>

Here's an example of a broken exception message:
```
fail: net.minecraft.commands.Commands
      '/ganderdebug minecraft:acacia_button' threw an exception
      java.lang.UnsupportedOperationException: Payload {} may not be sent to the client!
```

This also applies in the other overload of checkPacket.

**Comment by XFactHD** [comment]
#1190 includes a fix for this, it's still held up by reviews though
