### ISSUE TITLE
[1.21] Custom `SimpleChannelInboundHandler` to handle time packets does not get called.

### ISSUE THREAD

**Issue by LeScooter** [neoforged/NeoForge#1399]
**Minecraft Version:** `1.21`

**NeoForge Version:** `21.0.146` (Issue occurs since `21.0.129-beta` #1318 )

**Steps to Reproduce:**
 1. Create a new class that extends `SimpleChannelInboundHandler` and handles `ClientboundSetTimePacket` or `ClientboundCustomSetTimePayload`.
 2. Enter a world and observe that the server does send the time packet.
 3. Observe that the method `channelRead0` in the custom inbound handler is not called.

**Description of issue:**
I use a simple channel inbound handler to listen for time packets. I run servers for my mod, each with matches running on them. Depending on the map being played, these matches can have different times of day.

The simple channel inbound handler would listen for time packets and update the client players' time based on the match that they are currently playing in.

The following code snippet is how I register the packet listener during the player's connection.

```
@EventBusSubscriber(modid = BlockFront.MOD_ID, bus = EventBusSubscriber.Bus.GAME, value = Dist.CLIENT)
public class ClientEventHandlerPlayerNetwork {
 
    /**
     * Called when the player logs into the server / world
     *
     * @param event - Given event
     */
    @SubscribeEvent
    public static void onClientPlayerNetworkEvent(@Nonnull final ClientPlayerNetworkEvent.LoggingIn event) {
        ModLoggerUtility.log("Adding custom packet listeners for new connection...");
 
        // Add all necessary listeners to the pipeline
        final var pipeline = event.getConnection().channel().pipeline();
        pipeline.addBefore(HandlerNames.PACKET_HANDLER, "mod_packet_handler_time", new PacketListenerSetTimePacket());
 
        ModLoggerUtility.log("Finished adding custom packet listener for new connection!");
    }
}
```

The following code snippet is the initial packet handler, which would be called once per tick when receiving the time packet from the server. Neither a `ClientboundSetTimePacket` handler or `ClientboundCustomSetTimePayload` handler will call `channelRead0`.

```
/**
 * This packet listener intercepts time packets and prevents them from altering
 * the client-side level time while in a client game. This is because the client
 * game uses the day time provided by the affiliated
 * {@link com.boehmod.blockfront.common.game.references.MapType} instance
 */
public class PacketListenerSetTimePacket extends SimpleChannelInboundHandler<ClientboundSetTimePacket> {
 
    @Override
    protected void channelRead0(final ChannelHandlerContext ctx, final ClientboundSetTimePacket msg) {
        if (msg == null) return;
 
        final var clientModManager = ClientModManager.instance();
        assert clientModManager != null : "Client mod manager is null!";
 
        // Fetch the client game instance
        final var game = clientModManager.getGame();
 
        // If the client game exists, process the message
        if (game != null) {
            ctx.fireChannelRead(new ClientboundSetTimePacket(msg.getGameTime(), game.getMapType().mapTime, false));
            return;
        }
 
        ctx.fireChannelRead(msg);
    }
}
```

**Comment by sciwhiz12** [comment]
Just as a quick test: could you try changing out the `addBefore` call to `addAfter`? I seem to recall in ages past when I was attempting to insert my own handlers before an existing handler (in old Forge days of 1.18, although this is at the Netty level so it ought not to have changed much since), that I had to specifically call `addAfter` to get my handler to execute _before_ the handler I was trying run before.

Also, could you clarify if this is a regression of previously working code?

**Comment by LeScooter** [comment]
> Just as a quick test: could you try changing out the `addBefore` call to `addAfter`? I seem to recall in ages past when I was attempting to insert my own handlers before an existing handler (in old Forge days of 1.18, although this is at the Netty level so it ought not to have changed much since), that I had to specifically call `addAfter` to get my handler to execute _before_ the handler I was trying run before.
> 
> Also, could you clarify if this is a regression of previously working code?

- I can confirm that this is a regression of previously working code. The handlers worked fine before the provided PR was merged.

- I can also confirm that changing out `addBefore` with `addAfter`, with version `21.0.146`, has not fixed the issue.

**Comment by HenryLoenwind** [comment]
I know little about the network system, but from a first look:

For the new payload (that is sent to all and only neo clients), you need to intercept `ClientboundCustomPayloadPacket` and then get the payload from that. Unlike the vanilla ClientboundSetTimePacket, the modded payload is wrapped and not sent as-is.

On the client side, it is handled in `net.neoforged.neoforge.network.registration.NetworkRegistry.handleModdedPayload(ClientCommonPacketListener, ClientboundCustomPayloadPacket)` which then hands it of to the registered handler, `net.neoforged.neoforge.network.handlers.ClientPayloadHandler.handle(ClientboundCustomSetTimePayload, IPayloadContext)`. So, there is no way to intercept the packet based on the payload type.

---

Edit: But I find it a bit strange to intentionally desync the client from the server by intercepting packets client-side. Wouldn't your purpose be better served by suppressing the time change server-side and sending your own packet (or a modified time packet) with whatever extra data you want to send?

---

For this specific use case, replacing the handler for `PLAY, neoforge:custom_time_packet` in `net.neoforged.neoforge.network.registration.NetworkRegistry.PAYLOAD_REGISTRATIONS` with your own handler might be a solution. That way you could make the client either ignore the normal time packet completely (and if you set the time speed to 0, you can take over time progression in your tick handler), or modify the values you set.

I don't think this is a supported operation, but it's a HashMap, so it is easy to modify.

**Comment by LeScooter** [comment]
@HenryLoenwind Thank you for the response. I appreciate it greatly.

I've created a new inbound handler that listens for `ClientboundCustomPayloadPacket`, which fires off successfully. I can also successfully fetch the `ClientboundCustomSetTimePayload` instance via `msg.payload()`. Thank you very much!

**Comment by LeScooter** [comment]
This is no longer an issue, as you can successfully handle the payload by listening for `ClientboundCustomPayloadPacket` types.
