### ISSUE TITLE
[1.21] Registering too many GUI layers causes some to be invisible

### ISSUE THREAD

**Issue by embeddedt** [neoforged/NeoForge#1400]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.112-beta

**Description of issue:**

Presumably due to the `LayeredDraw` system using a fixed Z separation of 200 units between layers, adding enough layers causes the top ones to become invisible.

To reproduce, add a loop like below to any mod that renders a custom GUI layer and run it standalone. The modded layer will be invisible.

```java
private void onRegisterGuiLayers(RegisterGuiLayersEvent event) {
    // Register some placeholder layers
    for(int i = 0; i < 50; i++) {
        event.registerAboveAll(ResourceLocation.fromNamespaceAndPath(MOD_ID, "fake_" + i), new LayeredDraw.Layer() {
            @Override
	    public void render(GuiGraphics guiGraphics, DeltaTracker deltaTracker) {
					
	    }
        });
    }
    // Register the real layer
    event.registerAboveAll(ResourceLocation.fromNamespaceAndPath(MOD_ID, "hud"), new ModdedHUDRenderLayer());
}
```

**Comment by KyBeeS** [comment]
Issue is occurring again in current release of all the mods 10. We're having issues reproducing it with other mod combinations and it's seemingly random. Seems it may be a neoforge issue but we're not sure

**Comment by XFactHD** [comment]
I can reproduce the issue in both ATM10 and a dev environment. I have opened a separate issue for it, see #1504 for more details
