### ISSUE TITLE
Endless loop in Chunkmap#processUnloads() when exiting/unloading level (Connected with BlockCapabilityCache)

### ISSUE THREAD

**Issue by klikli-dev** [neoforged/NeoForge#1403]
**Minecraft Version:** 1.21

**NeoForge Version:** 21.0.146

**Logs:** Clean log, just stuck forever at `[Server thread/INFO] [minecraft/MinecraftServer]: Saving worlds`

To prefix this, this issue may be caused by something I am doing with my mod, but it seems to be connected to BlockCapabilityCache and I am not sure where exactly it is coming from. I apologize if I am doing something wrong but considering the details of when the issue happens and when it does not (see below) I believe it may be an edge case that neo can influence.

**Steps to Reproduce:**
 1. Clone https://github.com/klikli-dev/theurgy/tree/bug/saving
 2. Download the save that reproduces the issue [Test Saving 2.zip](https://github.com/user-attachments/files/16444787/Test.Saving.2.zip)
 3. Unpack the save
 4. Place the contents in /<clonelocation>/runs/client/saves/Test Saving 2
 5. Start the game and load the save.
 6. Esc -> "Save and Quit to Title"
 7. Notice it gets stuck forevermore.

**Description of issue:**

In the given test save, ChunkMap.unloadQueue never gets empty. 
ChunkMap#processUnloads() keeps polling the queue. The loop exit counter "k" already is negative, but doe to "hasMoreTime" being `() -> true` it is ignored. 

At the same time ChunkMap#scheduleUnload() keeps adding new unload tasks to the unloadQueue. 
ChunkHolder#isReadyForSaving() returns false, which causes scheduleUnload to re-schedule itself.
ChunkHolder.saveSync#isDone() returns true, but ChunkHolder#getGenerationRefCount() remains > 0.

I am not sure why this is the case. Some things I found when debugging:

Interactions between two chunks in connection with BlockCapabilityCache are related to the issue (it may be that I am using the cache wrong!).

The following scenario is necessary to cause the issue:

- A BE X of type LogisticsItemInserterBlockEntity is in Chunk A, at the border to Chunk B
- It must be attached to any BE in Chunk B with an Inventory (in the savegame, a Chest)
- A second BE Y of type LogisticsItemExtractorBlockEntity is in Chunk B
- This must be attached to any BE in Chunk B with an Inventory (in the savegame, a Chest)
- The two BEs from my mod must be connecte with a "Mercurial Copper Wire" which makes the two form a network that uses a BlockCapabilityCache to allow the LogisticsItemExtractorBlockEntity to directly place items in the BE the LogisticsItemInserterBlockEntity is attached to.

The second BE from my mod seems to be necessary to cause it, because if only one is present no BlockCapabilityCache is created.

Noteworthy is that the BlockCapabilityCache is created for a BE (Chest) in Chunk B, in which is the BE Y which references it.
If the second BE Y is instead in Chunk A ([Test Saving 2 - Y in A.zip](https://github.com/user-attachments/files/16444960/Test.Saving.2.-.Y.in.A.zip)) or a completely unrelated Chunk C ([Test Saving 2 - Y in C.zip](https://github.com/user-attachments/files/16444967/Test.Saving.2.-.Y.in.C.zip)) the issue does not happen. So it seems only to happen if the Cache is in the same chunk as the BE referencing it.

Further noteworthy is, BlockCapabilityCache.listener is not called (presumably the code execution never gets to that point) when exiting a world when the issue is present (Cache and Y in the same Chunk), but IS called if the issue is not present (Cache and Y in different chunks).

**Comment by klikli-dev** [comment]
Mea culpa - false positive!
I commented out all uses of BlockCapabilityCache and the issue is still present.
After further debugging it seems the underlying problem is that I was accessing level.getBlockEntity without checking level.isLoaded for the position first, causing chunk generation during unload

**Comment by Technici4n** [comment]
Oh well, nothing for me to do then. :)
