### ISSUE TITLE
neoforge broken 1.20.4

### ISSUE THREAD

**Issue by kinggoodguynaso** [neoforged/NeoForge#1420]
**Minecraft Version:** {Minecraft version}

**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**
i can't use the neoforge version its forcing me to remove all of my mods please fix it

**Comment by TelepathicGrunt** [comment]
We cannot help without more info. What does "forcing me" mean? What error message or logs do you have?

**Comment by sciwhiz12** [comment]
Closing on account of lack of response from author with no information given on the original issue report.

@kinggoodguynaso, please head to the [official Discord server](https://discord.neoforged.net/) to receive further support, as we reserve this issue tracker for final bug reports.
