### ISSUE TITLE
Neoforge's conditional overlays break outside of Neoforge

### ISSUE THREAD

**Issue by Apollounknowndev** [neoforged/NeoForge#1423]
The way Neoforge has conditional overlays implemented breaks outside of Neoforge, causing overlays to always be applied. 

```json
{
    "pack": {
        "description": "",
        "pack_format": 48
    },
    "overlays": {
        "entries": [
            {
                "neoforge:conditions": [
                    {
                        "type": "neoforge:mod_loaded",
                        "modid": "mod_id"
                    }
                ],
                "directory": "mod_id_compat",
                "formats": [
                    0,
                    2147483647
                ]
            }
        ]
    }
}
```

Since Neoforge simply adds a `neoforge:conditions` field to vanilla overlays, the condition will only be checked on Neoforge. On other modloaders and in vanilla, the game will apply the overlay no matter what. This can be frustrating for things such as multiloader projects and datapacks packaged as mods.

Moving conditional overlays out of the vanilla `overlays` field or making the `formats` field optional could alleviate the issue.

**Comment by TelepathicGrunt** [comment]
If the solution is breaking, it'll have to wait till next breaking mc version before it can be change since neo is stable now

@lukebemish Was overlays in neo part of the work you did?

**Comment by lukebemish** [comment]
I don't see the issue here? I'd argue that this is the intentional behavior. Yes, this is work I did and this was how I intended it to work

**Comment by lukebemish** [comment]
For an example of this behavior being used to make loader-specific stuff in datapacks, see <https://gist.github.com/lukebemish/91431e6bdabd495e692e7069d822f1ae>

**Comment by lukebemish** [comment]
Furthermore, this is how any _other_ conditional stuff works. If I have a recipe with conditions, it is always on in vanilla and the conditions are ignored. Similarly, if I have an overlay with conditions... It really ought to act the same way

**Comment by Apollounknowndev** [comment]
> For an example of this behavior being used to make loader-specific stuff in datapacks, see https://gist.github.com/lukebemish/91431e6bdabd495e692e7069d822f1ae

You can make overlays work only outside of Neoforge, but there's no way to make them only work on Neoforge. Vanilla/Fabric/Lexforge will ignore the `neoforge:conditions` field and apply the overlay.

**Comment by lukebemish** [comment]
Yes I'm not seeing the issue. That's how _every other_ conditional stuff works. And you can get the same behavior by doing what I do in that gist, and just inverting the conditions.

**Comment by Apollounknowndev** [comment]
> Furthermore, this is how any _other_ conditional stuff works. If I have a recipe with conditions, it is always on in vanilla and the conditions are ignored. Similarly, if I have an overlay with conditions... It really ought to act the same way

The difference with non-overlay load conditions is that they're stored in the root object of the json file. You can simply add both a `neoforge:load_conditions` and `fabric:conditions` field to a json file to have both loaders ignore it.
```json
{
    "fabric:load_conditions": {
        "condition": "fabric:all_mods_loaded",
        "values": [
            "terralith"
        ]
    },
    "neoforge:conditions": [
        {
            "type": "neoforge:mod_loaded",
            "modid": "terralith"
        }
    ],
    ...
}
```

There's no way to do this for overlays.

```json
{
    "pack": {},
    "overlays": {
        "entries": [
            {
                "directory": "terralith_compat",
                "formats": 48,
                "neoforge:conditions": [ <-- Fabric won't read this and will apply the `terralith_compat` overlay anyways
                    {
                        "type": "neoforge:mod_loaded",
                        "modid": "terralith"
                    }
                ]
            }
        ]
    },
    "fabric:overlays": { <-- Neoforge won't read this so it won't apply the `terralith_compat` overlay
        "entries": [
            {
                "directory": "terralith_compat",
                "condition": {
                    "condition": "fabric:all_mods_loaded",
                    "values": [
                        "terralith"
                    ]
                }
            }
        ]
    }
}
```

**Comment by lukebemish** [comment]
To write out my reasoning a bit more here: overlay conditions use the same condition system as all other datapack condition stuff in neoforge; that is, adding condition fields to vanilla objects. In every other datapack condition thingy in neoforge, these fields are ignored in vanilla and the object is thus always loaded; if you have a datapack where you expect to conditionally load stuff on neo that you wouldn't on vanilla, you thus have to work with inverted conditions. I see no reason that overlays should be any different -- having them act differently would just lead to confusion. The issue you note with fabric conditions seems to be a flaw in the design of fabric's system -- they chose to make their overlays work differently from all other conditional stuff. I don't see why neo should follow suite -- especially as neo has plenty of other stuff where conditions are in objects nested further into the JSON (loot table stuff iirc)! Had fabric _also_ implemented it the same way they did everything else, your example would be solvable by inverting the overlay/main pack as well as the conditions. It possibly could still be at present but it's more painful.

**Comment by lukebemish** [comment]
That said, given that fabric has chosen to implement this that way, I suppose it's probably a good idea to at least make this less painful in spite of that design choice. We _should not_ remove conditions from the normal overlay field -- given that folks use that and its useful, since it lets me have the condition ignored on vanilla! -- but it seems like the best solution would be to _also_ load the `neoforge:overlays` field and just merge the two together and apply the same logic to both.

**Comment by lukebemish** [comment]
This could be accomplished by:
- making a new pack metadata section for `neoforge:overlays` that just reuses `OverlayMetadataSection` and its codec, but has a different key
- in the places that the overlays are actually used, patch it to just grab both lists

**Comment by lukebemish** [comment]
PRed something that does that; @Apollounknowndev does that solution work for you?

**Comment by Apollounknowndev** [comment]
That works perfectly, yes.
