### ISSUE TITLE
[Suggestion] Add Missing `c:food` and `c:fruit` tag to the chorus fruit

### ISSUE THREAD

**Issue by ffuentesm** [neoforged/NeoForge#1437]
Chorus fruit is an editable item that restores saturation, so having no tags at all not even those related to food seems like an overlook, especially since poisonous potatoes, rotten flesh, and ominous bottles are tagged as food items and that is the last thing a player would eat.

**Comment by TelepathicGrunt** [comment]
It would be an entry into `c:foods/fruit` tag which then would be inherited into `c:foods`
