### ISSUE TITLE
Rendering a overlay above the hotbar now also renders it above the items in the hotbar

### ISSUE THREAD

**Issue by IThundxr** [neoforged/NeoForge#1478]
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.4

**Description of issue:**
In 1.20.1 rendering a overlay above the hotbar used to render it above the hotbar but behind the items in the hotbar, however this is no longer the case as it will render it above the items aswell, another layer should be added allowing you to render the overlay behind the items.

**Comment by KnightMiner** [comment]
Can you not just render your stuff at a different Z offset to achieve this?

**Comment by IThundxr** [comment]
> Can you not just render your stuff at a different Z offset to achieve this?

No since that ends up messing the rendered texture up, i need to render the texture before the item is rendered

**Comment by sciwhiz12** [comment]
Could you please provide example code and screenshots demonstrating the issue?

**Comment by IThundxr** [comment]
Apparently the texture always just looks a bit broken, not sure how i didn't notice previously, but wrapping my draw call like the following works fine.

```java
		PoseStack ms = graphics.pose();
		ms.pushPose();
		ms.translate(0, 0, -300);
		// draw call here
		ms.popPose();
```
