### ISSUE TITLE
An error with the mod preloading

### ISSUE THREAD

**Issue by LingyiBit0** [neoforged/NeoForge#1484]
Minecraft Version: {1.21}
NeoForge Version: {21.0.167}
Logs: [latest.log](https://github.com/user-attachments/files/16736801/latest.log)

Steps to Reproduce:
 1. rewrite the main program entry of the mod the mod group, the mod id
 2. add mod items, the item model datagen, language datagen and DatagenHandler
 3. run datagen
 4. in my work enviroment, the errors appear

I'm having an issue where I can't tell if it's due to my mistake or Neoforge causing the error to keep throwing the error when running the "**runClient**" and "**runData**" tasks: **"com.electronwill.nightconfig.core.io.ParisingException: Invalid bare key: '${mod_id}" and "is not a valid mod file"**. To fix this, I tried to re-clone the MDK template that could be run, but after modifying the mod_id, mod_group, etc., it still got the same error. Maybe my mistake.
![image](https://github.com/user-attachments/assets/14011e7f-78bd-4122-8732-e86663b0d5e8)

**Comment by sciwhiz12** [comment]
The MDK's configuration is such that the `${mod_id}` is replaced with the actual mod ID from the `gradle.properties` time when the mod is built by Gradle (as part of making the final JAR or launching through Gradle or your IDE). If it fails to replace that part (and causes NightConfig to encounter the invalid key), then something is not quite correct with your setup of how you're launching the game.

Solving that issue, however, is out of scope of this issue tracker, as we accept only feature requests and final bug reports here. Please ask in the `#user-support` channel (under the "For Users" category) in the [NeoForge Discord server](https://discord.neoforged.net/), and the conversation can continue there.
