### ISSUE TITLE
Game crashes immediately upon launching. My graphics drivers are up to date.

### ISSUE THREAD

**Issue by Shidiwadi** [neoforged/NeoForge#1521]
At first the game didnt work and would crash right after this line.

[03:42:06] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6

Then, after some research I changed earlyWindowControl to "false" in the fml.toml

After this, the game gets a little further, processes stuff for about 14 seconds but still crashes. I have attached the log and the text file from the console.

[crashlogtime.txt](https://github.com/user-attachments/files/16915065/crashlogtime.txt)
[hs_err_pid25604.log](https://github.com/user-attachments/files/16915067/hs_err_pid25604.log)

**Comment by HenryLoenwind** [comment]
For better visibility without having to download the log files:

This crash happens in `atio6axx.dll` in the native call `GLFW.nglfwCreateWindow()`.

**Comment by sciwhiz12** [comment]
That really tells more of a graphics driver issue than something specific to NeoForge. 

Does this issue only happen with NeoForge, or does it also happen with vanilla Minecraft? The Java line that runs immediately before the GLFW call is exactly the same line from vanilla, which implies something else is at fault here.

Regardless, we use the issue tracker exclusively for final bug reports and feature requests, and this issue appears to be better suited for the [NeoForge Discord](https://discord.neoforged.net/). Please ask in the `#modder-support-1.21` channel (under the "For Mod Developers" category) in the Discord server, and the conversation can continue there.

**Comment by sciwhiz12** [comment]
I saw a report from a user asking for help in the ParchmentMC Discord server of an identical bug, down to the same DLL file and location. 

After a bit of discussion and searching around online for similar issues, it seems to be a known(-ish) issue with the drivers packed with Adrenalin, the graphics management user interface for AMD Radeon graphics. The user solved the issue, per the suggestio from online searches, by uninstalling Adrenalin and installing fresh graphics drivers.

As a sidenote, the user also noted that they didn't notice that Minecraft wasn't using their NVIDIA discrete graphics card, yet they assumed as such and reinstalled the NVIDIA graphics drivers. It may be worth bearing in mind to configure your OS or drivers to use the discrete graphics card, if any, for Minecraft (the `javaw` executable).
