### ISSUE TITLE
Loader seems to be incompatible with "ForceGL2.0" mod

### ISSUE THREAD

**Issue by IntelMiner** [neoforged/NeoForge#1523]
**Minecraft Version:** 1.20.1

**NeoForge Version:** 1.20.1-47.1.106

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report} see other github issue page

**Steps to Reproduce:**
1. Install ForceGL2.0-1.2x (any Forge release) 

2. Attempt to launch Minecraft

**Description of issue:**

According to the developer of the mod, Forge appears not to be loading the ForceGL2.0 mod before already initiating the OpenGL check.

The mod is designed to "force" OpenGL 2.x compatibility for Minecraft 1.20 clients so that users of older (particularly Intel integrated) graphics can continue to play the game. 

I have been discussing the issue at length with the developer on their issue tracker here https://github.com/coredex-source/ForceGL2.0-1.2x/issues/3 

At this time it seems to be an issue with Forge/Neoforge (both tested and exhibit the same problem) but is likely not an issue with the "Fabric" loader.

**Comment by sciwhiz12** [comment]
I'm not sure what you want us to do here...? Minecraft deliberately has its OpenGL version set to 3.2 Core, which Neo/Forge follows for constructing the early loading window (with additional code to try load higher OpenGL versions if possible, but it will always try 3.2 Core).

Deliberately bypassing Minecraft's own minimum requirements to run on lower-spec'd hardware is an interesting effort, to say the least. While I'm open to hearing what solutions can be made on our part to allow more leeway in mods adjusting the early loading window (see neoforged/FancyModLoader#200), I just don't see how we can accomodate deliberate minimum requirement bypasses in NeoForge.

**Comment by IntelMiner** [comment]
Apologies. My intention was to get as many eyes on this issue as possible, from both sides of the problem (Neoforge and the mod itself) 

As noted in the other bug thread it looks like setting `earlyWindowControl = false` fixes the mod patching out the GL check. However it currently leads to a rendering related crash afterwards.

[RenderCrash.txt](https://github.com/user-attachments/files/16935363/RenderCrash.txt)

One minor correction for the labels is this is against `1.20.1` not 1.21.x

**Comment by Shadows-of-Fire** [comment]
@sciwhiz12 should we close this as wontfix since this is targeting 1.20.1?  We don't really have the ability to make changes to that version.

**Comment by sciwhiz12** [comment]
I agree with that assessment, yeah.
