### ISSUE TITLE
[1.21.1] Missing Crying Obsidian form the `c:obsidians` tag group? 

### ISSUE THREAD

**Issue by ffuentesm** [neoforged/NeoForge#1535]
I just want to confirm if the lack of the `c:obsidians` on the crying obsidian block was on purpose or not. 
Because the tag itself being "obsidians" in plural, means that there is more than one of them in that tag group. 

![image](https://github.com/user-attachments/assets/44f5aa82-3724-4fe5-a44f-76fb3041c193) 
![image](https://github.com/user-attachments/assets/464bb46b-d1fa-4956-a488-fabc13dd64aa)

**Comment by TelepathicGrunt** [comment]
The obsidians tag is old. Really old. It was never updated to have crying obsidian back in forge when it was `forge:obsidian`

So just means we need to update the tag to account for the newer block.

**Comment by tmvkrpxl0** [comment]
Btw what's the use case of the tag? I've never seen mods that add new type of obsidian

**Comment by ffuentesm** [comment]
Irons Spellbook uses it for a crafting item.

But in reality, it would just make both obsidian blocks interchangeable in crafting. 
I wonder if that would make any use in custom portal frame materials, so to allow crying obsidian in the portal activation.

**Comment by HenryLoenwind** [comment]
> I've never seen mods that add new type of obsidian

I have. Coloured Obsidian was a thing.

**Comment by TelepathicGrunt** [comment]
There was that Nether Reactor in Pocket Edition that would spawn some weird glowing red Obsidian thing called Glowing Obsidian. Any mod porting that to Java must add that block lol. So technically Minecraft history had 3 different obsidian types

![image](https://github.com/user-attachments/assets/70966048-a901-46ec-ad91-39f884ba0eb9)
