### ISSUE TITLE
| gfx: *Fabulous!* | Falling blocks are not rendered when they are a translucent block.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#154]
Vanilla:
![image](https://github.com/neoforged/NeoForge/assets/68275908/d811f443-84c7-4661-9d70-944d9ba1b33f)

Forge:
![image](https://github.com/neoforged/NeoForge/assets/68275908/9ac1379f-52dd-4e20-ad49-18fc38b3d61e)

> I found the reason... It has to do with how Fabulous! mode works combined with Forge allowing fancy stuff with render types of baked models: https://github.com/neoforged/NeoForge/blob/1.20.x/patches/minecraft/net/minecraft/client/renderer/entity/FallingBlockRenderer.java.patch#L10. In short, that patch is missing a "render type conversion" so to speak. I'll make a PR when 1.20.2 is ready 

@XFactHD via Discord

**Comment by Lolothepro** [comment]
fixed in 1.20.2

**Comment by XFactHD** [comment]
The fix is unfortunately not quite correct. I'll PR the proper fix I had in mind in a bit
