### ISSUE TITLE
Issue with latest neoforge

### ISSUE THREAD

**Issue by VaporeonScripts** [neoforged/NeoForge#1547]
**Minecraft Version:** {Minecraft version}
1.21.1
**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}
21.1.54
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
![image](https://github.com/user-attachments/assets/228c84a2-455c-4bc4-a720-fe2478cc3608)

**Steps to Reproduce:**
use latest neoforge?
**Description of issue:**
i just updated neoforge and this happened

**Comment by sciwhiz12** [comment]
Cannot reproduce the issue. As the error message implies, you have an issue with your internet connection somehow blocking connections to `piston-meta.mojang.com`, which is not hosted by us.

Additionally, use the issue tracker exclusively for final bug reports and feature requests, and this issue appears to be better suited for the [NeoForge Discord](https://discord.neoforged.net/). Please ask in the `#user-support` channel (under the "For Users" category) in the Discord server, and the conversation can continue there.

**Comment by zWatch** [comment]
I'm having a similar problem because of the network and I get it sometime

```
* What went wrong:
A problem occurred evaluating root project 'Born'.
> Uncaught exception while processing replacement of dependency net.neoforged:neoforge using handler net.neoforged.gradle.common.extensions.dependency.replacement.Handler_Decorated: Failed to download the file from: https://piston-meta.mojang.com/mc/game/version_manifest.json to: C:\Users\xxx\.gradle\caches\minecraft\.\launcher_metadata.json
```

Because of some inconvenient reason, reliable internet is not so easy to come by, which makes it almost impossible for me to work.

If I shut down the network completely, I get the same problem as above.
Please tell me how to build offline
