### ISSUE TITLE
Inconsistent definitions of Boolean return values ​​in different methods in `CommonHooks`.

### ISSUE THREAD

**Issue by qyl27** [neoforged/NeoForge#1550]
Today I am fixing the entity damaging issue in our hybrid server implementation.  
https://github.com/IzzelAliz/Arclight/commit/8041d80970499ea1dbf19380c89003bb9fd6e372
I found that the newer API in `CommonHooks` returns true for cancelled (eg.: `onItemStackedOn`, `onEntityIncomingDamage`, `onLivingDeath`, `onLivingDrops`), but the elder API returns false for cancelled (eg.: `onLivingUseTotem`, `onVanillaGameEvent`, `onAnvilChange`, `onPlayerAttackTarget`, `onTravelToDimension`, `onFarmlandTrample`).  
Should we make it ​​consistent?

**Comment by Shadows-of-Fire** [comment]
The new pattern is to return the `Event` object directly and call `Event#isCanceled()` at the site of the return. Boolean returns are obtuse for the reasons you've outlined.

**Comment by qyl27** [comment]
Is the usage of the new damage pipeline also obsoleted?

**Comment by HenryLoenwind** [comment]
> Is the usage of the new damage pipeline also obsoleted?

What?

You need to understand that there are very few people who do cleanup work on old and working code during the "breaking changes allowed" periods. Most people work on making old code that got broken by the update work again and adding new code for stuff the update added.

You're welcome to jump in when 1.12.2 drops and NeoForge goes into beta again with a PR that changes all events to the new preferred pattern.

**Comment by Technici4n** [comment]
You should always check what `true` and `false` mean in function returns, especially for these methods that exist mainly to make patch code shorter. I don't think that unifying the meaning of `true` and `false` in these methods is worthwhile.

**Comment by qyl27** [comment]
Ok, now I understand, that is intended, and won't be fixed.
