### ISSUE TITLE
[NF 1.21.1] Invisible creative tab(s) until entries are manually added

### ISSUE THREAD

**Issue by JohnGoten** [neoforged/NeoForge#1565]
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.62

**Logs:** KubeJS https://mclo.gs/uY3cjB1 | Modonomicon https://mclo.gs/MSYGGNp

**Steps to Reproduce:**
 1. Install either KubeJS and Rhino dependency and/or Modonomicon.
 2. Open up the creative inventory.
 3. Discover an empty second tab where normally a mod's items would be displayed in its respective category

**Description of issue:**
As a regular player working on the creation of a personal modpack, I discovered that using either KubeJS or Modonomicon will results in entirely invisible tabs in the creative mode inventory as the two only add entries for custom-made content.

This behavior appears to be exclusive to the NeoForge mod loader and cannot be replicated using the Fabric version of Modonomicon - as KubeJS lacks one - in yet another isolated instance for testing purposes.

In order to be certain this issue would not be exclusive to a specific mod, I brought it up on both Latvian's Discord server and Kli Kli's github page https://github.com/klikli-dev/modonomicon/issues/253 as well as receive confirmation from NeoForge's Discord moderator "commoble" that is in fact at being NeoForge at fault.

Screenshots:
personal modpack
![2024-09-28_14 59 20](https://github.com/user-attachments/assets/d3f61d85-2113-4f6f-b1ac-0266ae363e56)
KubeJS only
![2024-09-27_13 21 59](https://github.com/user-attachments/assets/fdb33787-a346-4d31-b7d7-a742e297413d)

**Comment by TelepathicGrunt** [comment]
Will backport to 1.21.1 when 1.21.3 pr is merged
