### ISSUE TITLE
Creative Mode Inventory Screen counts empty tabs when determining page count

### ISSUE THREAD

**Issue by Commoble** [neoforged/NeoForge#1566]
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.62

**Logs:** no logs

**Steps to Reproduce:**
 1. Register a single creative tab with no contents
 2. Open the creative menu
 3. Observe that the creative menu adds a second page with no extra tabs

**Description of issue:**

Neoforge expands the creative inventory screen to support more than one page of tabs, to support indefinitely many mods adding their own creative tabs. This is fine.

However, there is a discrepancy in how tabs are rendered:

1. When determining how many pages should exist, the number of tabs are counted (via CreativeModeTabRegistry.getSortedCreativeModeTabs(), regardless of their contents or visibility
2. When determining whether to render a given tab's... tab? The little clickable nubbins that switch to that tab, only tabs filtered by CreativeModeTab::shouldDisplay are rendered

This means that empty tabs (which can be empty for legitimate reasons, such as all of a mods' content being disabled by configs, or a mod creating a tab for datapacks and addons to add content to without adding anything itself) can inflate the page count and result in empty pages-of-tabs existing

Ordinary creative tab:

![image](https://github.com/user-attachments/assets/21f8fd51-1c03-4221-b476-21aa77cc2a43)

Empty creative tab: observe, page 2 still exists but is empty!

![image](https://github.com/user-attachments/assets/19c1fb28-2e0a-4773-9395-b98e228fac69)

If there are a lot of empty tabs this can get increasingly absurd

![image](https://github.com/user-attachments/assets/75d7c993-5e13-42ef-a58f-4524950cfb5b)

**Comment by XFactHD** [comment]
Fixed in #1711
