### ISSUE TITLE
[RFC] Remove `ITextureAtlasSpriteLoader` in favor of `SpriteSource`s

### ISSUE THREAD

**Issue by XFactHD** [neoforged/NeoForge#157]
The `ITextureAtlasSpriteLoader` API was introduced in 1.16 by https://github.com/MinecraftForge/MinecraftForge/pull/7822 to allow the creation of atlas-stitched textures with special behaviour outside of the capabilities of vanilla's texture animation system, such as proceduraly generated textures like shown in the linked PR.

In 1.19.3, the `SpriteSource` system was introduced as part of the rework of texture loading. With this system, a JSON file is loaded for each registered atlas (in the case of multiple packs containing this JSON, the behaviour is comparable to tags in that the entries are merged) which contains an array of sources, each with a type field and any arbitrary metadata the respective `SpriteSource` needs. A `SpriteSource` can then queue an arbitrary amount of `SpriteSource.SpriteSupplier`s for loading, each associated with a `ResourceLocation` representing the final path of the texture created by the sprite supplier. Two sprite suppliers with the same result path will overwrite each other and the last one to be queued wins. The sprite supplier then produces `SpriteContents` with the actual pixels of the texture. Since all relevant data of the texture (except absolute coordinates and UV coordinates on the atlas) and the creation of the sprite's ticker were moved from `TextureAtlasSprite` to `SpriteContents`, the `SpriteSource` API has basically the exact same capabilities as `ITextureAtlasSpriteLoader`. Additionally, the `SpriteSource` API also has the benefit of being able to create textures from thin air while the `ITextureAtlasSpriteLoader` API requires a PNG to be present, even if none of its contents will be used, since the metadata (`.mcmeta` file) specifying the loader is attached to that PNG.

Unless anyone can think of or has a use case that cannot be replicated with a `SpriteSource`, the `ITextureAtlasSpriteLoader` API should be deprecated for removal since it is entirely redundant now.

**Comment by Minecraftschurli** [comment]
Custom `SpriteSource` PR: #77

**Comment by Technici4n** [comment]
This was actually removed in the 20.2 port. #77 will be prioritized as soon as it's ready.
