### ISSUE TITLE
[Bug?]server can't run success

### ISSUE THREAD

**Issue by Error1015** [neoforged/NeoForge#1591]
**Minecraft Version:** 1.21.1

**NeoForge Version:**21.1.68

**Steps to Reproduce:**
 1. Download the server
 2. run the "run.bat"
 3. ![Image](https://github.com/user-attachments/assets/1553f8cf-02fa-49bb-b1e8-bffa26afff6c)

**Description of issue:**
server can't run success

**Comment by Matyrobbrt** [comment]
That error means that you need Java 21.
