### ISSUE TITLE
add support for older versions of minecraft

### ISSUE THREAD

**Issue by Be1acProgrammer** [neoforged/NeoForge#1608]
I would love to see support for 1.8.9 or 1.12.2 minecraft neoforge versions released! but I'm not sure if it's possible. I also have no coding knowledge or experience. I'm just submitting this to see what the community and developers may say. I run older hardware and would love to see more older versions of minecraft other than just 1.20-21 versions. My current version 1.8.9 forge I have been running for years now, but once I saw neoforge and one of friends with better hardware than me, talked about how great neoforge is. That's how I heard it about this github project. It's just that with the latest versions of Minecraft. I'm unable to run them, **unfortunately**. It would probably be an absolute dream if this did actually get accomplish or did happen. But nothing is impossible.

Best Regards From Zaga.

**Comment by Technici4n** [comment]
Sorry, we're focused on newer versions exclusively.
