### ISSUE TITLE
[1.21.2-1.21.4] If leather armor is not dyed, it is dyed black instead of transparent.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#1612]
**Minecraft Version:** 1.21.2

**NeoForge Version:** 21.2.0-beta

**Logs:** https://mclo.gs/pzgERVM

**Steps to Reproduce:**
 1. Add leather armor to a horse

**Description of issue:**
![Image](https://github.com/user-attachments/assets/2b4cd779-9f8c-4d35-a2eb-a57845645aa6)

The color of the armor is black

**Comment by XFactHD** [comment]
Known issue, I have it fixed locally and will PR it with other equipment rendering fixes
