### ISSUE TITLE
BlockParticleOption#pos is not serialized and end up breaking blocks that relay on ModelData for particles

### ISSUE THREAD

**Issue by ZeroNoRyouki** [neoforged/NeoForge#1629]
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.22 (dev-env) / 21.1.72 (production)

**Steps to Reproduce:**
 1. Put a breakpoint in both the constructors of ClientboundLevelParticlesPacket
 2. Fall on any blocks from some distance
 3. Observe that the pos field of the pos field of the object referenced to by ClientboundLevelParticlesPacket#particle is non-null (and the position of the fallen-on block) at the end of the "logical server side" constructor and null at the end of the constructor used by the netty thread.

![Image](https://github.com/user-attachments/assets/869c5657-d329-4bf1-88ca-37c5e6287970)

**Description of issue:**
The position of the fallen-on block is not know on the client. If the block model depend on ModelData to retrive the correct particle it is unable to do so since the correct ModelData can't be retrived (ModelData.EMPTY is used instead)

Having discussed this with XFactHD on discord, it looks like this problem originated at the introduction of the pos field in BlockParticleOption

Z

**Comment by XFactHD** [comment]
I've made a PR to fix this in 1.21.3, though I'm not sure yet how to deal with it in 1.21.1 since the fix used in the PR is technically a network compatibility break.
