### ISSUE TITLE
(1.21.3) Lava is "intangible"

### ISSUE THREAD

**Issue by Inonedn** [neoforged/NeoForge#1634]
**Minecraft Version:** 1.21.3

**NeoForge Version:** 21.3.3

**Logs:**N/A

**Steps to Reproduce:**
 1. place down Lava
 2. swim in it
 3. see results

**Description of issue:**
When swimming in lava, the player is able to move freely, and isn't slowed down at all, but cannot swim up.

**Comment by Lolothepro** [comment]
I can confirm this bug
