### ISSUE TITLE
Add interface injection Features

### ISSUE THREAD

**Issue by baka4n** [neoforged/NeoForge#1640]
The interface injection function is really good, and it avoids strong turns for programmers, and I hope there is a feature like this in moddev

**Comment by Erdragh** [comment]
Do you mean this?
https://github.com/neoforged/ModDevGradle/#interface-injection

And the work going on on `feature/interface-injection` on NeoGradle?
https://github.com/neoforged/NeoGradle/tree/feature/interface-injection

**Comment by baka4n** [comment]
> Do you mean this? https://github.com/neoforged/ModDevGradle/#interface-injection
> 
> And the work going on on `feature/interface-injection` on NeoGradle? https://github.com/neoforged/NeoGradle/tree/feature/interface-injection

I saw it, so closed the issue
