### ISSUE TITLE
Durability loss on modded armor not working

### ISSUE THREAD

**Issue by Rimplestilt** [neoforged/NeoForge#1642]
**Minecraft Version:** {1.21.1}

**NeoForge Version:** {21.1.73}

**Logs:** {none}

**Steps to Reproduce:**
1. vanilla with only armor mod. Spawn any non vanilla armor,
2. spawn enemy and get hit
3. see no durability loss

**Description of issue:**
Durability/damage will not work on modded armor in 1.21.1 neoforge. I thought it was some mod causing the issue, but it appears to happen even with no extra mods installed, and with any mods i have that add armor.

**Comment by TelepathicGrunt** [comment]
Can you please provide an example mod? Following the code for armor hurting looks fine and will hurt the armor. The armor just needs to be an instance of Armor Item and can be damaged by the damage source
![Image](https://github.com/user-attachments/assets/f93084d1-3d40-4410-a609-2a3f443fc7f0)

**Comment by TelepathicGrunt** [comment]
Tested my own mod's armor on 1.21.1 v21.1.66 Neoforge, I am seeing my armor's durability go down so it seems more unlikely that Neoforge is the problem here
![Image](https://github.com/user-attachments/assets/d8d6c752-101a-453f-b60c-869fc5d5d590)

Edit: tried again with v.21.1.73 neoforge and still see my durability go down

**Comment by desht** [comment]
Can confirm that my modded armor (PneumaticCraft) also takes durability damage, as expected. @Rimplestilt check that your armor items have the `DataComponents.DAMAGE` and `DataComponents.MAX_DAMAGE` components included in the item properties.

**Comment by Rimplestilt** [comment]
thank you. it turns out I just had multiple mods installed with missing durability. I contributed to fix one of them already.
