### ISSUE TITLE
[1.21.3] Crash opening world in single player (Exception in server tick loop)

### ISSUE THREAD

**Issue by ericjs** [neoforged/NeoForge#1646]
**Minecraft Version:** 1.21.3

**NeoForge Version:** 21.3.5-beta
**Logs:** {Link(s) to [crash-2024-10-30_18.29.15-server.txt](https://github.com/user-attachments/files/17579779/crash-2024-10-30_18.29.15-server.txt)
with full latest.log and/or crash report}

**Steps to Reproduce:**
Open world in single player mode

**Description of issue:**
Immediate crash

**Comment by Lolothepro** [comment]
It's caused by World Edit

**Comment by ericjs** [comment]
You beat me to it. I just tested without worldedit, and it doesn't crash...
