### ISSUE TITLE
Biome modifer crash with pale gardens

### ISSUE THREAD

**Issue by MincraftEinstein** [neoforged/NeoForge#1649]
**Minecraft Version:** 1.21.3

**NeoForge Version:** 21.3.6-beta

**Logs:** [crash-2024-10-30_16.35.35-client.txt](https://github.com/user-attachments/files/17578808/crash-2024-10-30_16.35.35-client.txt)

**Steps to Reproduce:**
 1. Create a biome modifier with the biome set to the pale garden
 2. Run the game
 3. Open the Create New World screen

**Description of issue:**
If you add a biome modifier for the pale garden biome the game will crash when opening the create new world screen because the biome is not enabled

**Comment by TelepathicGrunt** [comment]
Can you please show exactly how you setup the Biome Modifier? Have you tried using a biome tag with Pale Garden as an optional entry and then use that tag for the Biome Modifier and see if that doesn't crash?

**Comment by TelepathicGrunt** [comment]
I made a test datapack doing what I described with an optional tag entry. I verified that does add forest rock feature to Pale Gardens just fine when the biome is activated so I know the biome modifier is loaded in and working. Then I tried again in a world with Pale Garden turned off and the datapack does not crash
[test.zip](https://github.com/user-attachments/files/17599950/test.zip)
![Image](https://github.com/user-attachments/assets/bb673207-e7ef-4bbc-83d6-c97fb86f9f14)

I'm leaning towards your Biome Modifier is not setup properly to handle experimental biomes. Please try my suggested setup and if it works, we can close this issue report as working as intended.

**Comment by MincraftEinstein** [comment]
Yes, using an optional tag fixes it. Perhaps this should be mentioned as a workaround for disabled biomes on the documentation
