### ISSUE TITLE
MouseHandler injection issue.

### ISSUE THREAD

**Issue by Sonic3Modder** [neoforged/NeoForge#1655]
MouseHandler injection issue. im trying to use CIT Reswen which is for fabric using a mod called controlify and with the cit resawn mod (im using sinytra connecter) and i have a MouseHandler injection issue. with the controlify mod

**Comment by Matyrobbrt** [comment]
Running Fabric mods is not supported by NeoForge. Report any issues using Connector to them.

**Comment by Sonic3Modder** [comment]
i use sinytra connecter and forgified fabric api

**Comment by TelepathicGrunt** [comment]
That still an issue for Sinytra Connector mod dev to look into. Neoforge modloader is not going to look into this as we aim to support Neoforge mods first and foremost. Not Fabric mods that has been mangled to run on Neoforge through connector

**Comment by Gaming32** [comment]
Please see their [Mod Compatibility Thread](https://github.com/Sinytra/Connector/discussions/12)
