### ISSUE TITLE
Incorrect hand position in death screen

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#167]
NeoForge in death screen:
![2023-10-05_19 25 10](https://github.com/neoforged/NeoForge/assets/68275908/b162058f-2308-4fda-815e-33b1232f4f7d)

Vanilla in death screen:
![2023-10-05_19 26 12](https://github.com/neoforged/NeoForge/assets/68275908/003b2c3f-fed4-446c-9848-2d6aea1e3324)

*Vanilla:*
![2023-10-05_20 22 23](https://github.com/neoforged/NeoForge/assets/68275908/f74cc91e-b93e-425f-8191-a64760518452)

*NeoForge:*
![2023-10-05_20 23 12](https://github.com/neoforged/NeoForge/assets/68275908/0a9e6426-ae59-4ed5-8456-5648a961e50e)

**Comment by LaithAlshakhs** [comment]
Can you provide the version?

**Comment by Lolothepro** [comment]
> Can you provide the version?

NeoForge 47.1.79

**Comment by Lolothepro** [comment]
I can't reproduce the bug, probably fixed?
