### ISSUE TITLE
[1.21.4] Missing json files when generating Item Models

### ISSUE THREAD

**Issue by Stein-N** [neoforged/NeoForge#1742]
**Minecraft Version:** 1.21.4

**NeoForge Version:** 21.4.7-beta

**Logs:** no logs

**Steps to Reproduce:**
 1. Create a class that extends the ItemModelProvider
 2. use ``basicItem()`` to generate an Item Model

**Description of issue:**
The problem here is that it only generates the json file inside the ``assets/mod_id/models/item`` directory but not the ``ItemModelModifier`` json inside the ``assets/mod_id/items`` directory.
Also there is currently no way to alter the Modifier for items

**Comment by XFactHD** [comment]
The custom model providers provided by NeoForge have not been updated to generate the item model definition files because we are working on replacing them with patches to the vanilla providers. This will be resolved once https://github.com/neoforged/NeoForge/pull/1725 is merged.

**Comment by Stein-N** [comment]
When i understand that PR correct the datagen will be comparible in any maner to the fabric datagen, when it comes to usability of all Vanilla Tools and helper methods right?

**Comment by XFactHD** [comment]
Yes, the vanilla helpers will be usable the same way they are in Fabric.
