### ISSUE TITLE
Cannot repair bows

### ISSUE THREAD

**Issue by roddythekidd** [neoforged/NeoForge#1747]
**Minecraft Version:** 1.21.3

**NeoForge Version:** 21.3.57

**Logs:** N/A

**Steps to Reproduce:**
 1. Create 2 bows **or** find 2 bows
 2. Use them to create damage
 3. Attempt to repair in a crafting bench or on-person crafting interface
 4. Repaired bow is not available in crafting output.

Cannot repair bows with NeoForge 21.3.57... worked with swords.

**Comment by Lolothepro** [comment]
I confirm this bug with Minecraft 1.21.4

**Comment by TelepathicGrunt** [comment]
![Image](https://github.com/user-attachments/assets/371c2fb4-02cc-427f-8d3d-6968b7ce4d05)

**Comment by TelepathicGrunt** [comment]
![Image](https://github.com/user-attachments/assets/8e8453b7-725c-421b-a690-1aeefa03e3f9)

**Comment by TelepathicGrunt** [comment]
edit: ignore me

**Comment by TelepathicGrunt** [comment]
Nvm I was running the wrong thing locally
