### ISSUE TITLE
[1.21] Duplicated vegetable tag on crops

### ISSUE THREAD

**Issue by ffuentesm** [neoforged/NeoForge#1758]
**Minecraft Version:** 1.21.x

**NeoForge Version:** 21.1.83

**Description of issue:** Carrots, Potatoes, beets, and Golden Carrots all have duplicated tags c:foods/vegetable and c:foods/vegetables
![Image](https://github.com/user-attachments/assets/3b4e589c-a767-477b-80f8-8555dc32c67c)
![Image](https://github.com/user-attachments/assets/7a28de75-2008-457a-956c-e646d9df8f95)
![Image](https://github.com/user-attachments/assets/9b5ae7a7-069a-43b6-9a52-788d13d40f7f)
![Image](https://github.com/user-attachments/assets/8dda40c5-e49d-4945-b60b-79cc7107b3d4)

**Comment by dhyces** [comment]
Not a NeoForge issue. You have a mod installed that uses the old "c:foods/vegetables" tag id. The correct tag id is "c:foods/vegetable" (not plural).

**Comment by sciwhiz12** [comment]
Closing per above comment. You will need to find which mod uses the `c:foods/vegetables` (with a trailing "s") item tag and report the issue to that mod, so they use the proper tag.

**Comment by ffuentesm** [comment]
I assume then that the "c:foods/vegetables" tag found inside the c:foods/vegetable file does nothing? 
![Image](https://github.com/user-attachments/assets/5f75c367-1387-4a65-b3f5-491d8e068301)

**Comment by dhyces** [comment]
It does. It makes it so anything added to the "c:foods/vegetables" tag still works for anyone that uses the correct tag. so, functionally, everything is fine. your specific complaint of having "duplicates" is unrelated to that and will have to be fixed by the mod author

**Comment by sciwhiz12** [comment]
That is meant as a fallback in case a mod does add to the legacy `c:foods/vegetables` tag, so they work in the interim (as mods slowly move to the proper tags over time). In the future, we will be removing that fallback to force mods to use the proper tags.

The mod development environment does issue warnings in the log when legacy tags are detected to be in use, as configurable through the `logLegacyTagWarnings` config option in the NeoForge common config.

**Comment by ffuentesm** [comment]
Thanks, I've been going through each mod's GitHub to see if I can find which mod is using the old tag. 
Which setting should I use? DEV_SHORT, DEV_VERBOSE, PROD_SHORT, PROD_VERBOSE, not sure what DEV and PROD mean. 

I assume the tag warning appears on the "latest log" file?

**Comment by TelepathicGrunt** [comment]
The logging won’t say which mod is it from. Just that the presence of legacy tag usage exists. I can’t think of anything that can actually point to a source of a tag but I’m sure someone did make a mod to do so as I would assume this is a common issue when making modpacks.

**Comment by ffuentesm** [comment]
Found the problem. Fabric is doing this. 
The Forgified Fabric API is adding both the mistyped and correct tags. 
they are also messing things up by appending the #minecraft:coals to c:coal, which break things on my end by messing with charcoal item.
