### ISSUE TITLE
Vanilla swallows item asset errors in loading, NeoForge re-add?

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#1776]
With the new setup in 1.21.4, Vanilla is now silently swallowing errors for some things related to loading in item assets.

For example, if you don't have an `assets/<modid>/items/<item_id>.json` file at all (which is required for all items), the game will silently load in the missing texture/model, but won't print anything to log.
I believe it's also swallowing some others, such as if the target model the items asset designates doesn't exist (although it does print errors if the target model is _invalid json_

Any chance NeoForge could add these for usability? Especially given this is an entirely new asset location and system, users are going to be incredibly confused.

**Comment by XFactHD** [comment]
The most likely reason why vanilla doesn't log anything anymore is that there is no way to know all missing models during reload anymore and while there is currently still a way to check at least the default model for all items during resource reload (which is what my PR adds), the intention once items are data-driven seems to be to not require doing a resource reload when connecting to a server with custom items, at which point it is impossible to check pre-emptively check for missing models.

**Comment by Tslat** [comment]
Right but even when the item tries to _use_ the asset, it'll fail out with an error model and not tell you why

It's not even just for presumptive assets
