### ISSUE TITLE
SecurityCraft Crash Report

### ISSUE THREAD

**Issue by AnonymousUser98** [neoforged/NeoForge#1788]
Sorry, I don't use Discord.

**Minecraft Version:** 1.21.4

**NeoForge Version:** neoforge-21.4.30-beta

**Logs:** [crash-2024-12-20_11.25.42-client.txt](https://github.com/user-attachments/files/18214869/crash-2024-12-20_11.25.42-client.txt)

**Steps to Reproduce:** Video is too big to upload, so I had to use a file hosting service. It will unfortunately expire in 6 days. You can view it here: https://filebin.net/sj2p76xq28xrswpo
**Update:** Use this link instead. It won't expire. [https://app.weet.co/play/e1ac476f/create-video-tutorials-with-weet](https://app.weet.co/play/e1ac476f/create-video-tutorials-with-weet)

**Description of issue:**
The game crashes when I try to view a security camera with the SecurityCraft mod. I wanted to report this to them directly, but they make you join a Discord server, and I don't use Discord. If possible, please forward this to them (including the attached files).

**Screenshot of crash message:**
![Image](https://github.com/user-attachments/assets/0442f44f-e0c3-4c4a-a85e-ac20b99746e7)

**SecurityCraft Version:** v1.9.12-beta1
**SecurityCraft on CurseForge:** [https://www.curseforge.com/minecraft/mc-mods/security-craft](https://www.curseforge.com/minecraft/mc-mods/security-craft)

**Comment by AnonymousUser98** [comment]
**Update:** You might be able to access the video here: [https://file.io/n2UiXamhAZf6](https://file.io/n2UiXamhAZf6)
It won't expire in 6 days (expires in 1 year), but it might be a one-time download.

**Comment by ApexModder** [comment]
Issue is with the mod rather than neo, `21.4.30-beta` changed some parameter types and mod code looks to have not updated to match these changes, causing the `NoSuchMethodError`.

**Comment by AnonymousUser98** [comment]
> Issue is with the mod rather than neo, `21.4.30-beta` changed some parameter types and mod code looks to have not updated to match these changes, causing the `NoSuchMethodError`.

Please report this to the SecruityCraft team for me. I would do it myself, but I don't use Discord, and there's no other way to report it.

**Comment by Matyrobbrt** [comment]
They have a link to their GitHub repository on their page https://www.curseforge.com/minecraft/mc-mods/security-craft

**Comment by AnonymousUser98** [comment]
> They have a link to their GitHub repository on their page https://www.curseforge.com/minecraft/mc-mods/security-craft

Yes, but their _issues_ page doesn't allow me to create a new issue. If I click "New Issue", it just tells me to go to the Discord.
Please reopen this post.

**Comment by XFactHD** [comment]
You can work around that by editing the URL to https://github.com/Geforce132/SecurityCraft/issues/new

**Comment by AnonymousUser98** [comment]
> You can work around that by editing the URL to https://github.com/Geforce132/SecurityCraft/issues/new

Ok thanks
