### ISSUE TITLE
Installer jar file connection timed out

### ISSUE THREAD

**Issue by ShiroeHikari** [neoforged/NeoForge#1813]
**Minecraft Version:** 1.21.1

**NeoForge Version:** 21.1.92

**Logs:** https://pastebin.com/MT1h8CcB

**Steps to Reproduce:**
1. Download installer through https://neoforged.net/ , make a modded minecraft instance through ATLauncher, Download a modpack through curseforge/atlauncher, or Download Server Files of a modpack
2. Attempt to install the .jar file, modpack, or server files as normal
3. neoforge-21.1.92-installer.jar fails to download libraries folder files giving Connection Timed out Errors

**Description of issue:**
Whenever I attempt to install neoforge on a minecraft instance or a server file, it always fails to download the libraries folder due to connection error. Redownloading the installer.jar file, trying a different version of neoforge, reseting router and rebooting pc. It always end up with the same issue. Downloading from Philippines. Sometimes when opening https://maven.neoforged.net/#/ through a browser, the loads very slowly or doesnt load at all. However when using a VPN (ProtonVPN in my case), the installer starts downloading just fine. 

Im able to download other modloader(Forge and fabric) just fine

**Comment by shartte** [comment]
Can you say what your ISP and ~~country of origin~~ (Philippines :-P) is?

**Comment by shartte** [comment]
Oh, can you please also try this, assuming you are on Windows?

```
ping -4 maven.neoforged.net
ping -6 maven.neoforged.net
```

Wondering whether your ISP has congested carrier grade NAT, maybe?

**Comment by ShiroeHikari** [comment]
> Can you say what your ISP and ~country of origin~ (Philippines :-P) is?

PLDT

**Comment by ShiroeHikari** [comment]
> Oh, can you please also try this, assuming you are on Windows?
> 
> ```
> ping -4 maven.neoforged.net
> ping -6 maven.neoforged.net
> ```
> 
> Wondering whether your ISP has congested carrier grade NAT, maybe?

PowerShell 7.4.6
PS C:\Users\Acer> ping -4 maven.neoforged.net

Pinging 1755624453.rsc.cdn77.org [89.187.162.155] with 32 bytes of data:
Reply from 210.213.131.224: TTL expired in transit.
Reply from 210.213.131.224: TTL expired in transit.
Reply from 210.213.131.224: TTL expired in transit.
Reply from 210.213.131.224: TTL expired in transit.

Ping statistics for 89.187.162.155:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
PS C:\Users\Acer> ping -6 maven.neoforged.net
Ping request could not find host maven.neoforged.net. Please check the name and try again.

this is what returned

**Comment by shartte** [comment]
Oh that is very weird. There's definitely an IPv6 address for maven.neoforged.net

I am not sure what can really be done about it. Somewhere from your ISP to the CDN, the traffic seems to get lost. I had hoped IPV6 might work better, but doesn't look like it works at all for you.

**Comment by ShiroeHikari** [comment]
> Oh that is very weird. There's definitely an IPv6 address for maven.neoforged.net
> 
> I am not sure what can really be done about it. Somewhere from your ISP to the CDN, the traffic seems to get lost. I had hoped IPV6 might work better, but doesn't look like it works at all for you.

I see, if its really just an ISP issue, ill just hope the issue eventually resolves itself on their end and just work through VPN when downloading/updating neoforge packs. Thanks for the short help

**Comment by shartte** [comment]
Yes, sorry. This is very unfortunate. I'd guess it's a peering issue between the CDN and ISP which is sadly outside of our (and your) control :-(

**Comment by fabricplayer** [comment]
Microsoft Windows [Version 10.0.26100.6899]
(c) Microsoft Corporation. All rights reserved.

C:\Users\hp>ping -4 maven.neoforged.net

Pinging 1755624453.rsc.cdn77.org [79.127.235.59] with 32 bytes of data:
Reply from 79.127.235.59: bytes=32 time=123ms TTL=56
Reply from 79.127.235.59: bytes=32 time=108ms TTL=56
Reply from 79.127.235.59: bytes=32 time=108ms TTL=56
Reply from 79.127.235.59: bytes=32 time=108ms TTL=56

Ping statistics for 79.127.235.59:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 108ms, Maximum = 123ms, Average = 111ms

C:\Users\hp>ping -6 maven.neoforged.net


i got this but still cant download

**Comment by fabricplayer** [comment]
oh wait
C:\Users\hp>ping -6 maven.neoforged.net
Ping request could not find host maven.neoforged.net. Please check the name and try again.

**Comment by EdToxer** [comment]
guys, stop leaking your own ip adresses. Also have these error for some reason :(

**Comment by fabricplayer** [comment]
dw  im on CGNAT
it cant tell u anything about me
@EdToxer

**Comment by fabricplayer** [comment]
and ye the fix to this is either using cloudflare or forcing ipv4
