### ISSUE TITLE
[1.20.1+] Add brushing action to ToolActions

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#190]
Brushes are a tool that Minecraft added recently for brushing suspicious blocks but there is no ToolActions for it. Would it make sense for a brushing action be added to that class?

This issue report is just so we don't forget about this in future.

**Comment by ChampionAsh5357** [comment]
I agree. There are already tool actions for left and right click logic for shovels, swords, etc., so adding them to brushes makes sense.

**Comment by TelepathicGrunt** [comment]
Hmm it also looks like trident throwing and dig is not in the ToolActions either. We may want to take another overall look at the class and see if there is anything else that is missing from it.
![image](https://github.com/neoforged/NeoForge/assets/40846040/4081fe95-5d8a-4601-be6e-001b1fdbaaf9)
