### ISSUE TITLE
Couple New Features

### ISSUE THREAD

**Issue by ZestyBlaze** [neoforged/NeoForge#192]
Just a couple features that I come across when I started modding with NeoForge that I feel like could be handy little additions to make certain little bits of modding a lot easier:
- `BlockStateProvider` provides help for making a Sign to give it it's drop particles in standing and wall state with `signBlock`, but Hanging Signs have no such tool yet to datagen the blockstate and model files for particles as far as I know yet
- Boats seem to be a difficult thing to make since they require you to pass an enum value into it `Boat.Type` which is one of the enum's where you cannot register new values. It would be very handy for NeoForge to have an easier way to add onto these to make Boats easier to make

**Comment by TelepathicGrunt** [comment]
Boat enum is extensible now as of: https://github.com/neoforged/NeoForge/pull/1292

Not sure what the state is on BlockStateProvider and hanging signs. Is this still an issue?

**Comment by ZestyBlaze** [comment]
@TelepathicGrunt I believe so, I'll have to double check but there was no method to datagen files for hanging signs so they had textureless break particles. I'll test this again once I'm next deving

**Comment by ZestyBlaze** [comment]
Okay @TelepathicGrunt so turns out this is still an issue. Basically in `BlockStateProvider` NF adds a `signBlock` method to easily create the blockstate files for the standing and wall block and the block model for the sign as a whole which gives it the planks breaking particles for the sign like it should have.
However we cannot use this method for the Hanging Sign and it's `CeilingHangingSignBlock` and `WallHangingSignBlock`  variants, so it would be super handy to have a `hangingSignBlock` method that creates all these same files for the hanging sign block too rather then having to do it manually

**Comment by XFactHD** [comment]
The helpers for hanging sign models were added in #1528.
