### ISSUE TITLE
If a loading error occurs (ie: bad depency), and Oculus/Iris is present, the error will not be displayed, and the game will crash, blaming Oculus.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#195]
Oculus discord:
![image](https://github.com/neoforged/NeoForge/assets/68275908/a906ffe2-0400-4530-be9d-24488b6515f4)

Example with Iris and Forge:
https://mclo.gs/Gho52SG

Loading error:
```[main/ERROR] [ne.mi.fm.lo.LanguageLoadingProvider/LOADING]: Missing language kotlinforforge version [1,) wanted by Resourcify (1.20-1.20.1-forge)-1.2.1.jar```

Current crash message:

```java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance```

**Comment by Technici4n** [comment]
The problem here is ATs being turned off when a dependency error occurs, but not core mods. Either we should find a way to turn AT back on, or we should find a way to turn off core mods. Personally I'd prefer the latter option.

**Comment by XFactHD** [comment]
Fixed by https://github.com/neoforged/FancyModLoader/pull/31.

**Comment by Lolothepro** [comment]
I forgot to close it myself
