### ISSUE TITLE
Reconsider `ForgeI18n`

### ISSUE THREAD

**Issue by Technici4n** [neoforged/NeoForge#196]
I think this is entirely superseded by components and can be deleted but we should make sure first.

**Comment by pupnewfster** [comment]
Isn't part of the class extending the translation component? See `TextComponentMessageFormatHandler` for uses

**Comment by Shadows-of-Fire** [comment]
I don't see anything in this class that could not be replaced by usage of components.

**Comment by Technici4n** [comment]
Part of the problem is that FML (ab)uses this system to translate strings without depending on Minecraft classes.

**Comment by Matyrobbrt** [comment]
FML now has its own translations. We do use them in a few places in Neo code, but those will eventually™ be replaced with components.
