### ISSUE TITLE
State of the project?

### ISSUE THREAD

**Issue by Speiger** [neoforged/NeoForge#197]
ok, I know that a lot of stuff is being developed at the moment by loads of different groups.

But ever since 1.20.1 there was no real support for outside of that specific version.
And even that stopped, see that the last merged thing was my link fix... 55133ebdb40c8e83d8d816b5bdf06c0683c48116

And I get asked: "Are you going to support Neoforge in latest mc version?"
And my answer is like: "I would love to but Neoforge is not on the latest version, and while I also try to contribute to it, it is not for the latest version so i can't support it".

So the question. Is the project dead?
Is there a giant USA holiday i don't know about that lasts like a month or two?

Or what is going on?
There is no issues/discussions of this on github.

So this is also to force a bit of a official statement and not just make people scan the discord server for stuff.

**Comment by Technici4n** [comment]
Hi, you can track the progress at: https://hackmd.io/@neoforged/SyPzw1Ryp. We are quite close but there are still a few essential tasks to finish. Official statement will come with the release.

**Comment by Speiger** [comment]
@Technici4n why isn't that on the main page?
Like this is essential info...

**Comment by AterAnimAvis** [comment]
https://github.com/neoforged/NeoForge/discussions/199
