### ISSUE TITLE
Minecraft crashes when resources are reloaded near an ocean

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#200]
**Minecraft Version:** 1.20.1

**Forge Version:** 47.1.79

log: https://gist.github.com/Lolothepro/492ec28746b1971da65b9c7fba5bc672
crash report: https://gist.github.com/Lolothepro/53ef8b98fdd51161e235075a1858a564
log + crash: https://mclo.gs/fEVrWeH

**Description of issue:**

4471952105434132996
`/execute in minecraft:overworld run tp @s -197.87 63.00 656.28 -149.26 18.15`

https://github.com/neoforged/NeoForge/assets/68275908/5dfb7a33-a79d-4d21-96c2-3a65e9fa5bc9

video log: https://mclo.gs/exRV1je

**Comment by Shadows-of-Fire** [comment]
What in the hell
this game is haunted

I'm guessing this is some kind of race condition between the liquid renderer and the reloading process.

**Comment by embeddedt** [comment]
This is just an educated guess from a quick code audit, but I wonder if it's related to Forge fetching the sprites for fluids from the atlas inside the actual render function, while vanilla appears to fetch them inside a resource reload listener. Presumably fetching the sprites on a worker thread can cause potential race conditions.

**Comment by marchermans** [comment]
Very likely yes, good catch @embeddedt

**Comment by Lolothepro** [comment]
https://gist.github.com/Lolothepro/7d3b73d88753b99d754c2ed6ad921b64
