### ISSUE TITLE
Universal JAR is always packed inside the installer JAR

### ISSUE THREAD

**Issue by sciwhiz12** [neoforged/NeoForge#209]
Currently, the installer JAR is packed with the universal JAR (under the `maven/` folder inside the installer), despite the universal JAR also being published and downloadable from our Maven repository.

During NeoForge development, it's helpful to have the universal JAR packed with the installer as to not require publishing the universal JAR to e.g. the local Maven repository (`~/.m2`). Outside of development though, there's little benefit to packing the universal JAR, since the installer will automatically download it alongside all other libraries.

The packing of the universal JAR is controlled by [the `neogradle.runtime.platform.installer.debug` project property in NeoGradle](https://github.com/neoforged/NeoGradle/blob/2442ea835b255855be7ca3df9318b88ca0590214/platform/src/main/java/net/neoforged/gradle/platform/extensions/DynamicProjectExtension.java#L491-L496), which is [currently set to `true` in NeoForge](https://github.com/neoforged/NeoForge/blob/14ee4f7e9aefaec86d2189fc1c5367b830256f67/gradle.properties#L52C1-L52C43). The property should be set to `true` only in a local/non-CI environment.

**Comment by Matyrobbrt** [comment]
test comment, pls ignore

**Comment by TheSpareTire177** [comment]
im trying to do a custom installer and using the installers wont work for me as they try to install to a launcher profile. is there some place i can just pull the zips or do you have any tips for recompiling for whatever version i need?
