### ISSUE TITLE
Improve the position of the "Mods" menu in Minecraft's title screen

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#249]
Currently, it looks like this:

![image](https://github.com/neoforged/NeoForge/assets/68275908/61bf41f6-5b23-4d68-a102-f933faf02f55)

![image](https://github.com/neoforged/NeoForge/assets/68275908/a64eaf9a-bad7-4a3e-8746-b1b3a6e89fe4)

The "Minecraft Realms" menu is smaller, so the icons get stuck in the letters.

I think it would be possible to find a position in the title screen better adapted to the mod menu.

**Comment by Enderteck** [comment]
On the toppic of the mods in-game page, 

Having a mod such as catalogue from MrCrayfish (https://mrcrayfish.com/mods/catalogue) directly into NeoForge would also be a welcome addition, you could maybe ask to integrate it ?

**Comment by TelepathicGrunt** [comment]
Allow me to show how the Realms button looks for me lol
![image](https://github.com/neoforged/NeoForge/assets/40846040/23b5fc6d-0b3c-4929-8549-6150bb1bee02)

**Comment by Gaming32** [comment]
Realms actually doesn't even work on Neo. For me at least. I wonder why.

**Comment by dayo05** [comment]
In my opinion, regarding to modmenu mod which available for fabric, just stacking vertically might one of the good choice. 

But it might be very-breaking change because the location of the 'mods' button was determined very long time ago as I know

**Comment by KnightMiner** [comment]
Would it be reasonable to hide the realms button entirely of its determined the mods installed make you unable to play realms? Would prevent it from increasing the menu size.

The cases where realms would still work with forge are probably as few as those where you can connect to a vanilla server

**Comment by sciwhiz12** [comment]
> Realms actually doesn't even work on Neo. For me at least. I wonder why.

This is a known issue; see #205.

> Would it be reasonable to hide the realms button entirely [i]f its determined the mods installed make you unable to play realms?

That would run into the problem of figuring out if the mods one has installed are compatible with connecting to a vanilla server, without actually connecting to (or pinging with a status packet) a vanilla server.

**Comment by dayo05** [comment]
> Would it be reasonable to hide the realms button entirely of its determined the mods installed make you unable to play realms? Would prevent it from increasing the menu size.
> 
> The cases where realms would still work with forge are probably as few as those where you can connect to a vanilla server

I don't think this is the real solution.

A lots of players uses forge only for client mods(like performance improvement or shaders). In this case, user sometimes wants to play relem server.

This can sometimes resonable if use hide relem button on mods which server-sided mod required. But, we cannot determine which mods always must be exists on server and client. The [Simple Voice Chat](https://www.curseforge.com/minecraft/mc-mods/simple-voice-chat) available not only mod but also plugin. As I know, this marked as both can be used even some players prefer to use this only on client.
Also, making relem button to be optional, this not make sence. I think there are better solution for it but idk now...

**Comment by Jab125** [comment]
Older versions of forge replaced "Minecraft Realms" with "Realms" (by removing "Minecraft")

**Comment by st4r1ight** [comment]
Even with that change, the button isn't wide enough to accommodate all the icons.

![image](https://private-user-images.githubusercontent.com/115791356/294204921-b70f3355-d1bb-4c3f-ac8b-6164f93377e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNzgyNTQsIm5iZiI6MTcwNDM3Nzk1NCwicGF0aCI6Ii8xMTU3OTEzNTYvMjk0MjA0OTIxLWI3MGYzMzU1LWQxYmItNGMzZi1hYzhiLTYxNjRmOTMzNzdlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNFQxNDE5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04N2M1ZDdiOWQzMWM4ZjRkZWU0M2IyNTVlMzc4MDI3MTNmZGE3MjkzMGZjZGJmYzBkOGRjYTU3Y2EyZGFlOTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8jL-xZJAHqW1LrzPDBuTF0fGDHFk2xdajSrIdKzxkn0)
