### ISSUE TITLE
[1.20.2] ModelData is not passed to getQuads in all cases

### ISSUE THREAD

**Issue by RedstoneDubstep** [neoforged/NeoForge#260]
Within `ModelBlockRenderer#tesselateWithoutAO`, there are two calls to `BakedModel#getQuads` that try to acquire the list of renderable `BakedQuad`s of this model for the given (or null) direction. While the first of these instances passes the relevant `ModelData` into `getQuads` correctly, the second one does not and instead calls the model-data-insensitive version of `getQuads` (which ends up passing `ModelData.EMPTY` to the `getQuads` method that expects a complete model data), even though there would be a model data to use available (which *is* being used in the first `getQuads` call). This causes issues when rendering the model, most prominently z-fighting between the rendered ModelData-aware and -unaware quads, the former returned by the first `getQuads` call and the latter by the second. 
I strongly assume this to be an oversight introduced when porting to 1.20.2, as `ModelBlockRenderer#tesselateWithAO` has a very similar method structure, with two `BakedModel#getQuads` calls that both include the `modelData` parameter. If this indeed turns out to be unintended behaviour, I'd be happy to open a PR that fixes the issue by restoring consistency between the two `tesselate` methods.

**Comment by Technici4n** [comment]
Yeah that sounds like a bug, if you want to PR a fix. :)
