### ISSUE TITLE
[RFC] Use bundle packet instead of fully custom packet for additional entity spawn data

### ISSUE THREAD

**Issue by XFactHD** [neoforged/NeoForge#275]
To use `IEntityAdditionalSpawnData` for custom entities, it is currently required to return a custom spawn packet added by Neo instead of the vanilla `ClientboundAddEntityPacket` from `Entity#getAddEntityPacket()`. This is not only error-prone on the modder side, it also incurs significant maintenance overhead as the custom packet is effectively a carbon copy of the vanilla packet.

In 1.19.4, vanilla introduced packet bundles to allow handling a set of packets (in this case the entity spawn packet and additional packets like synced entity data, attributes, equipment and passenger, vehicle and leash info) in a single tick instead of spread out due to potential networking delays, presumably to prevent desyncs when subsequent packets arrive late. It is worth noting that each packet is still sent separately and therefor can make use of the full packet size limit. A pipeline component is used to delimit this packet queue on the sending side and re-bundle it on the receiving side. Entity spawning is currently the only vanilla system making use of packet bundling.
Since this system is very generic, there is nothing preventing us from moving the custom spawn data to a simple custom packet that only handles said data and adding that to the bundle in `ServerEntity#sendPairingData()` and using the vanilla packet as the actual spawn packet. This would also make the use of `IEntityAdditionalSpawnData` less confusing as it would only require opting into it in one place (implementing `IEntityAdditionalSpawnData` on the target entity) instead of two places (the interface implementation plus the custom packet returned from `Entity#getAddEntityPacket()`).

**Comment by marchermans** [comment]
The one thing that this proposed bundle system would not cover is the current custom client spawn code in the entity type builder, I am also not sure if that is a great api in the first place.

However there might be some usages.

**Comment by XFactHD** [comment]
Implemented by #277
