### ISSUE TITLE
Ingredient.CODEC_NONEMPTY is not resolving tag entries from context in Neoforge

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#292]
(copied from discord)

I am making a custom ShapelessRecipe with a single extra field. I copied the entire vanilla ShapelessRecipe including its codec with Ingredient.CODEC_NONEMPTY.listOf(). But it turns all tag entries into barrier input while the same recipe works perfectly fine on Fabric and was working in 1.20.1 Forge. If I do a /reload in game, the recipe works again. You can likely reproduce using vanilla's shapeless recipe itself with tag entries.

Recipe: https://github.com/TelepathicGrunt/Bumblezone/blob/1.20.x-Arch/common/src/main/resources/data/the_bumblezone/recipes/bumble_bee_chestplate/trans_1.json

Recipe class: https://github.com/TelepathicGrunt/Bumblezone/blob/24ab4e7f532604bf9b159a29559dd4357b101fde/common/src/main/java/com/telepathicgrunt/the_bumblezone/items/recipes/NbtKeepingShapelessRecipe.java#L111

Tags: https://github.com/TelepathicGrunt/Bumblezone/blob/1.20.x-Arch/common/src/main/resources/data/the_bumblezone/tags/items/dyes/cyan.json

What I was seeing when breakpointing in the codec to see why recipe would not match:
![image](https://github.com/neoforged/NeoForge/assets/40846040/41c2c824-1a56-47db-a0c1-5e6606bd578b)

Original discord convo:
https://discord.com/channels/313125603924639766/852298000042164244/1177746870748069948

**Comment by Technici4n** [comment]
The fix was to not call `isEmpty` too early.
