### ISSUE TITLE
Strange sounds

### ISSUE THREAD

**Issue by Kaligraphy22** [neoforged/NeoForge#295]
Using Prism Launcher 8.0

Minecraft Version: 1.20.1

NeoForge Version: 47.1.79

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
I'm not sure how to reproduce this. I downloaded about 100 mods through Prism Launcher. I started my game per usual.

**Description of issue:**
It started with game sounds randomly going out and having to restart the instance to get them back. Now, I have this strange sound you can hear in the video that I am going to try to attach to my next post. I crashed before I could record this video but I got back in and the sound was still here. Here's the crash log.
[crash-2023-11-26_12.39.43-client.txt](https://github.com/neoforged/NeoForge/files/13467779/crash-2023-11-26_12.39.43-client.txt)

**Comment by Kaligraphy22** [comment]
https://github.com/neoforged/NeoForge/assets/72703227/69f77d26-5379-425b-ada8-1407338f6020

**Comment by Technici4n** [comment]
That is probably a mod issue, not an issue in NeoForge itself.

**Comment by Kaligraphy22** [comment]
Oh, I wan't sure what is was. Sorry.
