### ISSUE TITLE
When NeoForge is installed, the burning grass behaves differently from Minecraft Vanilla.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#302]
When NeoForge is installed, the burning grass behaves differently from Minecraft Vanilla.

Neo:

https://github.com/neoforged/NeoForge/assets/68275908/cae687fb-fc0c-4a4c-9680-e7d1e03ed8aa

Vanilla:

https://github.com/neoforged/NeoForge/assets/68275908/6acb9586-ca9b-48c8-8096-b7f56e1a3bfa

**Comment by TelepathicGrunt** [comment]
This patch in FireBlock is the cause it seems.
https://github.com/neoforged/NeoForge/blob/77b3fd16f7e17d2f0e87aa17807049ec86a43dd4/patches/net/minecraft/world/level/block/FireBlock.java.patch#L8

Checking now
