### ISSUE TITLE
EventBusSubscribers with the same name are treated as one

### ISSUE THREAD

**Issue by RadonCoding** [neoforged/NeoForge#305]
**Minecraft Version:** 1.20.1

**NeoForge Version:** 47.1.77

**Steps to Reproduce:**
 1. Create two static inner event bus subscribers with the same name
 2. Subscribe to the same event in both of the event bus subscribers
 3. Only one of the event handlers receives the event

**Description of issue:**
It seems classes with the EventBusSubscriber annotation that have the same name causes only one of them to be subscribed.

**Reproducing the issue:**
```
public class EventHandler1 {
    @Mod.EventBusSubscriber(modid = Example.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
    public static class ForgeEvents {
        @SubscribeEvent
        public static void onLivingTick(LivingEvent.LivingTickEvent event) {
            System.out.println("Ticking from EventHandler1!");
        }
    }
}
```

```
public class EventHandler2 {
    @Mod.EventBusSubscriber(modid = Example.MODID, bus = Mod.EventBusSubscriber.Bus.FORGE)
    public static class ForgeEvents {
        @SubscribeEvent
        public static void onLivingTick(LivingEvent.LivingTickEvent event) {
            System.out.println("Ticking from EventHandler2!");
        }
    }
}
```

**Comment by Technici4n** [comment]
This was verified to be fixed in 20.2 with the event bus changes.
