### ISSUE TITLE
Issue with earlyWindow and rubidium extra.

### ISSUE THREAD

**Issue by ekkomaru** [neoforged/NeoForge#307]
**Minecraft Version:** 1.20.1

**NeoForge Version:** 47.1.79

**Logs:** [GitHub Gist](https://gist.github.com/ekkomaru/a91452fc78f07cf372f5df7ff6b46a9b)

**Steps to Reproduce:**
 1. Install the latest version of NeoForge, embeddium and rubudium-extra.
 2. Enable reduced resolution on macOS.
 3. Restart Minecraft.

**Description of issue:**
Launching Minecraft with reduced resolution using rubidium-extra causes it to reduce the window to only a quarter of the window screen, and any change to the window resets it back to the original resolution.
Detailed description of the issue is here: https://github.com/dima-dencep/rubidium-extra/issues/64#issuecomment-1829011231
The author of rubidium-extra said it's a problem with Forge's `earlyWindow`, so I'm trying to report it here to see if it's something that can be looked at.

The issue at play:
<img width="966" alt="image" src="https://github.com/neoforged/NeoForge/assets/20847464/46e8ae0b-0676-47c8-957b-cba8c1e5ac17">

I would be pleased to provide anything more that might be necessary for this.

**Comment by Technici4n** [comment]
@dima-dencep can you explain the issue? Just pointing the blame at the early loading screen is not very helpful, and it could also be an issue on your side.

**Comment by marchermans** [comment]
The problem here lies with how the early loading screen is constructed and its setup, the GL Context and other properties of the view screen are setup by the EarlyLoading Screen before any mod is even touched, let alone the hacky mixins from Rubidium to control this.

As such rubidium expects certain properties with respect to the view to hold, which simply don't cause their mixin code is not ran, and there is no opportunity for them to mixin into the ELS.

In practice this means that this problem is not fixable.

**Comment by Technici4n** [comment]
Is this the relevant mixin? https://github.com/dima-dencep/rubidium-extra/blob/1.20.x/stable/src/main/java/me/flashyreese/mods/sodiumextra/mixin/reduce_resolution_on_mac/MixinWindow.java

If you explain what it does and why it is useful we might consider adding an FML config option.

**Comment by dima-dencep** [comment]
Reduces the resolution on a Mac with retina (denser pixels), but I don't have a mac, so...

**Comment by ekkomaru** [comment]
I can chime in a little with the general why something like that is important, but not quite why the code in question is/should be how it is.

macOS renders stuff on the retina displays scaled by the factor of two, for example, on a 4k display, you get the usable space of 1080p because all the elements of macOS are scaled double to accommodate.

Up to a certain version of Minecraft (I think 1.13), it has worked like that as well, rendering the game at half the resolution and letting it scale up. This was reportedly a bug, but as a downside, now the rendering goes to the full native resolution, which in itself wouldn't be quite a problem if it wouldn't be murdering performance. In vanilla Minecraft on modern macs it's not really that noticeable, but once you get into modded, it can affect performance quite a bit. This is mostly prevalent with shaders enabled, but can be a real hit to FPS even without them on larger render distances. And at least in my opinion, the reduced resolution leads to almost no discernable loss in quality, at least on the 16" internal display.

**Comment by ekkomaru** [comment]
@Technici4n Hello, just wanted to ask how you see this issue? Do you think the addition would be possible, or is this something out of the scope of the project? Either is fine, but if it wasn't feasible, I wouldn't mind closing the issue.

**Comment by Technici4n** [comment]
I'm happy to accept a PR that adds the config option to FML. I can't write it though since I don't have a Mac.

**Comment by TelepathicGrunt** [comment]
Closing as this went for a while without any progress. The neo team does not have enough people with both this specific FML experience and Macs to be able to make a PR for a config to change the retina flag. However, we will accept any outside contributor to making a PR to neo for 1.21 to add said config option.
