### ISSUE TITLE
About loading mod files from other folders

### ISSUE THREAD

**Issue by Xing-C** [neoforged/NeoForge#320]
Yes, that's just my idea

Description;

I hope the module loader can load the modules contained in the sub folders under the mods folder Just like a feature in the old version of Forge 1.12.2, it searches and loads .\mods and .\mods\1.12.2

I tried Fork FancyModLoader and tested the modifications, but it was not successful. (.\1.20. x\libraries\net\eoforged \fanymodloader \loader\47.1.47\loader-47.1.47. jar) When this file is changed, any tampering by the loader will cause it to fail to start

I hope to get some help.

**Comment by Technici4n** [comment]
To install a modified version of FML, the best way is to use it in a custom-built Forge.

This specific feature (loading mods under a subfolder) is not a good idea. You should use different MC instances instead.
