### ISSUE TITLE
partial nbt ingredient fails to match on numbers

### ISSUE THREAD

**Issue by ThatGravyBoat** [neoforged/NeoForge#328]
**Minecraft Version:** 1.20.3

**NeoForge Version:** 20.3.3

**Steps to Reproduce:**
 1. Create a recipe using a partial nbt ingredient that checks if a repair able item has a repair cost of 1
 2. repair that item once
 3. try to use the item to craft the recipe you created
 4. notice that it does not work

**Description of issue:**
The partial nbt ingredient uses an `NbtPredicate` that uses `NbtUtils.compareNbt`, which requires both tags to be the same class this is an issue due to the tag for the stacks being created using `CompoundTag.CODEC` and how it works. As `CompoundTag.CODEC` uses `Dynamic.convert` and since its going from JSON to NBT it uses `JsonOps.convertTo`. `JsonOps` for numbers will convert to the type that is the smallest in size that can fit the number, (ie. 1 will always be converted to 1 byte). That means the item in-game will have NBT of `RepairCost` of 1 int while the `NbtPredicate` with have repair cost of 1 byte and they will never match.

**Example:**
Heres an example json recipe that will fail:
```json
{
  "type": "minecraft:crafting_shapeless",
  "ingredients": [
    {
      "type": "neoforge:partial_nbt",
      "item": "minecraft:diamond_axe",
      "tag": {
        "RepairCost": 1
      }
    }
  ],
  "result": {
    "item": "minecraft:bedrock"
  }
}
```

> Side note: But the `NbtPredicate` usage in `PartialNBTIngredient` is not really needed and can just be replaced with `NbtUtils.compareNbt` instead of creating a new instance of the predicate each time.

**Comment by Technici4n** [comment]
I would recommend using the string format for `"tag"` to avoid this exact issue. Was this working in 1.20.2? If yes it's probably worth researching what changed since then.

**Comment by ThatGravyBoat** [comment]
This would not work in 1.20.2 too, `CompoundTag.CODEC` has always passed through and converted. When the ingredient was switched to a codec in 1.20.2 the lose of tag as a string happened which means that there is no workaround for this, there is `TagParser.AS_CODEC` which is string -> CompoundTag so to have it back to the old options an either codec of those 2 could be done.

**Comment by Technici4n** [comment]
In fact, we already have such a Codec inside our `ItemStack.ITEM_WITH_COUNT_CODEC` patch. I would suggest moving the `ExtraCodecs.withAlternative(net.minecraft.nbt.TagParser.AS_CODEC, net.minecraft.nbt.CompoundTag.CODEC)` to a field in `NeoForgeExtraCodecs`, and then also use it for the partial (and strict!) NBT ingredients.
