### ISSUE TITLE
[1.20.3] Could not find run type client

### ISSUE THREAD

**Issue by Spinoscythe** [neoforged/NeoForge#337]
**Minecraft Version:** 1.20.3

**NeoForge Version:** 20.3.7-beta/20.3.8-beta

**Logs:** [Github Gist](https://gist.github.com/Nekretaur/fd7497cce2624594cb5ec61547b32efa)

**Steps to Reproduce:**

**Description of issue: Regardless the task I try to run - this was when I was porting to 1.20.3 - this error just keeps popping up!**

**Comment by Andromander** [comment]
You've input `20.3-7-beta` instead of `20.3.7-beta`.

**Comment by Technici4n** [comment]
Indeed. it is `3.7` not `3-7`.
