### ISSUE TITLE
Apply wildcards to all instances of BlockBehaviour#codec

### ISSUE THREAD

**Issue by Andromander** [neoforged/NeoForge#368]
It's my understanding that as of 1.20.4, the use of `BlockBehaviour#codec` is effectively unused and that it's not necessary to create a codec for all blocks just yet, but in case this will continue after these are applied, it might be ideal that most if not all overrides of `BlockBehaviour#codec` should have a wildcard for extensibility.

For example: the FenceBlock's override for `BlockBehaviour#codec` returns a `MapCodec<FenceBlock>` meaning that if a class extends FenceBlock, it must match the parent class without any new parameters. Say for example, a child of FenceBlock that contains a parameter for a DamageType if an entity were to stand on top of it. Due to how FenceBlock has overridden `BlockBehaviour#codec`, it would be impossible to create a new Codec for this particular child class.

**Comment by Technici4n** [comment]
You can use an unchecked cast to get away with it. Something like `return (MapCodec) YOUR_CODEC`. So I don't think this will really be an issue in practice, and I'd be concerned by the required patch size.
