### ISSUE TITLE
[1.20.2+] The Registry Overhaul

### ISSUE THREAD

**Issue by Shadows-of-Fire** [neoforged/NeoForge#37]
The Registry Overhaul is the transition from the Forge Registry system to the vanilla Registry system. This issue serves as the general record of all changes under this umbrella, as well as their scope and future steps that have yet to be executed. It is also a work-in-progress. Discussion is also ongoing in the [Registries Overhaul thread](https://discord.com/channels/313125603924639766/1131130393144336385).

Importantly, this will be a gradual change. This system is huge and has a lot of pieces to it, and we hope to make the transition as seamless as possible.

# Phase 1
The first step in this process is to phase out usages of the Forge Registry system.  The goals of this phase are to reduce mod usage of the forge registry system and identify feature gaps between the two systems.

### Identified Feature Gaps
* Registry Sync
* ID Map Serialization to Disk
* Aliasing
* ~~Registry Replacement~~
  * This feature is being removed.

PR's under this umbrella include the following:
1. https://github.com/neoforged/NeoForge/pull/35

# Phase 2
The second step is to add feature parity to the vanilla Registry system, based on feature gaps identified in phase 1.

PR's under this umbrella include the following:

# Phase 3
The final step is to remove the Forge Registry system in totality, after the vanilla Registry system has achieved parity.

PR's under this umbrella include the following:

**Comment by Technici4n** [comment]
The changes are coming along nicely in #257.

For an overview of the changes, refer to the WIP blog post: https://github.com/neoforged/websites/pull/14.
