### ISSUE TITLE
Pack overlays in mod files are not supported

### ISSUE THREAD

**Issue by Apollounknowndev** [neoforged/NeoForge#381]
**Minecraft Version:** 1.20.2+

**NeoForge Version:** any

**Description of issue:** Pack overlays in mod pack.mcmeta files do not function. This is a major issue for datapacks-packaged-as-mods which rely on overlays to function correctly on new versions, such as Terralith.

**Steps to Reproduce**
- Install [Terralith v2.4.11](https://modrinth.com/mod/terralith/version/2.4.11). This version of Terralith relies on pack overlays to support the `minecraft:grass` -> `minecraft:short_grass` change.
- Attempt to create a new world. The game will instantly crash due to errors with registries failing the load, which is due to the game still trying to parse the files with `minecraft:grass` in them.

**Comment by KnightMiner** [comment]
I assume #367 already addresses this issue. Due to the nature of the fix will require being part of a breaking changes window.

**Comment by lukebemish** [comment]
If #367 doesn't already address this issue I will be making sure it does before it's merged (which should be pretty easy if it doesn't already support it out of the box - it's supposed to but it's also untested so I might need to fix s thing or two) - avoiding this sort of issue is a major goal of that PR

**Comment by lukebemish** [comment]
Just tested locally and #367 does seem to fix this - at least, making the terralith jar use `lowcodefml` so that it would load, then loading it locally with that PR, loaded and generated a world with the overlays applied correctly.

**Comment by XFactHD** [comment]
Fixed by #367
