### ISSUE TITLE
Ever time I try to download Neoforge I get this popup saying how my libraries failed to download. What do I do?

### ISSUE THREAD

**Issue by Wersab12** [neoforged/NeoForge#390]
**Minecraft Version:** {Minecraft version}

**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
 1. Do this
 2. Then do that
 3. ...

**Description of issue:**
![Captudrre](https://github.com/neoforged/NeoForge/assets/125147341/12dcc6e9-756c-4e25-b0fa-b2f7ec98c876)

**Comment by Technici4n** [comment]
Likely a problem with your internet connection. We can't help you without further information anyway. Best to ask on discord.

**Comment by meyde** [comment]
sorry for the reopening but this is an issue i had (no internet connection) 
i fixed it by just.. updating java. Simple, but some people might not know that
