### ISSUE TITLE
[1.20.4] Unable to run mod in dev if a dependency has outdated mods.toml file

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#407]
I am developing and porting my mod to latest NeoForge and I fixed up my mods.toml file. However, I am unable to run my mod in dev because a dependency of my mod still uses an outdated mods.toml file.
![image](https://github.com/neoforged/NeoForge/assets/40846040/78f59046-5bf8-4d51-b945-f8084c3de072)

I think it would be ideal if this blocking mods.toml check only applies to the base mod in dev. Not to the dependencies. As of right now, I can't test my mod at all in dev and forced to wait for the dependency to change their mods.toml file.

**Comment by TelepathicGrunt** [comment]
From discord:
![image](https://github.com/neoforged/NeoForge/assets/40846040/824ea7e7-df3f-4c4b-b387-5dac184c4209)

**Comment by Technici4n** [comment]
I knew this might be an issue heh. We actually have a concept of "the mod being developed" (MOD_CLASSES), but it's a bit of a pain to access it from the TOML parser... Maybe we could simply add an env variable to disable the check.
