### ISSUE TITLE
Neogradle doesn't automatically create the "run" folder in eclipse and when you try to run it, it simply can't run.

### ISSUE THREAD

**Issue by Speiger** [neoforged/NeoForge#409]
o/
Neogradle is a huge upgrade already.
There is just some things that it should be doing that forge did.
Especially if you are sharing projects with others where you don't share your "run" folder, for obvious reasons.
Having to remember/explain "just create the run folder" is a bit annoying.

It would be awesome if the run folder would be created in eclipse too. (I am assuming that in intellij it will be created)

**Comment by marchermans** [comment]
There is a ticket for this on the neogradle repo. CLosing

**Comment by TelepathicGrunt** [comment]
this the issue report?
https://github.com/neoforged/NeoGradle/issues/78

**Comment by Speiger** [comment]
@TelepathicGrunt yes. It should automatically just create the run folder.
