### ISSUE TITLE
FluidSpriteCache triggers an unexpected crash

### ISSUE THREAD

**Issue by TT432** [neoforged/NeoForge#422]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.47-beta

**Logs:** [Crash Report](https:paste.feed-the-beast.com/view/00bbc6fd)

**Steps to Reproduce:**
I registered a new FluidType, Fluid, FlowingBlock, and a bucket that crashed when I tried to drop Fluid with the bucket.

**Description of issue:**
I'm guessing the reason is that I didn't initialize the texture that Fluid needs to use, `FluidSpriteCache#getFluidSprites`' `textures.getOrDefault` error (key is null), which I don't think is expected (the expectation is: use `missingSprite` instead of crashing)

**Comment by Lolothepro** [comment]
broken hyperlink: Logs : https://paste.feed-the-beast.com/view/00bbc6fd

**Comment by Technici4n** [comment]
> I'm guessing the reason is that I didn't initialize the texture that Fluid needs to use, `FluidSpriteCache#getFluidSprites`' `textures.getOrDefault` error (key is null), which I don't think is expected (the expectation is: use `missingSprite` instead of crashing)

Indeed. :P

**Comment by Technici4n** [comment]
You are not supposed to return `null`:
![image](https://github.com/neoforged/NeoForge/assets/13494793/4bde4dc6-487e-4061-bd76-cd9217c2cbeb)
