### ISSUE TITLE
Split living entity tick (and level tick) into a separate start and end tick event

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#424]
The phases for the tick events are opaque and easy for people to miss. Forcing people to explicitly subscribe to start or end will help eliminate mods accidentally running their logic twice (at start and end) per entity tick. Ideally, a breaking change so that hopefully afterwards, there would be less performance hurting tick mistakes in mods.

mods would keep doing the client/server checks on their own as that’s a common thing in any code or event to do

**Comment by Technici4n** [comment]
The living entity tick event is not split at the moment. For the other events, see #542.

**Comment by Shadows-of-Fire** [comment]
#542 was updated to include (and split) `LivingTickEvent`

**Comment by tmvkrpxl0** [comment]
since it's merged, can this issue be closed?

**Comment by sciwhiz12** [comment]
Resolved by #542 -- tick events have a `Pre` and `Post` subclass each, per PR description.
