### ISSUE TITLE
isConnected does not convey effectively what it does

### ISSUE THREAD

**Issue by ThatGravyBoat** [neoforged/NeoForge#459]
The `isConnected` method introduced on the player connection with the networking PR does not convey what it does effectively.

The method currently checks if the connection that is already connected has told the server that it can receive a specific channel/packet `isConnected` does not convey this which makes it hard to search for in the code base I personally spent a bit trying to find such a method and couldn't and had to ask for if there was such a method.

A more effective name could be something along the lines of `canSend`, `canReceive`, `hasChannel`, `hasPacket` all these names have the same thing in common they are more directly related to it being a packet or channel of a packet that is trying to be checked which is what people will be searching for when they want to find it. Could also do something closer to what it used to be with `SimpleChannel`s it could be `isPresent`

**Comment by Shadows-of-Fire** [comment]
The current name is a result of being in-between two network architectures after failing to negotiate a multi-loader standard.  The name represents the behavior of the new structure, but the actual implementation represents the old structure.

Given the current ("old") network structure, where the `connection` is a list of pre-negotiated network channels without the ability to connect or disconnect at runtime, the method name `hasChannel` makes the most sense.

The current method name was designed for the "new" network structure where there are `Channel` objects that may be in a connected or disconnected state, which is where an `isConnected` method would live.

### Examples
Current Name: `player.connection.isConnected(RegistryDataMapSyncPayload.ID)` (awkward method naming)


Proposed: `player.connection.hasChannel(RegistryDataMapSyncPayload.ID)` (implicit contract that all channels on the connection are negotiated and available)


Future Target: `player.connection.getChannel(RegistryDataMapSyncPayload.ID).isConnected()` (No implicit contract, as channels may exist and be disconnected)

**Comment by ThatGravyBoat** [comment]
I think this can be closed now, but I don't know if it's being kept open for another reason as 1.20.5 this has changed to a more fitting name.
