### ISSUE TITLE
getCapability fails because relative coordinates are used in the tests

### ISSUE THREAD

**Issue by Edivad99** [neoforged/NeoForge#463]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.70-beta

**Description of issue:**
If I use the Minecraft in-game testing framework, the method 
```java
default <T, C> @Nullable T getCapability(BlockCapability<T, C> cap, BlockPos pos, C context
```
does not take into account the relative coordinates that are used.
So for now the only way to solve this problem is to retrieve the BE and then pass it to the method.

**Comment by Matyrobbrt** [comment]
Relative coordinates are only expected by the helpers in `GameTestHelper`. You can use `absolutePos` to convert a relative position to an absolute one everywhere else. We may consider adding a helper as an extension to `GameTestHelper`
