### ISSUE TITLE
Expose MixinExtras's version preferably as a feature

### ISSUE THREAD

**Issue by Jab125** [neoforged/NeoForge#465]
On Fabric, MixinExtras's version can be found easily as MixinExtras is a normal mod.
On NeoForge, MixinExtras isn't a normal mod, which can't be found in the mod list.

**Comment by Technici4n** [comment]
It was decided that we would not ship a mod with the default NeoForge install. Hence the distribution as a library. Indeed, a consequence is that you cannot see it in the mod list. You can get its module version, however.
