### ISSUE TITLE
Mixin application order can be inconsistent between client and server

### ISSUE THREAD

**Issue by embeddedt** [neoforged/NeoForge#47]
For some reason, Forge can apply mixins from individual mods in differing orders on the client and server.

An example of why this matters in the real world: some mods mix into vanilla entity classes and add custom `EntityDataAccessor` data values to be synced. Suppose both mod A and B add a custom data value field. Vanilla assigns these IDs based on the order of the fields in the class (since that is the order the values are registered in). It is possible for the mixins to be applied in the order A, B on the client and B, A on the server. This causes the field order to differ on each side, which means the data values are given different IDs on the server and client. This then leads to error spam/improperly synced entities when trying to play in multiplayer as the client receives incorrect data for each value.

That specific example could be solved by adding some type of event/more predictable ID system for mods to add custom `EntityDataAccessor` flags on entities, or by syncing the IDs to the client on server join (which is what I did in ModernFix), but it doesn't fix the issue that mods are already doing this, and there may be other mixins that subtly break as a result of this order difference.

I think something simple like sorting the mod list by ID would be a clean way to address this issue.

**Comment by TheCurle** [comment]
Could this be because of an underlying situation where the classes are loaded in different order on the sides because of code path differences? We should be sure we aren't fighting the architecture of the game.

**Comment by embeddedt** [comment]
I could be wrong, but I think classloading order shouldn't matter here. The issue is with the order in which mixins from different mods are applied to a given class at the moment it loads - it shouldn't matter if it loads slightly earlier or later.

**Comment by marchermans** [comment]
We do not control the order in which mixins are applied. They are determined by Mixin it self and it's priority system.

Please open a ticket on their repo.
