### ISSUE TITLE
`LootTableLoadEvent.getName()` can be null

### ISSUE THREAD

**Issue by SquidDev** [neoforged/NeoForge#474]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.80-beta

**Description of issue:**
In 1.20.1, the `LootTableLoadEvent` event was fired [when loading the loot table from disk](https://github.com/neoforged/NeoForge/blob/6302718cc167b4b8b0e18cfc09696670788ee1f8/src/main/java/net/minecraftforge/common/ForgeHooks.java#L886). This meant that each loot table was guaranteed to have been loaded from disk, and thus have a well-known ID.

However, in 1.20.4, the event is now fired within the loot table validator. This means that the event is fired for all events, including `LootTable.EMPTY`. As `LootTable.EMPTY` does not have an ID, this causes `LootTableLoadEvent.getName()` to return null.

It's not entirely clear to me what the correct behaviour is. I'd personally vote for maintaining the 1.20.1 behaviour, but I think there's a couple of options here:

 - Preserve the behavioural change, and document that `LootTableLoadEvent.getName()` may return null (just add a nullability annotation).
 - Preserve the current behaviour, but set `LootTable.EMPTY`'s ID to `BuiltInLootTables.EMPTY`.
 - Exclude the empty table from the callback. Either by moving where the event is fired[^1] or just checking for it in the event hook.

[^1]: `LootDataType.deserializeOrDefault` feels like the obvious place to put the event instead, but I'm assuming there's a reason it's not fired from there instead?

**Comment by KnightMiner** [comment]
I don't see any good reason to respond to the event for the emptt loot table, changing it to not ne empty will just break things. Id recommend special casing the event to not fire for empty.

**Comment by SquidDev** [comment]
Thanks!
