### ISSUE TITLE
Failed to run processor: java.lang.ArrayIndexOutOfBoundsException:0

### ISSUE THREAD

**Issue by TheBottomDweller** [neoforged/NeoForge#479]
**Minecraft Version:** {Minecraft version}

**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}

**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}

**Steps to Reproduce:**
1. Download the latest installer for 1.20.4
2. Try running the installer.
3. Start the installation process.

**Description of issue:**

Failed to run processor: java.lang.ArrayIndexOutOfBoundsException:0

See log for more details.

I've attached the Log.

It does this no matter what version I run. Java is up to date, even uninstalled and reinstalled java. Every other mod loader installer works except for this one. Its also unable to be installed using modpack platforms like Curse Forge.

My OS is Windows 11 if that matters.

[neoforge-20.4.83-beta-installer.jar.log](https://github.com/neoforged/NeoForge/files/13878705/neoforge-20.4.83-beta-installer.jar.log)

**Comment by Matyrobbrt** [comment]
The installer is currently broken with Java 8, please run it with Java 17. It will be fixed soon.
