### ISSUE TITLE
Add asItemStack variants to DeferredItem

### ISSUE THREAD

**Issue by Tslat** [neoforged/NeoForge#490]
Pretty quick and easy

ItemStack's constructors has both ItemLike and Holder<? extends Item> signatures, meaning that passing a [DeferredItem](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/registries/DeferredItem.java) into an ItemStack errors at compiletime as javac can't work out which constructor to use.

To rectify this, I propose adding two new methods to DeferredItem and [DeferredBlock](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/registries/DeferredBlock.java):

```java
/**
 * Creates a new {@link ItemStack} with a default size of 1 from this {@link Item}
 */
public ItemStack asItemStack() {
    return asItemStack(1);
}

/**
 * Creates a new {@link ItemStack} with the given size from this {@link Item}
 * 
 * @param count The size of the stack to create
 */
public ItemStack asItemStack(int count) {
    return new ItemStack(asItem(), count);
}
```

**Comment by PlatinPython** [comment]
I would prefer if those methods used `Item#getDefaultInstance`. My particular case is that I always have some NBT data that should attached.
