### ISSUE TITLE
Oversights with `LivingConversionEvent`

### ISSUE THREAD

**Issue by Fuzss** [neoforged/NeoForge#505]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.77

**Description of issue:**
1. `LivingConversionEvent.Pre` nor `LivingConversionEvent.Post` do not fire for skeletons converting to strays in powder snow. This case seems to have simply been missed when the event was introduced.
2. `LivingConversionEvent.Pre` wrongly reports submerged husks converting to drowneds when they actually convert to zombies, that then convert to drowneds in a separate process. This is caused by husks inheriting the event invocation from the zombie superclass.

**Comment by sciwhiz12** [comment]
I've not looked into case 2 yet, but I can note that case 1 isn't an oversight with the _initial introduction_ of the event. Skeletons converting to strays in powdered snow was introduced in [snapshot 21w05a](https://minecraft.wiki/w/Java_Edition_21w05a) for 1.17, while the PR that introduced this event -- MinecraftForge/MinecraftForge#7386 -- was made for and merged in 1.16. That being said, it is an oversight that it wasn't added to the event afterwards.

**Comment by TelepathicGrunt** [comment]
The second case is described a bit weirdly. I did a test and what Fuzss is saying is that Husks will turn into Zombies first when drowning and reset their drowning timer. Then after a bit, the Zombie converts to Drowned. So it does not go from Husk to Downed. It has to drown twice to become a Drowned and is a Zombie in between the two drowning
