### ISSUE TITLE
[Suggestion/Proposal] Multi lang file support

### ISSUE THREAD

**Issue by Speiger** [neoforged/NeoForge#506]
This is mainly a proposal, and really only helps mods that are rather large, but at least I do like to suggest it.

Ofc I am fully aware that this really only works well if fabric/other Modloaders implement that feature too, it would kinda also aid the Modloader divide if not all Modloaders support it.

But lets say you have a mod that has has hundreds/thousands of lines in a language file.
Wouldn't the option to have an language file into multiple ones help with separating these things better?

I mean if your total language file has 3k lines (or 300k characters).
Wouldn't it be helpful if you could split it up into multiple files that would be less then 1k lines each?

My suggestion would be to allow prefixes in language files so you could have multiple language files,

To give a example of an IRL Example we have:
| File Name | Purpose | IRL example lines currently |
|-------------|----------|------------------------------| 
| blocks_en_us.json | For your blocks<br>and Block Tooltips | 478 lines |
| items_en_us.json | For your items<br>and Item Tooltips | 459 lines |
| en_us.json | Misc Entries<br>categories that are to small | 751 lines |
| wiki_en_us.json | For your Wiki<br>(If you have one) | 709 lines |

(Note: the lines do not add up to 3k since we split it up into a few more files, but that would be way past the idea, that's why only ~80% is accounted for)

It would have multiple benefits too for devs/translators.
Assuming large scale projects.
- 1: Everyone who is at that scale doesn't have to write their own tools for that.
- 2: It would help organization of projects and would also teach projects that jump from mid to large scale.
- 3: It also would help translators with managing translations since they usually don't have access to merge tools/they have to deal with the bulk version to test things.

I am honest in saying that I highly doubt that this suggestion would be even entertained.
But neoforge has proven me wrong multiple times.
So it's a shot into the dark with hope that I am proven wrong again.

**Comment by TelepathicGrunt** [comment]
wouldn't a more cleaner solution be to make the lang be the folder name. So `en_us/blocks.json`, `en_us/items.json` and behind the scenes, it gets all collapsed into a single en_us.json collection for the game at runtime.

**Comment by Speiger** [comment]
@TelepathicGrunt I suggested prefixes because that would be easier to implement IMO.
Instead of checking for exact files you can instead use: file.endsWith("en_us.json") and simply support the existing format and support "any" prefix the dev needs/wants vs having to iterate over folders.

But if neoforge thinks a folder solution is better, then be my guest.

Edit:
I just would love to have that feature in general.
As long as the implementation is not pure trash (in other words: more work then the current system minecraft has) then i don't care how its implemented.

**Comment by Gaming32** [comment]
It could be made as a Gradle task fairly easily.

**Comment by Speiger** [comment]
@Gaming32 that is also a solution, but a less favorable IMO.
Because then translators have to manually merge/split it to if they want to contribute to projects.
(if the devs haven't setup something like Crowdin or something like that)

And the proposal is to make work easier for devs and translators to maintain langauge files.

**Comment by Gaming32** [comment]
I don't see how merging the lang files at build time instead of runtime changes how someone works contribute to the mod.

**Comment by Speiger** [comment]
@Gaming32

If you have to split the file to contribute but merge it to test it that will be much more painful for translators.
This entire proposal is a convenience proposal, if you take out the convenience then the proposal is void.
And yes that includes contributors that don't have 100% access to the build tools.

Edit: Not all projects are open source but usually open source API/lang files so people can contribute to it if they want to.
(And opensource isn't a requirement for people wanting to contribute to it)

**Comment by XFactHD** [comment]
Having to merge the files manually if you want to test without access to the build tools is a valid concern but why would you have to split the file to contribute at all if the language files are open source? The point made by Gaming32 (at least to my understanding) is that the language files stay entirely separated right until they are copied to the build output in dev or the JAR when building for release.

It's worth noting that the way language files are loaded is very dependent on loading the so-called resource stack of very specific file names. Making your suggestion of runtime merging of arbitrary files work would require substantial changes to the way these are loaded, which is unlikely to be something we'd want to do for such a niche issue.

**Comment by shartte** [comment]
Managing these translation files manually to begin with is your first problem. Use a tool like Crowdin ;-)

I really don't see what this adds beyond more complexity. Joining JSON files at build time really seems like the best option if you really must split them.

**Comment by marchermans** [comment]
This can be implemented by the modder if they want:
You can use a custom in-memory resource pack that combines the files.

**Comment by Matyrobbrt** [comment]
As stated above, there are multiple ways splitting can be achieved on the mod's side. Such changes would be too invasive for NeoForge to implement.

**Comment by Speiger** [comment]
> Having to merge the files manually if you want to test without access to the build tools is a valid concern but why would you have to split the file to contribute at all if the language files are open source?

@XFactHD In my example we don't have a merged en_us.json if you haven't realized it.
So if the source files are split but the jar files are merged then you would have to split it since a merged pullrequest wouldn't be accepted.
You either merge it yourself to test it, or you work with the merged file to make testing easier but have to split it if you want to submit it to the project.

> It's worth noting that the way language files are loaded is very dependent on loading the so-called resource stack of very specific file names. Making your suggestion of runtime merging of arbitrary files work would require substantial changes to the way these are loaded, which is unlikely to be something we'd want to do for such a niche issue.

Not really it would change it from:
```java
ResourceLocation resourcelocation = new ResourceLocation("ModId", "lang/en_us.json");
appendFrom("en_us", p_265765_.getResourceStack(resourcelocation), map);
```

To this:
```java
List<Resource> allResources = new ObjectArrayList<>();
p_265765_.listResourceStacks("lang", T -> T.getPath().endsWith("en_us.json")).values().forEach(allResources::addAll);
appendFrom("en_us", allResources, map);
```
And that technically would maintain the same logic since we are looping over all mods anyways in the exact same order.
Its just a bulk processing version.

This covers only the Client side and not server side, but server side isn't that much more difficult to change.

Next person:
> Managing these translation files manually to begin with is your first problem. Use a tool like Crowdin ;-)


Till this day I have never used it and I am still in the phase of "I want to look into it", and I am pretty sure that I am not the only large scale mod that was/is at that phase.

> This can be implemented by the modder if they want:
You can use a custom in-memory resource pack that combines the files.

@marchermans 
Atm we hack into the lang loader, both client/server and simply add the functionality we needed.
It was the easier method for me at the time. (Not saying it was, but it was for me at the time)

>  As stated above, there are multiple ways splitting can be achieved on the mod's side. Such changes would be too invasive for NeoForge to implement.


@Matyrobbrt 
Thank  you for not letting me provide an example before making a decision.
As you can see in my example: See above. It could be technically even a performance boost? with very little changes to how minecraft loads lang files.
It would be backwards compatible while providing new functionality.

But thank you for making a choice very early without knowing how easy it is and proving my preconception of how forge worked before and what kept me away.

Edit because hiding it make it viewed worse IMO.
Conclusion.
Real reason:
Out of scope and to much of an edge case.

Not the BS reason @Matyrobbrt gave.

**Comment by Speiger** [comment]
Conclusion.
Real reason:
Out of scope and to much of an edge case.

Not the BS reason @Matyrobbrt gave.
