### ISSUE TITLE
Weird Damage Calculation

### ISSUE THREAD

**Issue by PellucidDice** [neoforged/NeoForge#516]
When updating to the latest version under mod dev environment from **_20.4.83-beta_** to **_20.4.107-beta_** I noticed that the entity hurt values are reduced to a lower value.
Even kill command won't kill the player (**_/kill_**), instead it deals 1 damage to the player.

Could be my own problem, needs some more testing.
But the recent damage changes for NeoForge may also potentially broke the system so I'll just put an issue report here to see if anyone has experienceed the same.

**Comment by Shadows-of-Fire** [comment]
Ah, yes, problematically, this should be `return amount` instead of `return 1.0F`
https://github.com/neoforged/NeoForge/blob/e24d6febe9fffee20937861af50086e2f0793d4c/src/main/java/net/neoforged/neoforge/common/damagesource/IScalingFunction.java#L24-L34

**Comment by PellucidDice** [comment]
Thank you :)
