### ISSUE TITLE
Update/promotions URL does not exist

### ISSUE THREAD

**Issue by MelanX** [neoforged/NeoForge#52]
**Minecraft Version:** 1.20.1

**NeoForge Version:** upstream

**Steps to Reproduce:**
 1. Start Minecraft
 2. Look at the log

**Description of issue:**
The update URL is set to "https://maven.neoforged.net/releases/net/neoforged/forge/promotions_slim.json", which is correct I guess, but the file doesn't exist at the moment. Because of that, there's a stacktrace each start of the game. 

I know, other things have priority. Just wanted to report that, so it won't be forgotten :)

**Comment by vaylor27** [comment]
Can confirm

**Comment by itzg** [comment]
This is blocking support for NeoForge in the `itzg/minecraft-server` Docker image. Or am I supposed to use the Forge promotions JSON for now?

**Comment by Matyrobbrt** [comment]
For now you're supposed to use the [maven metadata](https://maven.neoforged.net/releases/net/neoforged/forge/maven-metadata.xml).
