### ISSUE TITLE
connecting to a vanilla server, with mods loadded that are needed on the server side throws confusing error

### ISSUE THREAD

**Issue by fayer3** [neoforged/NeoForge#528]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.108-beta

**Logs:** https://mclo.gs/aSOFpfN

**Steps to Reproduce:**
 1. add a mod that adds blocks
 2. try to connect to a vanilla server
 3. see confusing error

**Description of issue:**

when a mod adds stufff that also needs it to be on the server, a confusing error shows up, about installing neoforge, even though it is obviously installed

in this example I had balm and Farming for Blockheads  installed:
https://www.curseforge.com/minecraft/mc-mods/balm
https://www.curseforge.com/minecraft/mc-mods/farming-for-blockheads

![grafik](https://github.com/neoforged/NeoForge/assets/8282299/e4bd85ba-764d-4196-9c91-2355bab155d9)

the message is thrown here, because of missing blocks it seems:
https://github.com/neoforged/NeoForge/blob/39661d944e8083890621494e8f1b0cd06dd63d23/src/main/java/net/neoforged/neoforge/network/registration/NetworkRegistry.java#L703
![grafik](https://github.com/neoforged/NeoForge/assets/8282299/a27acc1d-c6a6-42cf-8221-d1a6b98ee85e)

**Comment by Technici4n** [comment]
This was fixed with NeoForge `20.4.162-beta`.
