### ISSUE TITLE
Error log enhancements.

### ISSUE THREAD

**Issue by Thunderrock424242** [neoforged/NeoForge#53]
In the logs error logs for when a mod is incompatible it would be nice either at the end of the log or beginning it would tell you what went wrong if there are dependencies missing or what is incompatible.

**Comment by sciwhiz12** [comment]
I believe this feature already existed before you opened this request, as implemented by https://github.com/neoforged/FancyModLoader/commit/769da7060ab02637f25ae7e88178e5553fa9311a. That feature logs the missing or unsupported dependencies to the log file (which is separate yet coexists with the error screen that reports the same).

Additionally, #1479 improves the mod loading crash report to, among other things, actually translate the failure messages, which helps when reading only the crash report.

Closing as solved.
