### ISSUE TITLE
A proposition to add a new form of `mods.toml`

### ISSUE THREAD

**Issue by Ran-Mewo** [neoforged/NeoForge#531]
For projects like [Forgix](https://github.com/PacifistMC/Forgix) and [modfusioner](https://github.com/firstdarkdev/modfusioner)
Neoforge using the same formats as Forge would kill these projects
Quilt got around this by creating a `quilt.mod.json` which basically acts like if this file is found first then use this as the primary file that specifies the mod otherwise use `fabric.mod.json`

I'd love if something similar like `neoforge.mods.toml` was created
I also love how you guys added a mixin field to your `mods.toml`, it essentially kept these projects alive.

**Comment by Technici4n** [comment]
This has already been brought up before, and we have decided to stick with the current `mods.toml` format.

**Comment by Jab125** [comment]
You are still able to create merged Forge/NeoForge jars with a single `mods.toml`

You'll need to make both the forge and neoforge dependencies optional, add both the `mandatory=true` and `type="optional"` in your mod metadata, as well as adding neoforge's mixins to the mods.toml (create a mixin plugin on forge to not load those mixins if it can't find the NeoForge mod class.)

The `@Mod` annotations are in different packages, so you can put forge and neoforge init in separate classes.

**Comment by Ran-Mewo** [comment]
*sigh* I love it when developers have to do more work arounds just to create mods for people to enjoy.
I guess I'll take the pain and look into creating custom classes in build time to manage everything for them...

**Comment by KnightMiner** [comment]
You have to do more work, but every neoforge developer has to do less work. I think a single person doing more work is better than every developer doing more work, don't you agree?

**Comment by Ran-Mewo** [comment]
> This has already been brought up before, and we have decided to stick with the current `mods.toml` format.

Oh wait I think there's been a misunderstanding, I wasn't saying to change the format
I was saying something like
```
if (file("neoforge.mods.toml").exists) {
   ModFileReader.read("neoforge.mods.toml")
} else {
   ModFileReader.read("mods.toml")
}
```

it's the same format and everything but it attempts to read from `neoforge.mods.toml` first if it exists, otherwise reads from `mods.toml`

**Comment by sciwhiz12** [comment]
I'd like to add that I did previously bring up the suggestion of renaming the `mods.toml` file, on the bases that future changes to the format by FancyModLoader may make it incompatible with the format of `mods.toml` as understood by ForgeModLoader, and that it would be unwise to have two divergent loaders use the same file (which may have differing formats at some point in the future.) I was overruled by others.

**Comment by Matyrobbrt** [comment]
I would have liked the `mods.toml` file to be renamed too, but granted that the idea was turned down because "the file is part of FML not Forge" (which arguably doesn't make sense because ForgeModLoader isn't our project, it's part of Forge), I would support at the very least prioritizing loading a `neoforge.mods.toml` file for the sake of multiloader mods and 3rd parties that want to detect if a mod is a NeoForge mod.
