### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by DSLZL** [neoforged/NeoForge#536]
I remember some time ago, there was a paragraph in your article that you wanted to choose a name, but you didn't know what to choose, so you used Neoforge
I think we could call it **Find**
First, you are finding the new way
Second, it represents your quest to innovate and get rid of the old
Third, it starts with F
I'm sorry if my words have made you feel unpleasant

**Comment by Technici4n** [comment]
We're not gonna change our name... :P

**Comment by DSLZL** [comment]
> We're not gonna change our name... :P

Okay, maybe I'm mistaken, I seem to have seen you want to take a name, so sorry to bother you
