### ISSUE TITLE
I hope to add the ability to download and install mods from courseforge or modrinth and automatically restart MC

### ISSUE THREAD

**Issue by gameak2334498769** [neoforged/NeoForge#54]
I hope Neofoged to add the ability to download and install mods from courseforge or modrinth and automatically restart MC,such as Winget,Modget,Apt-get and so on

**Comment by sciwhiz12** [comment]
We do not have any plans to have NeoForge itself download and install mods from mod distribution platforms, such as CurseForge and Modrinth, and automatically restart Minecraft. Installation of mods are in the hands of the user, whether manually (drag and drop into the `mods` folder) or through a modpack launcher/manager, such as CurseForge's own launcher, MultiMC, and others.

Neither do we plan to provide our own application which presents an interface for downloading and installing mods, and launching Minecraft (or rather, the official Minecraft launcher). Many applications, such as those mentioned above, work fine for that purpose; making our own only divides our manpower to maintain and develop NeoForge.

Thank you for the suggestion, but unfortunately we cannot accomodate it.

(I will note that FML does offer an interface -- custom mod locators -- which allow for runtime discovery of mods, which may even be downloaded at runtime from some source such as a trusted server. However, that is for modpack/server developers to utilize if they are willing and able to do so.)
