### ISSUE TITLE
Journeymap render thread error, "Ressource reload failed", java.lang.NoClassDefFoundError, >1.20.4.69

### ISSUE THREAD

**Issue by codingnewcode** [neoforged/NeoForge#580]
---
name: Journeymap "Ressource reload failed"
about: [Render thread/ERROR] [net.neoforged.fml.DeferredWorkQueue/]: Mod 'journeymap' encountered an error in a deferred task:
java.lang.NoClassDefFoundError: net/neoforged/neoforge/network/simple/MessageFunctions$MessageEncoder
title: ''Journeymap render thread error, "Ressource reload failed", java.lang.NoClassDefFoundError, >1.20.4.69
labels: triage
assignees: ''

---

**Minecraft Version:** 1.20.4

**NeoForge Version:** 1.20.4.130

**Logs:** see:
[debug_1.20.4.130.log](https://github.com/neoforged/NeoForge/files/14062945/debug_1.20.4.130.log)
[latest_1.20.4.130.log](https://github.com/neoforged/NeoForge/files/14062946/latest_1.20.4.130.log)
[debug_1.20.4.69.log](https://github.com/neoforged/NeoForge/files/14062948/debug_1.20.4.69.log)
[latest_1.20.4.69.log](https://github.com/neoforged/NeoForge/files/14062949/latest_1.20.4.69.log)

**Steps to Reproduce:**
 1. A. using only one mod, journeymap-1.20.4-5.9.20-neoforge with neoforge 1.20.4.130 (but issue started happening around 1.20.4.70+)
 2. start game with minecraft launcher
 3. at main menu "ressource reload failed" error message
 4. if playing a single player world endlessly stuck at "preparing ressources screen
 5. B.no issues with 1.20.4.69 with same mod
 6. C. no issues with 1.20.4.130 with no mod

**Description of issue:**
Neoforge arround 1.20.4.70+ displays "ressource reload failed" error message in start menu of the game, then when starting a single player world gets stuck endlessly at "preparing ressources".

Logs provide more info (of 1.20.4.130) at line : 
```
[26janv.2024 10:18:18.325] [Render thread/ERROR] [net.neoforged.fml.DeferredWorkQueue/]: Mod 'journeymap' encountered an error in a deferred task:
java.lang.NoClassDefFoundError: net/neoforged/neoforge/network/simple/MessageFunctions$MessageEncoder
	at journeymap.common.network.packets.PacketManager.<init>(PacketManager.java:21) ~[journeymap-1.20.4-5.9.20-neoforge.jar%23177!/:1.20.4-5.9.20]
```

<img width="1920" alt="ressource reload failed" src="https://github.com/neoforged/NeoForge/assets/155306405/94b914d9-51d1-43ac-97dd-48827047bd2a">
<img width="1915" alt="ressource reload failed 2" src="https://github.com/neoforged/NeoForge/assets/155306405/f6f9acc7-cb54-42a5-981e-6e44ee6941af">

apologies if issue was already posted, i do ont use discord

i think this is a journeymap issue rather (and they would have to fix it) but i dont know if neoforge plans to change this

i am also not very knowledgeable about minecraft code in  general

thanks,

**Comment by Technici4n** [comment]
JourneyMap needs to update to a newer version of NeoForge.
