### ISSUE TITLE
The pumpkin overlay and the spyglass overlay can be rendered at the same time.

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#601]
**NeoForge Version:** 20.4.147-beta

**Steps to Reproduce:**
 1. Use a spyglass with a pumpkin on your head (not IRL)

**Description of issue:**
The pumpkin overlay and the spyglass overlay can be rendered at the same time.

Note: https://bugs.mojang.com/browse/MC-204159 is WAI

**Screenshot:**
NeoForge:
![2024-02-01_22 10 40](https://github.com/neoforged/NeoForge/assets/68275908/36903a61-ccb9-43ee-923e-d8264de388b4)

Vanilla:
![2024-02-01_22 12 21](https://github.com/neoforged/NeoForge/assets/68275908/bc4c1996-5bc6-40fd-861d-9402c6f7cdd5)

**Comment by sciwhiz12** [comment]
`ExtendedGui#renderHelmet` is responsible for rendering the pumpkin overlay, but it lacks a not-scoping check to match the vanilla behavior at `Gui#render` (which contains both the spyglass overlay and pumpkin overlay rendering within the second `if`-statement).

The fix should be as simple as adding a `!this.minecraft.player.isScoping()` check to `ExtendedGui#renderHelmet`.
