### ISSUE TITLE
Add easy way to get growing block with CropGrowEvent from GrowingPlantHeadBlock

### ISSUE THREAD

**Issue by khjxiaogu** [neoforged/NeoForge#605]
CropGrowEvent usually have a blockstate for growing block, however, it's impossible to get growing block from GrowingPlantHeadBlock as it calls event by:
```
net.neoforged.neoforge.common.CommonHooks.onCropsGrowPre(pLevel, pPos.relative(this.growthDirection), pLevel.getBlockState(pPos.relative(this.growthDirection)), pRandom.nextDouble() < this.growPerTickProbability)
```
Unlike other plants, this code would only provide the blockstate that the plant are growing into but not the original growing plant. There should be a way to get growing block from the event.     
Possible fixes:
1. change this code into 
```
net.neoforged.neoforge.common.CommonHooks.onCropsGrowPre(pLevel, pPos.relative(this.growthDirection), state, pRandom.nextDouble() < this.growPerTickProbability)
```
2. modify CropGrowEvent and add a blockstate for the origin block.

**Comment by TelepathicGrunt** [comment]
Looking at the other callers of the event, they seem to pass in the plant block that the new block is going to grow off of. Example being bamboo or cactus. So that means option 1 is the correct option of passing in the `state` instead of trying to get it from the world.
