### ISSUE TITLE
[Suggestion] Add one-liner way to register builtin resourcepacks for mods

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#61]
A while ago, I wanted to add an optional builtin resourcepack for my mod that users can enable on their own like how Minecraft has a programmer art builtin resourcepack. I was then shown this is how that is done:
https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/test/java/net/minecraftforge/debug/AddPackFinderEventTest.java

My thought is I feel like this could be simplified to a one liner registration for modders. Here’s the idea of such a system:

- Modders creates a folder called resourcepacks in their mod’s resources folder.
- Then the modder puts the resourcepack they want to use into that resourcepacks folder.
- Now the modder calls a single line while giving it a resourcelocation where the namespace is the modid of the mod’s resourcepacks folder to look under and the path is the name of resource pack itself to load as a built-in resourcepack.

Something like:
`event.registerResourcePack(new ResourceLocation(“modid”, “packfilename”), PackActivationType.DISABLED_DEFAULT, Component.literal(“Display Name Of Resourcepack”));`

This may be easier for people to find and use as the current code to make builtin resourcepacks looks tricky to figure out on our own without asking in the Neoforged discord. I had asked in another discord earlier and two people gave me incorrect/even more complex solutions which seems to show that this system is not well known. A simpler API may go a long way

**Comment by dhyces** [comment]
imo, mimic mc's `data/datapacks` with `assets/resourcepacks` and extend pack.mcmeta to allow for defining that info in the mcmeta, reducing it to be entirely data-driven.

**Comment by TelepathicGrunt** [comment]
if a modder has a builtin resource pack that is only supposed to be added if a specific other mod is on, then making it data-driven in mcmeta would be insufficient. Having the code event would be more ideal in this case

**Comment by dhyces** [comment]
> if a modder has a builtin resource pack that is only supposed to be added if a specific other mod is on, then making it data-driven in mcmeta would be insufficient. Having the code event would be more ideal in this case

Pack overlays

**Comment by TelepathicGrunt** [comment]
@dhyces Just saying two words with no further info provides nothing to the discussion. What are pack overlays. How do they work. How would one specifically use it to targets specific mods?
 
 The overlays entry on the wiki doesnt seem to show anything that looks like it can target specific modids.
 https://minecraft.wiki/w/Resource_pack
![image](https://github.com/neoforged/NeoForge/assets/40846040/c3a81ddd-dfba-48e9-af7d-9479b6329cca)

**Comment by dhyces** [comment]
> @dhyces Just saying two words with no further info provides nothing to the discussion. What are pack overlays. How do they work. How would one specifically use it to targets specific mods?
>  
>  The overlays entry on the wiki doesnt seem to show anything that looks like it can target specific modids.
>  https://minecraft.wiki/w/Resource_pack
> ![image](https://github.com/neoforged/NeoForge/assets/40846040/c3a81ddd-dfba-48e9-af7d-9479b6329cca)

Give me some time to finish breakfast and power on my pc, then I'll provide some more info about it. To clarify, I've never been opposed to your in-code helper, but because of how data oriented the base method is, I proposed there also be a fully data-driven operation.

**Comment by dhyces** [comment]
Pack overlays are basically a way to add/remove resources from a pack based on a "version". For modders, the datapack/resourcepack version is not very helpful, but adding conditions makes them useful for built-in packs. NeoForge currently supports conditions for overlays ([example](https://github.com/neoforged/NeoForge/blob/1.20.x/tests/src/generated/resources/pack.mcmeta)) and fabric has an open PR to support them ([example](https://github.com/Apollounknowndev/fabric/blob/overlay-conditions/fabric-resource-conditions-api-v1/src/testmod/resources/resourcepacks/overlay_test/pack.mcmeta)). For built-in packs, this would allow conditional registration of resources. Fabric already goes part of the way in this endeavor and will search `resourcepacks/data` and `resourcepacks/assets` if a pack is registered in code. I propose going the rest of the way, though instead using the vanilla directories `data/datapacks` and `assets/resourcepacks`, defining custom fields within `pack.mcmeta` for how the pack is activated, where it should load (top/bottom) if force enabled, etc.

NeoForge PR which enables this functionality: https://github.com/neoforged/NeoForge/pull/483
Fabric PR which would enable this functionality: https://github.com/FabricMC/fabric/pull/3702

**Comment by TelepathicGrunt** [comment]
I see. The neo added conditions is why i couldn't find any info on that. I am not familiar with that area so I'll leave it to another person to add the extra stuff for pack.mcmeta to work with the overlays. I have a PR for just the helper in code for AddPackFindersEvent to reduce the amount of code modders need to write.
