### ISSUE TITLE
renderHealthMount is rendered only in survival mode

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#626]
Same as https://bugs.mojang.com/browse/MC-13818, but in NeoForge

**Comment by ZestyBlaze** [comment]
I believe a horse's health bar being rendered is _meant_ to be a survival only thing, same as how the player's health bar is only rendered on survival too?
Someone can correct me if I'm wrong

**Comment by Lolothepro** [comment]
> I believe a horse's health bar being rendered is _meant_ to be a survival only thing, same as how the player's health bar is only rendered on survival too? Someone can correct me if I'm wrong

No

**Comment by Lolothepro** [comment]
Vanilla:

![2024-02-11_21 27 39](https://github.com/neoforged/NeoForge/assets/68275908/eadbf2d7-8a69-4eac-a75c-a2386d8a5c61)

**Comment by Lolothepro** [comment]
...
