### ISSUE TITLE
Re-add note in the fix for bug MC-112730

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#635]
see https://github.com/MinecraftForge/MinecraftForge/pull/3651

https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/client/renderer/chunk/SectionRenderDispatcher.java.patch#L84

Note to add : Neo: Fix MC-112730

**Comment by embeddedt** [comment]
Fixed in https://github.com/neoforged/Kits/commit/075b1432b741c40d62bcccaca192029efcc66e38 for 1.21.
