### ISSUE TITLE
Wrong `@Nullable` position on `getBeaconColorMultiplier`

### ISSUE THREAD

**Issue by PlatinPython** [neoforged/NeoForge#677]
[IBlockStateExtension#getBeaconColorMultiplier](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/extensions/IBlockStateExtension.java#L427-L428) and [IBlockExtension#getBeaconColorMultiplier](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/extensions/IBlockExtension.java#L533-L534) should both be `float @Nullable []`.

The current annotation position says that they return a "non null array of nullable `float`s" instead of the wanted "nullable array of `float`s".

I did not make a PR because a new build just for that felt unnecessary, so it should just be included in the 1.20.5 port or something.

**Comment by TelepathicGrunt** [comment]
Looks like this was changed to an integer return. This is correct tho now right? 
![image](https://github.com/neoforged/NeoForge/assets/40846040/f3b287d1-bf3f-4f69-8801-3015ffe61350)

Yeah annotation is correct now. Will close this
