### ISSUE TITLE
Crashes on world screen when rendering corrupted level summaries

### ISSUE THREAD

**Issue by tmvkrpxl0** [neoforged/NeoForge#683]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.190

**Logs:** https://gist.github.com/tmvkrpxl0/fb3f5c025697253ba8dd25b41ee49fc4

**Steps to Reproduce:**
 1. Add this world
[World1.zip](https://github.com/neoforged/NeoForge/files/14477850/World1.zip)
 2. Load world screen
 3. crash

**Description of issue:**
Method `LevelSummary#isLifecycleExperimental` added by https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/level/storage/LevelSummary.java.patch does not take account that `this.settings` can be null.
If the level is corrupted or it's symlink then `settings` is set to null.

**Comment by Shadows-of-Fire** [comment]
This was added to support https://github.com/MinecraftForge/MinecraftForge/pull/7275 so I guess this is a very old bug.  Honestly I would be in favor of dropping the checkbox thing entirely and just nuking the experimental settings screen, it's just noise.

**Comment by embeddedt** [comment]
Fixed by #864 for 1.20.5.
