### ISSUE TITLE
Make dedicated servers set `online-mode=false` by default in dev

### ISSUE THREAD

**Issue by Shadows-of-Fire** [neoforged/NeoForge#695]
This can be done by patching `public final boolean onlineMode = this.get("online-mode", true);` in `DedicatedServerProperties` to use `!IS_RUNNING_IN_IDE` instead of always defaulting to true.

**Comment by marchermans** [comment]
Alternatively we are considering adding a log in mechanism to neogradle on the client

**Comment by TelepathicGrunt** [comment]
Having this online mode set to false by default would be extremely great. I keep forgetting to set it. I like having my dev dedicated server not actually being online too so I would just keep setting it to false, even with a log-in mechanism available.

**Comment by KnightMiner** [comment]
Does neo currently automatically accept the server eula for you? IIRC it did not in the past. The fact I have to both accept the eula and set online mode to false led me to just create a folder with both those properties and whatever other "server defaults" I want that I copy into all my dev environments.

**Comment by Shadows-of-Fire** [comment]
Yes https://github.com/neoforged/NeoForge/blob/8dd9e1803f5b163f12b85db4f3a152860197b795/patches/net/minecraft/server/Eula.java.patch#L8
