### ISSUE TITLE
Unnecessary `Stitcher` patch

### ISSUE THREAD

**Issue by PepperCode1** [neoforged/NeoForge#705]
https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/client/renderer/texture/Stitcher.java.patch#L32

Vanilla 1.19.3 changed the stitcher logic to optimize the atlas size. The new logic is weird in that it handles cases which cannot possibly occur, but the patched logic will never produce a better result than the vanilla logic and the vanilla logic always produces the best possible atlas size, so the patch should be removed.

**Comment by ChampionAsh5357** [comment]
I believe this is correct since, when expanding the stitcher, the region is updated to have the width in the expanded area with the border set to the new width.

Pre-1.19.3:
```
regionWidth = holderWidth
storageWidth += holderWidth
```

Post-1.193:
```
regionWidth = expandedWidth - storageWidth 
storageWidth = expandedWidth 
```
