### ISSUE TITLE
Unnecessary `useCombinedDepthStencilAttachment` client config value

### ISSUE THREAD

**Issue by PepperCode1** [neoforged/NeoForge#707]
The config value can be found [here](https://github.com/neoforged/NeoForge/blob/1.20.x/src/main/java/net/neoforged/neoforge/common/NeoForgeConfig.java#L87).

The only place it used in NeoForge is [here](https://github.com/neoforged/NeoForge/blob/1.20.x/patches/com/mojang/blaze3d/pipeline/RenderTarget.java.patch#L20).

To me to is strange that the user should be able to configure this. There is no case where changing the config value can resolve a hardware incompatibility. The config also affects all framebuffers. It would seem more appropriate to be able to configure this per-framebuffer as a parameter to `enableStencil`.

However, even that is not necessary. A GL documentation page for `glFramebufferTexture2D` [here](https://docs.gl/gl3/glFramebufferTexture) says the following.

> Attaching a level of a texture to `GL_DEPTH_STENCIL_ATTACHMENT` is equivalent to attaching that level to both the `GL_DEPTH_ATTACHMENT` and the `GL_STENCIL_ATTACHMENT` attachment points simultaneously.

Therefore, the config actually does nothing, as both code paths have the same result. In my opinion, the config value should be removed and the separate attachment approach should always be used.

**Comment by Shadows-of-Fire** [comment]
This was added by @gigaherz in https://github.com/neoforged/NeoForge/commit/8e5138da2757c1ac71d104180bd0984fbcfaffb7

I don't see a related PR, so he'll have to comment on why it exists.

**Comment by gigaherz** [comment]
I can't remember all the details about this, but there was some reason why the combined code path was crashing some GPUs. I'll try to find discord logs later.

**Comment by gigaherz** [comment]
The conversation happened on a private channel. Link: https://discord.com/channels/313125603924639766/584953713060347914/728399383112187906

<img src="https://github.com/neoforged/NeoForge/assets/685851/d11c5a75-0583-445b-a72b-8d5d0edc4f28" width="400" />
<img src="https://github.com/neoforged/NeoForge/assets/685851/19602fa0-6161-4b61-8914-5dc868c09d72" width="400" />

It appears that it actively errored in my PC, and separating the attachments fixed the error. I do not know what reason there was for it, only that separating the attachment fixed the error.

**Comment by TelepathicGrunt** [comment]
@gigaherz @PepperCode1 So what is the stance? Should we remove the config and stuff and see if it errors at all for anyone?

**Comment by Matyrobbrt** [comment]
This option was removed in 1.21.2 due to Mojang changes.
