### ISSUE TITLE
Re-fire villager/wandering trader trade events during /reload

### ISSUE THREAD

**Issue by Shadows-of-Fire** [neoforged/NeoForge#721]
Currently both of these events are only fired during the `ServerAboutToStartEvent`, which means that reflecting changes to them requires restarting the server.

I believe these events should be capable of being fired during resource reload instead, allowing for trades to be recomputed on `/reload`.

**Comment by TelepathicGrunt** [comment]
Would firing the events in TagsUpdatedEvent work? Since I believe tags are the last thing to be reloaded on /reload and someone could have their trade be using tags. So this event should cover it right?
