### ISSUE TITLE
Mods screen 'Illegal format found'

### ISSUE THREAD

**Issue by ApexModder** [neoforged/NeoForge#734]
**Minecraft Version:** 20.4/5

**NeoForge Version:** 20.4.184 / 20.5.0-alpha.24w12a [_local build_]

**Steps to Reproduce:**
 1. Set mod name to something with a `'` (`Fantasy's Dice`)
 2. Launch game and open the mods screen
 3. Console will spam something like the following
 `[18:36:30] [Render thread/ERROR] [ne.ne.ne.co.I18nExtension/CORE]: Illegal format found Fantasy's Dice`

**Description of issue:**
When including a `'` in your mods name for possessiveness it causes a illegal format issue when opening the mods screen, and possibly anywhere else which references the mods name.

Break points seem to show that the game is thinking its a unterminated string, but shouldn't it be looking for `"` for string terminations? I am using `'` for possessiveness in my mods name.

[Extended conversation in Neo-cord](https://discord.com/channels/313125603924639766/852298000042164244/1220444961783283812)

<details>

<summary>Break point of error/exception</summary>

![image](https://github.com/neoforged/NeoForge/assets/29412632/6a6c0e5f-91ed-4d3a-afd0-baf609023fd1)

</details>

**Comment by embeddedt** [comment]
This was fixed by https://github.com/neoforged/NeoForge/pull/851 for 1.20.5 and https://github.com/neoforged/NeoForge/pull/686 for 1.20.4.
