### ISSUE TITLE
can't start minecraft

### ISSUE THREAD

**Issue by XianZhu05** [neoforged/NeoForge#75]
**Minecraft Version:** {1.20.1}

**Forge Version:** {forge-1.20.1-47.1.59}

**Logs:** {}

**Steps to Reproduce:**
 1. installer the noforged
 2. start game

**Description of issue:**
 i can't start game
[minecraft-exported-crash-info-2023-08-02T09-33-24.zip](https://github.com/neoforged/NeoForge/files/12235141/minecraft-exported-crash-info-2023-08-02T09-33-24.zip)

**Comment by KLONOA9X6** [comment]
Did you tried official minecraft launcher?

**Comment by Shadows-of-Fire** [comment]
This is a bug in whatever launcher you are using, not Neo itself.  You'll have to get them to resolve it.
