### ISSUE TITLE
GLOBAL_LOOT_MODIFIER_SERIALIZERS in NeoForgeMod are never registered

### ISSUE THREAD

**Issue by RadonCoding** [neoforged/NeoForge#753]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.214

**Description of issue:** 
GLOBAL_LOOT_MODIFIER_SERIALIZERS in NeoForgeMod are never registered to the IEventBus.

**Comment by sciwhiz12** [comment]
Looks to be an oversight in PR #466 when it added the `AddTableLootModifier` from the original PR #65, as the original PR registered the `DeferredRegister` properly.

The lack of a test also didn't help in catching this bug.

**Comment by Spinoscythe** [comment]
@RadonCoding Ty for bringing this to my attention, I will fix this ASAP
