### ISSUE TITLE
Modded Recipe Result Missing NBT Tags

### ISSUE THREAD

**Issue by morgentruesdale** [neoforged/NeoForge#773]
Trying to port my mod from 1.16.5 to newer versions of minecraft (1.20.x), and running into this issue with recipes. NBT tags aren't being added to the result as they did previously. For instance, for the recipe in the following paste, the player should be rewarded with an item called "Swiss Grilled Cheese," but instead they are rewarded with an item called "Basic Sandwich" without the proper tag (or any tags at all actually).

https://pastebin.com/YWKh42dq

I'd have asked on Discord, but unfortunately the invite link seems to be broken wherever it's posted. Any idea what's causing this?

**Comment by Technici4n** [comment]
Which Minecraft version exactly? In any case, we do support NBT in the output.

**Comment by Shadows-of-Fire** [comment]
During the 1.20.2 ingredient nonsense the key was changed from `nbt` to `tag` - IMO that change should be reverted back to `nbt` both since `tag` is used as actual tags in this context, and for historical consistency.

**Comment by TelepathicGrunt** [comment]
> I'd have asked on Discord, but unfortunately the invite link seems to be broken wherever it's posted. Any idea what's causing this?

@stronwood If you were banned in past from the Forge discord, that might be why the neoforge links are not wokring. You can reverse the old ban at this link https://camelot.neoforged.net/ban-appeals/313125603924639766

Otherwise this link should work: https://discord.neoforged.net/

**Comment by Shadows-of-Fire** [comment]
Components will render the current syntax obsolete in all means, and we can't change the key name for the current versions due to BC rules, closing.
