### ISSUE TITLE
Add more protections to SavedData for data corruption

### ISSUE THREAD

**Issue by raoulvdberge** [neoforged/NeoForge#775]
Currently, `SavedData` tends to lose persisted data in the event of a crash, power loss, etc.

**Comment by PlatinPython** [comment]
Looking at the code, I don't see a reason why that should be the case, unless you didn't call `setDirty` in the constructor and/or whenever the data changes.
That being said, I can't actually test atm

**Comment by pupnewfster** [comment]
Because the way it is handled the operating system fails to save the complete file especially when it is on the larger side.
