### ISSUE TITLE
DiggerItem.blocks outdated docs, accessor

### ISSUE THREAD

**Issue by elifoster** [neoforged/NeoForge#780]
The field `blocks` in `DiggerItem` has outdated javadocs from the time when vanilla specified valid blocks for tools by a `Set<Block>`. It reads `Hardcoded set of blocks this tool can properly dig at full speed. Modders see instead.`. This should be removed.

Additionally, it would be nice if there was a protected or public accessor for the `blocks` field. Use case: Custom implementation of `isCorrectToolForDrops`, which has to check if the block is in the tag in `blocks`.

**Comment by Shadows-of-Fire** [comment]
This is gone in the 1.20.5 port, so we can consider this fixed.
