### ISSUE TITLE
Add a form of parametrized test to the test framework

### ISSUE THREAD

**Issue by Sirttas** [neoforged/NeoForge#781]
Following the short disruption in https://github.com/neoforged/NeoForge/pull/761, I realized that what I wanted to add was a form of parametrized test and the implementation I suggested wasn't the right one.

The Implementation I would suggest is to do something similar to Junit:

```java
@ParametrizedTestHolder(description = "Tests description")
@MethodSource("provideTestArguments")
static void someTest(final DynamicTest test, String param1, int param2) {
    ...
}

...

static Stream<Arguments> provideTestArguments() {
    return Stream.of(
        Arguments.of("test", 1),
        ...
    );
}
```

**Comment by Matyrobbrt** [comment]
Wouldn't parametrized test be better made using... JUnit? We're planning to implement junit support, right now it's waiting on @marchermans.

**Comment by Matyrobbrt** [comment]
We now have JUnit support.
