### ISSUE TITLE
Add command to dump registries

### ISSUE THREAD

**Issue by TelepathicGrunt** [neoforged/NeoForge#782]
Basically this
https://github.com/MinecraftForge/MinecraftForge/issues/6565

Reasoning for making it a command:

10000% more user friendly. Can select specific registries. Has autocomplete. Can spawn link in chat to the new file.

The marker is invisible to users and is incredibly hard for users to ever know about it. Commands are naturally usable by players.

**Comment by Shadows-of-Fire** [comment]
Worth noting I believe the old `REGISTRYDUMP` marker does nothing since the removal of forge registries.
