### ISSUE TITLE
MobSpawnEvent.FinalizeSpawn with MobSpawnType.TRIAL_SPAWNER is not working

### ISSUE THREAD

**Issue by baguchi** [neoforged/NeoForge#783]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 2.4.200

**Logs:** not have

**Steps to Reproduce:**
 1. write code on MobSpawnEvent.FinalizeSpawn with MobSpawnType.TRIAL_SPAWNER
 2. make spawn on Trial Spawner
 3. nothing happen

**Description of issue:** I found this while my mod debugging when I add about Trial Spawner mob. There is a possibility that I overlooked the process of Trial Spawner somewhere or it may not have been written.

**Comment by Shadows-of-Fire** [comment]
The finalize spawn hook for the spawner is patched in (as opposed to non-spawner targets, which are applied automatically via transformer) - given that the trial spawner is also a spawner, it probably needs a patch as well.

**Comment by embeddedt** [comment]
@Shadows-of-Fire `TrialSpawner` and `BaseSpawner` don't have a shared super class, so I can't easily make the `FinalizeSpawn` event constructor accept the `TrialSpawner` as-is. What's your preferred way of refactoring this? Having duplicate fields where one is always null feels like a code smell.
