### ISSUE TITLE
[1.20.1] Possibility to backport Minecraft 1.20.2+ rendering bug fixes?

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#790]
**Minecraft Version:**  1.20.1

**NeoForge Version:** 47.1.104

**Description of issue:**
Backport all Minecraft 1.20.2+ rendering bug fixes

Is it possible?

**Comment by Technici4n** [comment]
Do you mean fixes to NeoForge bugs or to Minecraft bugs? In any case, we have already stated that we will accept backports for important bugfixes.

Please note that this kind of issue provides 0 value and is a waste of time, both for you to write and for me to respond to.

**Comment by Lolothepro** [comment]
> Do you mean fixes to NeoForge bugs or to Minecraft bugs? In any case, we have already stated that we will accept backports for important bugfixes.
> 
> Please note that this kind of issue provides 0 value and is a waste of time, both for you to write and for me to respond to.

I asked the question on Discord but nobody answered. 🙃

**Comment by KnightMiner** [comment]
He did not mean "ask on discord", he meant "ask with specifics". Ask about a specific bug being backported, or make a backport PR for that specific bug yourself.

**Comment by Lolothepro** [comment]
> He did not mean "ask on discord", he meant "ask with specifics". Ask about a specific bug being backported, or make a backport PR for that specific bug yourself.

Technici4n said:

> we will accept backports for important bugfixes.


I don't think rendering bugs are important bugs
