### ISSUE TITLE
rare random Crafting Issue 

### ISSUE THREAD

**Issue by MSandro** [neoforged/NeoForge#795]
**Minecraft Version:** 1.20.4
**NeoForge Version:** 20.4.227

I'm really not sure if it's a problem directly with NeoForge. I've already reported the bug to a few mods.
In rare cases something seems to go wrong when loading recipes. I can rarely reproduce it.
I've spent many hours over the last few days trying to get to the bottom of the problem, but to no avail, I can't pinpoint an exact mod that might be to blame. The more mods are loaded, the more often it occurs.

**Steps to Reproduce:**
 1. Join a world
 2. put something in the crafting grid
 3. sometimes you will get a random item as output

**Description of issue:**
![image](https://github.com/neoforged/NeoForge/assets/10937159/a3539d84-013e-47d0-a502-923ae6a16fae)
![image](https://github.com/neoforged/NeoForge/assets/10937159/575a58ff-715b-4e96-a32d-e04f67a21be2)
![image](https://github.com/neoforged/NeoForge/assets/10937159/657d7ff2-9b61-434b-9e6a-522ddadba1f3)

**Comment by MSandro** [comment]
All of these issues are related to this:
https://github.com/mekanism/Mekanism/issues/8056
https://github.com/TeamTwilight/twilightforest/issues/2022
https://github.com/AztechMC/Modern-Industrialization/issues/694
https://github.com/Glitchfiend/ToughAsNails/issues/843

**Comment by shartte** [comment]
There was this Mojang bug I reported *ages* ago that was fixed a while back: https://bugs.mojang.com/browse/MC-244550

Did this get revived somehow?

**Comment by Technici4n** [comment]
It's probably due to our `isEmpty` ingredient patch + some bad luck?

**Comment by MSandro** [comment]
I have tried a mod which should be able to fix tag related issues:
https://www.curseforge.com/minecraft/mc-mods/lmft
but it did not work.

Now I've noticed that some items don't have tags when the issue occurs:
![image](https://github.com/neoforged/NeoForge/assets/10937159/22808614-6b18-4608-bd7b-41187ea71729)
Here's what it looks like if the recipes are okay:
![image](https://github.com/neoforged/NeoForge/assets/10937159/207ae1d7-2ad3-4c83-ace6-0d5ae284f0b7)

**Comment by MSandro** [comment]
I've noticed the same issue in this Modpack: https://www.curseforge.com/minecraft/modpacks/new-game-neoforge-version

But there is no tech mod like Mekanism or Modern Industrialization.
It is more like a large Vanilla+ Modpack.

![image](https://github.com/neoforged/NeoForge/assets/10937159/db310b9b-e400-4eb0-b05c-754394216131)
![image](https://github.com/neoforged/NeoForge/assets/10937159/09048e04-9551-46bd-aaeb-2ceeae5c5eb0)
![image](https://github.com/neoforged/NeoForge/assets/10937159/af1a7c84-5f18-4019-a38e-aa42f8fd2cfc)
![image](https://github.com/neoforged/NeoForge/assets/10937159/8b39fc92-a051-4f71-a2f6-6323b09e3a7a)

The only mod that is also in my modpacks is Twilight Forest.

**Comment by Shadows-of-Fire** [comment]
Will be worth tracking the status of this after https://github.com/neoforged/NeoForge/pull/793 to see if it still occurs, since it is obviously from some transient issue within the ingredient code.

**Comment by Technici4n** [comment]
Let's assume that the ingredient rework fixed this in 1.20.5+. If not, please let us now.
