### ISSUE TITLE
"Saving World" is not rendered with NeoForge

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#806]
**Minecraft Version:** 1.20.1-1.20.4

**Steps to Reproduce:**
 1. Press Esc in a world

**Description of issue:**
"Saving World" is not rendered with NeoForge

Vanilla:

![2024-04-15_22 47 37](https://github.com/neoforged/NeoForge/assets/68275908/2f4af85e-d6b3-43be-b48d-12c82c020da4)

NeoForge:

![2024-04-15_22 48 49](https://github.com/neoforged/NeoForge/assets/68275908/315adbac-e56c-4494-b20b-52480cc5fe8c)

Note: `renderSavingIndicator`

**Comment by shartte** [comment]
It shows on 1.20.5-pre2

**Comment by Lolothepro** [comment]
fixed in 1.20.5
