### ISSUE TITLE
[1.20.5] The End dimension crashes the game due to the Ender Dragon

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#819]
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.6-beta

**Logs:** 
[crash-2024-04-18_16.23.13-server.txt](https://github.com/neoforged/NeoForge/files/15026303/crash-2024-04-18_16.23.13-server.txt)
[latest.log](https://github.com/neoforged/NeoForge/files/15026304/latest.log)

**Steps to Reproduce:**
 1. Teleport in the End

**Description of issue:**
The End crashes the game due to the Ender Dragon

**Comment by Gaming32** [comment]
The issue is that there's an event invocation in `Entity.<init>` that calls `getEyeHeight`, which calls `getDimensions`. However, `getDimensions` is overridden in `EnderDragonPart` to return `EnderDragonPart.size`, which is initialized in `EnderDragonPart.<init>`, which hasn't run yet (other than to call the super constructor).

**Comment by gigaherz** [comment]
After giving this a quick look, I get the feeling that it is simply not a safe assumption that pose-dependant eye height or size will be available before the subclass constructor has been called.

My personal opinion on the solution would be to either have a way to fall back to the non-pose-dependant `getEyeHeight()` and make the event have a nullable `Pose`, or to make a separate event like `EntityEvent.InitialSize`. However, I am not invested in this event and have no use case for this myself and I didn't design it, so I would defer to others who have more expertise, to make any decisions in how to solve the issue.

**Comment by allanonmage** [comment]
I ran into a similar issue with a Fabric mod pack that I'm building. Any clues to help me track down my issue?
