### ISSUE TITLE
These libraries failed to download error

### ISSUE THREAD

**Issue by Mirogoal** [neoforged/NeoForge#826]
I am trying to install neoforge and this error keeps popping up
I am using Tlauncher
Minecraft Version:1.20.4
Neoforge Version::20.4.232

![Capture](https://github.com/neoforged/Documentation/assets/120584990/55af4c3a-ddb7-4233-a32f-02a830fd63cf)

**Comment by Mirogoal** [comment]
Also forgot to mention game doesnt even open

**Comment by ChampionAsh5357** [comment]
Apologies, but we do not provide support for TLauncher
