### ISSUE TITLE
Re-evaluate `Entity#canUpdate`

### ISSUE THREAD

**Issue by Shadows-of-Fire** [neoforged/NeoForge#829]
We patch in a field `Entity#canUpdate` (with get/set methods) that allows controlling if an entity will tick.  This has a functional overlap with the living tick event.  We should evaluate if this is useful functionality or it if can just be removed.

It was added arbitrarily during 1.13 porting [here](https://github.com/neoforged/NeoForge/commit/c191851ec0d188b768d25a148e2a607f0c6a3636#diff-2b71f5e71155963095e35429b33c3ab4def410481bdc2b72210698c757b73ebaR187-R195) and did not exist in 1.12

**Comment by embeddedt** [comment]
Seems to have been removed in https://github.com/neoforged/NeoForge/pull/542, so I think this can be closed.
