### ISSUE TITLE
NeoForge crashes when I scroll in the World Select.

### ISSUE THREAD

**Issue by bruh2899** [neoforged/NeoForge#838]
**Minecraft Version:** 1.20.4

**NeoForge Version:** 20.4.232

**Logs:** The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.LevelSettings.getLifecycle()" because "this.settings" is null

**Steps to Reproduce:**
 1. Load NeoForge
 2. Click Singleplayer
 3. Scroll down

**Comment by sciwhiz12** [comment]
Cannot reproduce using steps provided. Please provide an actual log file.

**Comment by bruh2899** [comment]
I will get the Log file let me just crash NeoForge again

**Comment by bruh2899** [comment]
[crash-2024-04-23_18.44.13-client.txt](https://github.com/neoforged/NeoForge/files/15083790/crash-2024-04-23_18.44.13-client.txt)

**Comment by PlatinPython** [comment]
Did you try without mods?

**Comment by bruh2899** [comment]
Yes, but it doesn't work.

**Comment by bruh2899** [comment]
I think I fixed it, I had to change the directory of the NeoForge installation

**Comment by embeddedt** [comment]
This is a duplicate of #683.
