### ISSUE TITLE
If craft with dye. Different Item Crafted

### ISSUE THREAD

**Issue by baguchi** [neoforged/NeoForge#841]
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.0-beta

**Logs:** none

**Steps to Reproduce:**
 1. Craft Item With Dye(like dye the item recipe such as carpet)
 2. different Item Crafted

**Description of issue:**
here is what happened when craft with dye item

![2024-04-24_21 45 05](https://github.com/neoforged/NeoForge/assets/88538210/2935dfcd-2540-44e7-871b-d6fff4d831a5)

**Comment by PlatinPython** [comment]
Can reproduce, resulting item seems to be determined by the type of dye, not the item to be colored.

**Comment by PlatinPython** [comment]
Ok, apparently any item + dye works
