### ISSUE TITLE
`LivingEvent.LivingJumpEvent` Bugs

### ISSUE THREAD

**Issue by ZestyBlaze** [neoforged/NeoForge#843]
**Minecraft Version:** All versions of MC covered by Neo

**NeoForge Version:** All

**Logs:** N/A

**Steps to Reproduce:**
 1. Create an event of `LivingEvent.LivingJumpEvent` that gives glowing or hurts an entity when they jump or anything that lets you see when it fires
 2. Spawn in a Slime, Magma Cube, and a Tamed Horse
 3. Watch as the Magma Cube gets affected by the event, the Slime won't be however. When a rider jumps on a horse, it doesn't get affected by the event either

**Description of issue:**
So when digging through the events, I had a look at `LivingEvent.LivingJumpEvent` and noticed that it's not patched into Slime's despite being patched into Magma Cube's jumps, despite these mobs both being jumping mobs. Furthermore, despite `AbstractHorse` being patched, the event doesn't seem to fire for Horses when the rider jumps (As well the description for the event points to the wrong method in `AbstractHorse` as well). This means it probably also extends to Donkey's and Mules too since they both also extend `AbstractHorse`

**Comment by TelepathicGrunt** [comment]
Horse does indeed trigger the event. Tested it right now. The executeRidersJump method in AbstractHorse is fired in tickRidden when the horse jumps. Goes for mules and all others. Only Camel overrides executeRidersJump and thus, won't fire the event.
