### ISSUE TITLE
All worlds have experimental settings with NeoForge

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#846]
**NeoForge Version:** 20.5.0-beta

**Steps to Reproduce:**
1. Try to generate a new world without any experimental settings
2. The experimental settings message is displayed.

**Description of issue:**
All worlds have experimental settings with NeoForge

https://github.com/neoforged/NeoForge/assets/68275908/357e1e3f-fe04-4e41-8a66-67afc7a77ed4

**Comment by lukebemish** [comment]
This will be fixed by adding a `KnownPack` for mod resource packs, which is doable (though the vanilla code path is a bit funky -- it might need a bit more than this) -- I plan to implement it once #735 is merged, as that PR sets up the infrastructure needed for hidden packs with `KnownPack`s to behave sensibly.

**Comment by lukebemish** [comment]
Should be fixed -- at least in many cases -- by #901.

**Comment by sciwhiz12** [comment]
"In many cases"? What edge cases aren't covered by that PR?

**Comment by lukebemish** [comment]
- Mod added dimensions, which are always experimental it seems
- Stuff added by packs in `AddPackFindersEvent` that do not add KnownPacks
- IDK, whatever other cases I've missed -- that lifecycle is collected from like 50 different places

But nothing in neoforge itself, just stuff mods would add.

**Comment by sciwhiz12** [comment]
Ah, but the PR will at least fix this issue, which occurs with NeoForge-only.

**Comment by lukebemish** [comment]
Yes, and will fix _most_ mod-caused equivalents -- any caused by the more "normal" non-dynamic datapack registries, from mod built-in datapacks.
