### ISSUE TITLE
[1.19-1.20.x] Submitted chat event incompatible with jarInJar

### ISSUE THREAD

**Issue by Icosider** [neoforged/NeoForge#85]
**Minecraft Version:** 1.19 and 1.20

**Forge Version:** 43.2.20

**Description of issue:**
I noticed that the chat decorator works in ForkJoinPool, instead of using own ExecutorService. As an example, you can see the chat filtering that works in Util.ioPool() (IO Worker) The reason why I created this Issue is that I use the chat event processing, which is processed in ForkJoinPool. In addition, I have JarInJar dependencies that fall into the ForkJoinPool and hence causing the ClassNotFoundException error. Most likely, this will not solve the context problem for my mod, but it will help avoid other problems with ForkJoinPool overflow and in general it will meet the requirements of Java.

**Comment by Icosider** [comment]
[Method with error](https://github.com/neoforged/NeoForge/blob/712aa0b1acb5479f5957b3d68aaaf07cb3b69ad5/src/main/java/net/minecraftforge/common/ForgeHooks.java#L404)

**Comment by Icosider** [comment]
I did the tests and what I got:

**Testing version:** 1.19.2

**Using ForkJoinPool**
Configuration gradle:
```gradle
dependencies {
    jarJar("org.jetbrains:annotations:[24.0.1]")
    jarJar("org.jetbrains.kotlin:kotlin-stdlib:[1.9.0]")
    jarJar("org.jetbrains.kotlin:kotlin-stdlib-common:[1.9.0]")
    jarJar("org.jetbrains.kotlin:kotlin-stdlib-jdk7:[1.9.0]")
    jarJar("org.jetbrains.kotlin:kotlin-stdlib-jdk8:[1.9.0]")
    jarJar("org.jetbrains.kotlin:kotlin-reflect:[1.9.0]")
    jarJar("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:[1.7.2]")
    jarJar("org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:[1.7.2]")
    jarJar("org.jetbrains.kotlinx:kotlinx-coroutines-slf4j:[1.7.2]")
    jarJar("org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:[1.5.1]")
    jarJar("org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:[1.5.1]")
}
```
Mod code:
```kotlin
@Mod("test")
class FjkTest {
    init {
        MinecraftForge.EVENT_BUS.addListener(::onServerStarting)
    }

    private fun onServerStarting(event: ServerStartingEvent) {
        CompletableFuture.runAsync {
            testException { text ->
            }
        }
    }

    private fun testException(block: String.() -> Unit) {
        println("I will printed with exception")
    }
}
```

Build mod, run outside the IDE and join to world. Look at logs and check stacktrace with ClassNotFoundException: kotlin.blablabla.Lambda

**Comment by Icosider** [comment]
**Using normal ExecutorService**
Configuration gradle: **look at message above**

Mod code:
```kotlin
import net.minecraft.Util

@Mod("test")
class ExecServiceTest {
    init {
        MinecraftForge.EVENT_BUS.addListener(::onServerStarting)
    }

    private fun onServerStarting(event: ServerStartingEvent) {
        CompletableFuture.runAsync({
            testException { text ->
            }
        }, Util.ioPool())
    }

    private fun testException(block: String.() -> Unit) {
        println("I will printed without exception")
    }
}
```

**Comment by Icosider** [comment]
@sciwhiz12, I fixed the error and i can create PR for it. At the moment, version 1.19 is ready.

**Comment by TelepathicGrunt** [comment]
@Icosider I see you made a commit to your own NeoForge repo fork. Were you going to make a PR to move that commit to main NeoForge itself?

**Comment by Icosider** [comment]
Yes, but idk is 1.19 relevant, or that PR will be closed as it was in MinecraftForge

**Comment by TelepathicGrunt** [comment]
NeoForge is targeting 1.20.4 right now as NeoForge does not exist on MC versions older than 1.20.1. If the issue still exist in current NeoForge, a PR would be totally fine to have so it can be reviewed and merged if needed

**Comment by Icosider** [comment]
I need rework commit for another executor service

**Comment by ErythroCraft** [comment]
need

neo_version=x.y.z of 1.20.1

**Comment by sciwhiz12** [comment]
Issue does not exist in 1.20.2 and beyond as the chat decorator no longer uses `CompletableFuture`, and therefore no longer uses `ForkJoinPool`.

Closing this issue, since the author's issue has resolved itself naturally. For any other bugs directly related to this, please open a new issue (or ask in the Discord server first).
