### ISSUE TITLE
If register the spawn egg in the mod. spawn egg cannot render. (even using item/template_spawn_egg model)

### ISSUE THREAD

**Issue by baguchi** [neoforged/NeoForge#855]
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.3-beta

**Logs:** none

**Steps to Reproduce:**
 1. add Spawn Egg. with model(using minecraft:item/template_spawn_egg)
 2. cannot render the spawn egg

**Description of issue:**

Normally, the spawn egg should be displayed with a color, but nothing is displayed.
Here is what looks like:

![2024-04-25_10 59 47](https://github.com/neoforged/NeoForge/assets/88538210/9084507c-5d31-4c6d-b172-9407041c18e8)

**Comment by solarsonata** [comment]
I'm getting the same issue.
