### ISSUE TITLE
Execution failed for task ':neoFormApplyForgesAccessTransformer'. 

### ISSUE THREAD

**Issue by xgui4** [neoforged/NeoForge#867]
**Minecraft Version:** 1.205

**NeoForge Version:** 7.0.97

**Logs:** 
[log.txt](https://github.com/neoforged/NeoForge/files/15135645/log.txt)

**Steps to Reproduce:**
 1. Build the same version with a blank mod and the build will fail. 

**Description of issue:**
I cant even build my mod , it just failed automaticacly

**Comment by Spinoscythe** [comment]
7.0.3 neo version?

**Comment by xgui4** [comment]
the version is 7.0.97 in the build.gradle

**Comment by Spinoscythe** [comment]
try updating NG

**Comment by sciwhiz12** [comment]
Per the [20.5 release blog post](https://neoforged.net/news/20.5release/), updating to 1.20.5 also requires updating NeoGradle (to the latest, which as of writing is 7.0.108; see the [project listing page](https://projects.neoforged.net/neoforged/neogradle)) and changing the Java language version to Java 21.

In the future, please ask in the `#user-support` channel (under the "For Users" category) in the [NeoForge Discord](https://discord.neoforged.net/) server, as we use the issue tracker exclusively for final bug reports and feature requests.
