### ISSUE TITLE
[1.20.5] Probably unintentional removal of method LiquidBlock#getFluid

### ISSUE THREAD

**Issue by yanny7** [neoforged/NeoForge#881]
**Minecraft Version:** 1.20.5
**NeoForge Version:** 20.5.20-beta

**related commit**
https://github.com/neoforged/NeoForge/commit/e6c1c91e5d96a432dd8bc4b8a5d3027732ce85cd#

**Description of issue:**
Missing method LiquidBlock#getFluid after code refactoring (removal unnecessary registry supplier redirect)
Only way to obtain fluid type from LiquidBlock is to AT protected field `fluid`

**Comment by Technici4n** [comment]
Indeed, the `getFluid` getter was kept on `BucketItem` but removed from `LiquidBlock`. We can either add the getter back, or AT both fields.
