### ISSUE TITLE
[1.20.5] `minecraft:stored_enchantments` item subpredicate does not function

### ISSUE THREAD

**Issue by ChrysanthCow** [neoforged/NeoForge#887]
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.20-beta

**Logs:** https://mclo.gs/bjV9DXR

**Steps to Reproduce:**
 1. [Download this datapack](http://img.merchantpug.net/u/AdfkGs.zip).
 2. Put it in your world folder.
 3. Give yourself an Aqua Affinity enchanted book.
 4. Run the command `/item modify entity @s weapon.mainhand test:oops`.
 5. It does not work on NeoForge, but works on vanilla.

**Description of issue:**
The `minecraft:stored_enchantments` item subpredicate does not function properly. This is because there is no component check to make sure that the enchantments specified are base enchantments before applying the NeoForge enchantment changes.

Vanilla Instance:
![image](https://github.com/neoforged/NeoForge/assets/81167232/5d732d75-af5d-4c26-a4b3-1ac60f21ac67)

NeoForge Instance:
![image](https://github.com/neoforged/NeoForge/assets/81167232/77e564ca-5d85-40bf-be07-23ee3e9d4142)

**Comment by TelepathicGrunt** [comment]
The datapack download link does not seem to be working for me

**Comment by ChrysanthCow** [comment]
Alright, I'll send a better link over.

**Comment by ChrysanthCow** [comment]
https://wormhole.app/xEkAx#u-J2X6NuMZ_l3RTrxW3AMA.
This will only last for 24h as of sending.

**Comment by TelepathicGrunt** [comment]
Ok got the datapack. Posting it here directly so it stays forever for future testing purposes. With github, you can upload up to 10mb files here without needing external links

[neoforge report.zip](https://github.com/neoforged/NeoForge/files/15357576/neoforge.report.zip)
