### ISSUE TITLE
Convention tag requests

### ISSUE THREAD

**Issue by Technici4n** [neoforged/NeoForge#894]
> [!NOTE]
> Any requests for a new tag under the `c:` namespace should also be mirrored to the https://github.com/FabricMC/fabric repository.
> 
> No change to the tags will be entertained that is not brought up for discussion on Fabric's side. 
> 
> Neither will a PR to these tags be merged unless both NeoForge and Fabric have approved the PR with the same tag(s), the same contents, and the same definition of what the tag(s) contains.
> 
> ~ @sciwhiz12

---

Why is there no shulker box tag? 😭 @TelepathicGrunt

**Comment by TelepathicGrunt** [comment]
Simple, no one asked for one and I’m tired. Make a list of the grouping tags for vanilla dyed stuff and make a fabric issue report linking this too for coordination so someone can make prs

**Comment by dhyces** [comment]
Fabric has a shulker box item tag. Vanilla has a block item tag for shulker boxes

**Comment by dhyces** [comment]
Thoughts for a `creative_only` item tag? Maybe a bad name, but it would encompass items that are only obtainable via commands or the creative mode tabs

**Comment by ModernGamingWorld** [comment]
Here are some suggestions below I have for custom tags via my datapack mod, and I don't know if they are already included or not or if they could be considered.

Item tags for
chains
clocks
cloth, for mods like reliquary, Material elements, Forbidden arcanus, Hexerei, Ars omega, and Botania to name a few
conveyor, for mods like Immersive Engineering, Industrial Foregoing, etc that add Conveyors
Jars, for mods like Ars Nouveau, Cooking for Blockheads, Delightful, Forbidden Arcanus, Hexerei, Supplementaries, Twilight Forest, thermal, and Productive bees
tanks, for mods like ae2, create, mekanism, pneumaticcraft, and Rftools that have tanks in their mods. Would help for things like custom recipes

**Comment by thomasglasser** [comment]
~~I would appreciate a `foods/cheeses` item tag among the other food subsets, and perhaps some other general food ones but I need cheese mainly~~

~~Fabric issue: https://github.com/FabricMC/fabric/issues/3771~~

Nvm no cheeses 😔

**Comment by TelepathicGrunt** [comment]
@ModernGamingWorld Just fyi, there is already a chains tag
https://github.com/neoforged/NeoForge/blob/1.20.x/src/generated/resources/data/c/tags/items/chains.json

I dont think a tanks tags or jars tag will succeed as those sound ambiguous. But can you explain your exact use cases for those two? If it is about detecting functionality, like a working fluid tank, not sure c:tanks is the way to go with that. And would jar be for storage containers or for decorative jars? If you're trying to detect storage, a tag may be too ambiguous and cause you to get decorative jars instead.

**Comment by ModernGamingWorld** [comment]
so @TelepathicGrunt my tag suggestions are based on this (https://github.com/AzureDoom/Modern-s-Monumental-Recipe/tree/1.19.2/src/main/resources/data/modernrecipes/tags/items) and what I did in my datapack. I was only suggesting them to maybe make things easier whenever it came to modpack creation.

**Comment by KnightMiner** [comment]
I agree with the others, these tags sound too vague to be useful. While it might make your modpack creation easier, I doubt it will help others if they don't understand why these tags are useful. You will have more success in this suggestion if you list each tag you want added and exactly what it is meant to do, don't just link your datapack and say "add this"

**Comment by TelepathicGrunt** [comment]
I could see a case for cloth as some modders may want that as a repair too for clothes tbh. But that’s the only one I see some general possible use case for

**Comment by TelepathicGrunt** [comment]
Closed as of https://github.com/neoforged/NeoForge/pull/1030

**Comment by TelepathicGrunt** [comment]
Convo about the new tags should move here for easier discussion https://github.com/neoforged/NeoForge/discussions/1146
