### ISSUE TITLE
EntityTickEvent.Post is never fired

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [neoforged/NeoForge#896]
**Minecraft Version:** 1.20.6

**NeoForge Version:** 20.6.9-beta

**Logs:** N/A

**Steps to Reproduce:**
 1. Add some code to a mod to fire on EntityTickEvent.Post, notice it doesn't ever fire

**Description of issue:**
`EventHooks.fireEntityTickPost` is not called anywhere in the codebase, meaning EntityTickEvent.Post will never fire. I'd fix this myself but I've been insanely busy lately, so I'm opening this so someone else can tackle it

**Comment by Shadows-of-Fire** [comment]
Bleh, probably got lost in one of the rebases.
