### ISSUE TITLE
[1.20.5] ItemAttributeModifierEvent does not cover all uses of attributes

### ISSUE THREAD

**Issue by jaredlll08** [neoforged/NeoForge#906]
(I'm listing 1.20.5 since that is my current environment, but I don't believe this has been changed in 1.20.6)
**Minecraft Version:** 1.20.5

**NeoForge Version:** 20.5.0-beta

**Description of issue:**

`CommonHooks#getAttributeModifiers` is only called in `ItemStack#forEachModifier`, however there are other calls to `DataComponents.ATTRIBUTE_MODIFIERS` that do not use `forEachModifier` or that are covered by the `ItemAttributeModifierEvent` event, such as `net.minecraft.advancements.critereon.ItemAttributeModifiersPredicate` and `net.minecraft.world.entity.Mob#getApproximateAttackDamageWithItem`.

This leads to instances where attributes added via mods using the event are not seen in those methods.

**Comment by Shadows-of-Fire** [comment]
Locations that need updating:
- [x] ~~`ItemStack#addAttributeTooltips`~~ delegates to `forEachModifier`
- [x] `ItemAttributeModifiersPredicate#matches`
- [x] `ItemStack#forEachModifier(EquipmentSlotGroup, BiConsumer)`
- [x] `Mob#getApproximateAttackDamageWithItem`

**Comment by jaredlll08** [comment]
While patching those locations would help, it still wouldn't deal with mods calling
```java
        ItemStack stack = ...;
        ItemAttributeModifiers itemAttributeModifiers = stack.get(DataComponents.ATTRIBUTE_MODIFIERS);
```
themselves, which I am sure they are bound to do, even if Neo added a `getAttributeModifiers` method somewhere.

**Comment by Technici4n** [comment]
In that case, mods are responsible for calling the appropriate method. We might want to deprecate the data component though, to have at least somewhat of a warning.

**Comment by jaredlll08** [comment]
I don't think it is as simple as throwing a `@Deprecated` and adding a method on there...

That would break NeoForge's own code in some places, here for example:
https://github.com/neoforged/NeoForge/blob/1.21.x/src/main/java/net/neoforged/neoforge/common/extensions/IItemExtension.java#L501-L525

That would completely sidestep the "appropriate method" and the deprecation warning, comparing the components without any event changed attributes.

This was only one quick example I found, but I'm sure there is more.

**Comment by Shadows-of-Fire** [comment]
>  it still wouldn't deal with mods calling `stack.get(DataComponents.ATTRIBUTE_MODIFIERS);`

This is wrong even in vanilla (you have to query the component and fall back to `getDefaultAttributeModifiers` if it doesn't exist).  I've added a note to our extended `getDefaultAttributeModifiers` that points to `getAttributeModifiers`, and I think that will be good enough.

**Comment by jaredlll08** [comment]
As I said, that was one quick example that I found, now that I have time to sit down and look at others, and test your PR, this is what I've found...

1) 
```
net.minecraft.client.gui.GuiGraphics#renderItem(net.minecraft.world.entity.LivingEntity, net.minecraft.world.level.Level, net.minecraft.world.item.ItemStack, int, int, int, int)
```

If rendering the item itself crashes, it prints the item components using `stack.getComponents()`.
Using the following event:
```java
    @SubscribeEvent
    public void modifyAttributes(ItemAttributeModifierEvent event) {
        if (event.getItemStack().is(Items.APPLE)) {
            event.addModifier(Attributes.JUMP_STRENGTH, new AttributeModifier(ResourceLocation.fromNamespaceAndPath("c", "jumps"), 2, AttributeModifier.Operation.ADD_VALUE), EquipmentSlotGroup.HAND);
        }
    }
```
If you force a crash in the try-catch, the following is printed:
```
Details:
	Item Type: minecraft:apple
	Item Components: {minecraft:max_stack_size=>64, minecraft:lore=>ItemLore[lines=[], styledLines=[]], minecraft:enchantments=>ItemEnchantments{enchantments={}, showInTooltip=true}, minecraft:repair_cost=>0, minecraft:attribute_modifiers=>ItemAttributeModifiers[modifiers=[], showInTooltip=true], minecraft:rarity=>COMMON, minecraft:food=>FoodProperties[nutrition=4, saturation=2.4, canAlwaysEat=false, eatSeconds=1.6, usingConvertsTo=Optional.empty, effects=[]]}
	Item Foil: false
```
No word of the added attribute modifier.

I wouldn't be surprised if a mod came around and changed how an item renders based on their attributes, and not having them show up there could be *very* confusing.

2) 
A potential gameplay difference, `net.minecraft.world.entity.Mob#canReplaceEqualItem` does a call to `Mob#hasAnyComponentExceptDamage`, which checks if the item has a component that isn't the damage component, since attributes added by the event aren't added to the item's components, it is completely ignored here. This could lead to frustration if a player is trying to force a mob to pick up a specific item that has an attribute added via the event (which the user wouldn't be able to tell)

3) 
I am not sure the full implications of this, but `net.minecraft.world.item.ItemStack#hashItemAndComponents`, which is used in a few places, namely the CreativeModeTab displayItems, and the hashcodes for a few other `DataComponent`s that hold `ItemStack`s, wouldn't have the affected attributes

4)
In NeoForge, you could construct a `DataComponentIngredient` that matches a Diamond Sword with a specific attribute, say Jump Boost, but with the proposed PR, it would be possible for the user to have a Diamond Sword, that *seemingly* has the Jump Boost attribute, but does not match the ingredient, since the attribute was added using the event.

5)
I still maintain that `net.neoforged.neoforge.common.extensions.IItemExtension#shouldCauseBlockBreakReset` is an issue, I am fairly sure there is a Tinker's Construct material that mines faster the lower the durability / has a higher mining level the higher the durability (I forgot which one, but imo both can conveviably exist as features in X mod), I would imagine that could be implemented using this event and could potentially lead to unwanted gameplay, where a block breaking *should* be reset, but is not (say you're mining obsidian and something causes the item in your hand to be damaged, making it only able to mine up to iron tier instead of diamond).

**Comment by Shadows-of-Fire** [comment]
Event-provided attribute modifiers are invariant on the stack (and by extension, the current components).  As such, concerns about reproducibility against the stack are unwarranted, especially for stack equivalency. The debug information *might* be lacking if someone is doing attribute-modifier-based rendering, but it would be reproduciable.

Cases (1-3) maintain the same behavior as prior versions, so no regressions there.

Case 4 is new, as there was no general match-against-NBT ingredient before the introduction of components.  I find it unlikely anyone will attempt to match against specific component NBT data due to the fact that all AttributeModifiers have a named ID, which would need to be included in the component for this purpose.  As such, it would seem likely that a new ingredient would need to be spun up anyway.

Case 5 would be on the item to implement override `shouldCauseBlockBreakReset` to produce the intended behavior.  I don't believe the behavior of that function is in-scope of this issue or the relevant event.
