### ISSUE TITLE
NeoForge 1.20.6-20.6.15+ does not recognise the "minecraft" dependency in neoforge.mods.toml.

### ISSUE THREAD

**Issue by ricksouth** [neoforged/NeoForge#907]
**Minecraft Version:** 1.20.6

**NeoForge Version:** 20.6.15+

**Logs:** https://gist.github.com/ricksouth/3f8cebe5b63598f62c44b15940f6e4f8#file-gistfile1-txt-L1635

**Steps to Reproduce:**
 1. Update NeoForge to 1.20.6-20.6.15
 2. Load up a NeoForge mod with the "minecraft" dependency set:
 https://github.com/Serilum/Cycle-Paintings/blob/1.20.6/Common/src/main/resources/META-INF/neoforge.mods.toml#L30
 3. Launch the game. The logs specify that the minecraft dependency is missing:
 `Mod ID: 'minecraft', Requested by: 'cyclepaintings', Expected range: '[1.20.6,1.20.6]', Actual version: '[MISSING]'`

**Description of issue:**
I have double checked that `20.6.13`/`20.6.14`, before the FML update, doesn't have the issue. It has been introduced in 20.6.15.

**Comment by ricksouth** [comment]
Upon further testing, the issue seems a little more complex.

So I had updated my TickEvents to the new Neo format, but did not use the `.Post/.Pre` for some. When I ran the mods in `20.6.13`, that error was correctly shown in the debug.log. I updated those mods to get them to launch correctly.

After doing that, `20.6.14+` seems to also launch correctly.

So it only shows the minecraft dependency as missing, if I think there is another issue. In my case it was not having `.Post/Pre` for some mods.

A more simple log with less mods: https://gist.github.com/ricksouth/7181f801987e99f1954d342185d070ad#file-gistfile1-txt-L147

SBM version 3.4 gives the missing minecraft dependency: https://modrinth.com/mod/snowballs-freeze-mobs/version/1.20.6-3.4-fabric+forge+neo (but the problem is actually the tickevent)
SBM version 3.5 does not: https://modrinth.com/mod/snowballs-freeze-mobs/version/1.20.6-3.5-fabric+forge+neo

(needs the Collective dependency: https://modrinth.com/mod/collective/version/1.20.6-7.55-fabric+forge+neo)

**Comment by ricksouth** [comment]
Nevermind, now it does not launch correctly anymore? :sweat_smile:

Maybe the minecraft dependency load order is random? I'm not sure at this point.

Log with correct mods: https://gist.github.com/ricksouth/27b2ea4f8994bb8f025bb4df1b1c167e

**Comment by ricksouth** [comment]
For clarification, this is ran in production.

**Comment by ricksouth** [comment]
Welp. Seems like 20.6.14 works, but 20.6.15 does not. Ran it 3+ times for each, with the same result.

For clarification, this is ran in production. Logs are simplified by just having Collective installed.

20.6.15 log (crash): https://gist.github.com/ricksouth/03a2090709dbc08c4e8ae71cf9d50c4a
20.6.14 log (runs ok): https://gist.github.com/ricksouth/f4bc24b1bfc29e835bb33db14301fbb2

**Comment by ricksouth** [comment]
Looking at the last 20.6.15 log I uploaded, seems like the "neoforge" dependency is also missing:
`Mod ID: 'neoforge', Requested by: 'collective', Expected range: '[20.6.0,)', Actual version: '[MISSING]'`

**Comment by shartte** [comment]
> **Minecraft Version:** 1.20.6
> 
> **NeoForge Version:** 20.6.15+
> 
> **Logs:** https://gist.github.com/ricksouth/3f8cebe5b63598f62c44b15940f6e4f8#file-gistfile1-txt-L1635
> 
> **Steps to Reproduce:**
> 
> 1. Update NeoForge to 1.20.6-20.6.15
> 2. Load up a NeoForge mod with the "minecraft" dependency set:
>    https://github.com/Serilum/Cycle-Paintings/blob/1.20.6/Common/src/main/resources/META-INF/neoforge.mods.toml#L30
> 3. Launch the game. The logs specify that the minecraft dependency is missing:
>    `Mod ID: 'minecraft', Requested by: 'cyclepaintings', Expected range: '[1.20.6,1.20.6]', Actual version: '[MISSING]'`
> 
> **Description of issue:** I have double checked that `20.6.13`/`20.6.14`, before the FML update, doesn't have the issue. It has been introduced in 20.6.15.

Just as a quick clarification to understand if the FML error reporting was swallowed.
How did this error present itself to you when you launched the game? Did you get the error reporting screen?

Since the locator reported an error when locating neoforge/minecraft but that was queued for being shown after the game loaded, I wonder if we need to add a more explicit logging of the error report when we fail to even start...

**Comment by ricksouth** [comment]
It gave me an error/exit code and put me back into the launcher, there was no error reporting screen on Neo's end. I was able to read the debug.log where the problem was described

**Comment by shartte** [comment]
> It gave me an error/exit code and put me back into the launcher, there was no error reporting screen on Neo's end. I was able to read the debug.log where the problem was described

Alright, but it didn't show the *actual* problem :-D

I'll look into adding a printout of all mod loading issues when it exits like that.

**Comment by ricksouth** [comment]
> > It gave me an error/exit code and put me back into the launcher, there was no error reporting screen on Neo's end. I was able to read the debug.log where the problem was described
> 
> Alright, but it didn't show the _actual_ problem :-D
> 
> I'll look into adding a printout of all mod loading issues when it exits like that.

Haha no, it seemed completely unrelated to the dependency with the installer cache. More logging, sounds good!
