### ISSUE TITLE
[1.19.2] Config deadlock

### ISSUE THREAD

**Issue by SiverDX** [neoforged/NeoForge#91]
Forge 43.2.14

This can randomly occur when joining a world
(Even if you place all the server configs in the `defaultconfigs` directory - it can still try to check / correct some configs)

The config / mod it hangs seems to not be consistent (sometimes its mod A, sometimes mod B etc.)

![image](https://github.com/neoforged/NeoForge/assets/22003703/19ee2db1-5a17-497c-b446-caf78e3f16f7)

I don't know if this can have an effect on the behaviour:

https://github.com/embeddedt/ModernFix/blob/1.19.2/forge/src/main/java/org/embeddedt/modernfix/forge/config/NightConfigFixer.java

**Comment by TheCurle** [comment]
This is an issue with ModernFIx. You are using an old version with a broken implementation of a feature. you should update the mod to prevent the issue.

**Comment by TelepathicGrunt** [comment]
The fixes are these two commits done 3 days ago:
https://github.com/embeddedt/ModernFix/commit/1989f122c60a012a5993bb195bf7bc676678ddbe
https://github.com/embeddedt/ModernFix/commit/dbff17a1ffd535efb9f7cbe2376f62540f7ab31e
