### ISSUE TITLE
Older MC Versions

### ISSUE THREAD

**Issue by Tasharu** [neoforged/NeoForge#912]
If you could add the older versions of forge and maybe make them into neoforge versions I think the people would be a Hella lot more willing to switch to neoforge rather than staying on old forge oh and I honestly just really think the old minecraft versions combined with old forge were awesome so if you could make them neoforge everyone would be happy.

**Comment by embeddedt** [comment]
Our focus is on modern Minecraft versions at this time. See https://github.com/neoforged/NeoForge/issues/84.
