### ISSUE TITLE
Picture says everything

### ISSUE THREAD

**Issue by ENC4YP7ED** [neoforged/NeoForge#927]
![image](https://github.com/neoforged/NeoForge/assets/70538228/918601b4-be76-434a-957f-9f1bd9e9255e)

**Comment by MelanX** [comment]
I can’t hear the picture say which version that is. Maybe the server files you used were incorrect, too. We can’t check it, the picture doesn’t say where to get these files, so we can’t reproduce it.

**Comment by sciwhiz12** [comment]
We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for the [NeoForge Discord](https://discord.neoforged.net/). Ask in the `#user-support` channel (under the "For Users" category) in the Discord server instead.

Additionally, we have an issue template -- including the Minecraft version, NeoForge version, steps to reproduce the issue, and textual description of the problem -- for a clear and purposeful reason. Images alone do not speak for the whole situation, and cannot show all of the context.
