### ISSUE TITLE
PrismLauncher setup of NeoForge doesn't work because NeoForge Maven is missing mcp_config file for MC 1.20.1

### ISSUE THREAD

**Issue by the-vindex** [neoforged/NeoForge#933]
**Minecraft Version:** {Minecraft version}
1.20.1
**NeoForge Version:** {NeoForge version. *Version number, not latest/rb*}
47.1.104
**Logs:** {Link(s) to GitHub Gist with full latest.log and/or crash report}
   140.505 D | Checksummed Download for: "de.oceanlabs.mcp:mcp_config:1.20.1-20230612.114412@zip" storage: "de/oceanlabs/mcp/mcp_config/1.20.1-20230612.114412/mcp_config-1.20.1-20230612.114412.zip" url: "https://maven.neoforged.net/releases/de/oceanlabs/mcp/mcp_config/1.20.1-20230612.114412/mcp_config-1.20.1-20230612.114412.zip"
   140.521 D | Setting up api download
   140.523 W | QWindowsWindow::setGeometry: Unable to set geometry 480x139+1444+671 (frame: 496x178+1436+640) on QWidgetWindow/"ProgressDialogWindow" on "PHL 346P1C". Resulting geometry: 480x204+1444+671 (frame: 496x243+1436+640) margins: 8, 31, 8, 8 minimum size: 480x139 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=496, y=178)))
   140.560 C | [launcher.task.net.download]: "{859f814b-3378-4da1-951e-553b2ea9c3d6}" Failed  "https://maven.neoforged.net/releases/de/oceanlabs/mcp/mcp_config/1.20.1-20230612.114412/mcp_config-1.20.1-20230612.114412.zip"  with reason  QNetworkReply::ContentNotFoundError

**Steps to Reproduce:**
 1. Grab PrismLauncher 8.3 portable
 2. Setup empty modpack with NeoForge version 47.1.104, MC version 1.20.1
 3. Try launching modpack, see it fail with cryptic message.
 4. Check PrismLauncher-0.log to find mcp_config is missing.
 5. Check the URL in the browser to find out it's not really there.

**Description of issue:**

**Comment by sciwhiz12** [comment]
Whoops. An internal restructuring of our Maven repository was done recently, which included a cleanup of artifacts, and it seems the MCPConfig artifacts were not set aside from the sweep.

We're working on a fix, and will close this issue once the artifacts have been restored to their proper place.

**Comment by sciwhiz12** [comment]
The artifacts for MCPConfig have been restored, and testing by me and another member of the team seem to confirm that 1.20.1 installers are now operational again.

Sorry for the inconvenience!

**Comment by the-vindex** [comment]
Thank you far fast fix, amazing! I can confirm by launching affected installation of PrismLauncher it know automatically downloads what it needs and pack is now loading.
