### ISSUE TITLE
re-add the "PitcherCropBlock.java" patch

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#934]
https://github.com/neoforged/NeoForge/blob/1.20.x/patches/net/minecraft/world/level/block/PitcherCropBlock.java.patch

Currently the patch is empty, and there's a TODO porting for Minecraft 1.20.2... it's a bit weird.

**Comment by sciwhiz12** [comment]
This looks to be missing the patch added in https://github.com/neoforged/NeoForge/commit/027f4d3d7b5bafe3cf85911f07a65e84cce045b0.

For reference, here is the patch with the SRG names converted to Mojang names:
```diff
--- a/net/minecraft/world/level/block/PitcherCropBlock.java
+++ b/net/minecraft/world/level/block/PitcherCropBlock.java
@@ -69,7 +_,11 @@
       if (!isLower(state)) {
          return super.canSurvive(state, level, pos);
       } else {
-         return this.mayPlaceOn(level.getBlockState(pos.below()), level, pos.below()) && sufficientLight(level, pos) && (state.getValue(AGE) < 3 || isUpper(level.getBlockState(pos.above())));
+         BlockPos below = pos.below();
+         boolean isSoil = this.mayPlaceOn(level.getBlockState(below), level, below);
+         if (state.getBlock() == this) //Forge: This function is called during world gen and placement, before this block is set, so if we are not 'here' then assume it's the pre-check.
+            isSoil = level.getBlockState(below).canSustainPlant(level, below, Direction.UP, this);
+         return isSoil && sufficientLight(level, pos) && (state.getValue(AGE) < 3 || isUpper(level.getBlockState(pos.above())));
       }
    }
 
```

**Comment by TelepathicGrunt** [comment]
The old patch breaks vanilla behavior as it causes pitcher plant crop to break if next to a block when age 3 or higher. Vanilla does not break.

https://github.com/neoforged/NeoForge/assets/40846040/815db037-f92c-450b-9bd5-75de3b38a282


In fact, I can't find anything that the patch actually "fixes".

My recommendation is to just remove the TODO.
