### ISSUE TITLE
New variant of javafml to just load xor earlyload libraries and validating environments

### ISSUE THREAD

**Issue by SrRapero720** [neoforged/NeoForge#978]
# Context
I am developing a library called WATERMeDIA which is basically that, a Java library (that should not be jarJar because it contains native binaries of VLC and some other heavy stuff making jar 76MB size).

This library needs an special booting to extract binaries and validate lib is not on server-side, ~~incompatible mods aren't installed~~ and get the game paths (config, game path)

whoever, make load the library without have to _basically copy every neoforge class/method and make it a stub_ is not a good option considering how many breaking changes are you guys doing every versions

# Request
Have an javafml alt option like `javalibrary` or `javafml-library`, which is the same as javafml. but instead of require a constructor with `IEventBus` and `ModContainer`, have a single class  (`ModEnvironment`) containing basic information about the enviroment to make the library _knows where is running_ and _what is running among it_.

This will also require have a barebones ``FancyModLoader`` variant just to make it implementable

# Reasons
1. Can't be impl any NeoForge library on projects which targets Java 8 because it targets to Java 21
2. Make easier to claim a library "is a mod" just to make dependent mods can detect it easier
3. Have a almost never-changing option to just boot stuff without interact with minecraft (or mojang) classes

**Comment by lukebemish** [comment]
What is stopping you from having a single `@Mod`-annotated entrypoint class that does the setup in the constructor?

**Comment by SrRapero720** [comment]
read the reasons (again)
the idea is make NeoForge environment accessible in one class for non-mods and also have a package for make more simple the integration without have to manually do Neo mockers

and also have an option to avoid have to stressout add compat hacks for old dropped version of neoforge because a new update rename/move some classes (in mods works do breaking changes every big releases, on libraries that supports any version isn't

In reallity _nothing stops me_ but have to mock all basic classes needed for bootstrap + util classes to get the game path, the config path, what mods are installed, what is the Dist (if was Client or not), minecraft + neoforge version... these kind of stuff is not something you'll like to do. And can be done more easy if neoforge integrates itself a bootstrap for libraries

**Comment by lukebemish** [comment]
If a library has to do setup, and doesn't want to be integrated with neo stuff more than it has to, what stops you from doing
```java
@Mod
public class ModInitializer {
    public ModInitializer() {
        // Do stuff here...
    }
}
```

Or rather, to clarify: how would using your proposed API look different than this? If you need access to stuff like game/config paths, the distribution, etc... then what you're making is a mod, not a library.

**Comment by SrRapero720** [comment]
> then what you're making is a mod, not a library.

mods to be a mod requires only 1 thing: modify something (in this case can be minecraft/neoforge)
a library just provide tools for your projects (including mods)

the idea behind is let the library know where is running and decide the proper way to load their stuff
Dist is important to avoid load/use LWJGL classes on server-side (otherwise will crash), Config and game paths is important to avoid weird changes from Custom Launchers or mods changing the game path or the config path...

to be more precise, is like your example, but minimal, making neoforge for the lib be read only
```java
@Library(value = "modid")
public class LibraryInitializer {
    public LibraryInitializer(ModEnvironment env) {
        Path gamepath = env.getGamePath();
        Path path = env.getConfigPath();
        boolean isClientDist = env.isClientDist();
        boolean isDevEnv = env.isDevEnv();
        env.isModInstalled("othermodid");
        String jarname = env.getSelfJarFilename();
        ClassLoader classloader = env.getJarClassloader();
        ClassLoader secondMod = env.getJarClassloader("othermodid2");

        // do stuff here
    }
}
```
this minimize the contact with NeoForge classes to 2 classes (the annotation and the ModEnvironment class). making this a simple lib bootstrap and also makes more reliable have a new repository/module of these 2 classes compiled in a low java (8} version

**Comment by Shadows-of-Fire** [comment]
I don't think this makes any sense as a request.  Why would we spin up another entrypoint system that is virtually identical to `@Mod`?

If you intend your library to be a "pure" java library, you can make it so, but you should then also make a mod component for depending on it and hooking it up to Neo's systems.  You will need to do this anyway, even with an additional kind of entrypoint.

**Comment by SrRapero720** [comment]
> but you should then also make a mod component for depending on it and hooking it up to Neo's systems. You will need to do this anyway, even with an additional kind of entrypoint.

hooking neoforge is something than dependent mods _should_ do.
you can consider this as a "minimal mod". which only with 2 NeoForge classes you can identify a "mod" and load it.
And how i said, the purpose of the request is have a variant of the javafml, which never changes, uses minimal NeoForge system classes, just to "load a mod"

what i considered before is just let mods triggers themselfs the bootstrap, but isn't possible because Neo doesn't put non-mod jars into the classpath, doesn't have a mod id to specify a version range (or its dependency)

other option i considered is McModLauncher bootstrap, problem with it is have _many_ breaking changes every minecraft update, and for some reason it causes an incredibly weird `ClassCastExcepion: cannot cast 'me.examplemod.MyMod' to 
'me.examplemod.MyMod'`

my request is have an option to "load a mod" with a minimal class spec, having all the options of `neoforge.mods.toml`, and information about the current environment

**Comment by lukebemish** [comment]
Everything in that example can already be done with the current `@Mod` annotation with the exact same level of difficulty. I don't see how a separate entrypoint would solve anything -- it certainly wouldn't solve the "multiple MC version" issue you're worried about because that entrypoint could _also_ change between versions, like anything in neoforge.

**Comment by SrRapero720** [comment]
> issue you're worried about because that entrypoint could also change between versions, like anything in neoforge.

examples i provide only _should_ return java classes, nothing else. and the only way that features got changed is if are removed or methods in the `ModEnvironment` class are renamed.
will still remain in the time

**Comment by lukebemish** [comment]
Yes, but... you have to compile against `ModEnvironment`. So. Might as well just grab FML and compile against that, and then you can use everything else?

**Comment by SrRapero720** [comment]
Thats another part of the request 
Make that loader on a separate artifact and targeting Java 8. Because you can't depend on artifacts requiring modern java versions on projects targeting older java version 

Right now all NeoForge classes (including FML) targets Java 21

**Comment by SrRapero720** [comment]
And you said it before. Everything in neo is changing,  but this ModEnvironment is minimal enough to not be affected by NeoForge changed (only internally)

**Comment by Matyrobbrt** [comment]
What you're suggesting is an abstraction library. You want us to commit to a never-changing API design using a decade old Java version (that's missing a lot of things that are a core part of the current FML, like… modules), so that *you* don't need one. This is the definition of something that will become tech debt.  
All the information you requested to be provided can be accessed (as others pointed out) through other means that don't imply one huge interface to skip a chain of 3-4 methods mods. Such methods would be much more prone to breaking changes, as the current encapsulation can be more stable.  
What this request would introduce is a lot of added overhead for us, as instead of being able to evolve the API, we'd have this abstraction stuck in years' old design and language features. This touches one of your arguments: breaking changes. Most of them aren't "for the sake of it", they have a more elaborate reason usually (reducing tech debt, fixing API or implementation oversights, improving modder UX etc).

All in all, I don't see the point of this. If you want to be compatible with dozens of MC versions, you should put that work into it yourself.
