### ISSUE TITLE
Press Continue when a mod loading warning is present bypasses the first startup screen

### ISSUE THREAD

**Issue by Lolothepro** [neoforged/NeoForge#980]
**Minecraft Version:** 1.20.6

**NeoForge Version:** 20.6.72-beta

**Steps to Reproduce:**
 1. Create a new game instance with a mod that causes a warning message
 2. Create new game instances without mods
 3. Compare

**Comment by IMS212** [comment]
For accessibility reasons, the first start screen should show before the warning screen.
