### ISSUE TITLE
Tests subproject's GameTestServer cannot be run in Eclipse debug mode

### ISSUE THREAD

**Issue by Shadows-of-Fire** [neoforged/NeoForge#983]
Attempting a simple execution of the `Tests - GameTestServer` eclipse launch config will be met with a fairly cryptic error `Illegal version number specified version (main)`

This is caused by lack of `processResources` executing on the `testframework` during launch of the `tests` project, which means the IDE-local version of testframework's `neoforge.mods.toml` will still contain the unexpanded `${version}` key instead of the real version.

**Comment by Technici4n** [comment]
I think we should investigate why this is different from the other projects. NeoForge and tests do run correctly?

**Comment by Matyrobbrt** [comment]
Neither of those use variable replacement, it's expected behaviour for it not to work in Eclipse.

**Comment by Technici4n** [comment]
Hmmm. We generally add a launch group for that, no?

Although... getting rid of variable replacement has nice properties in general, as it allows running via IntelliJ directly. :smile:

**Comment by Matyrobbrt** [comment]
That group only runs the prepare tasks, it lacks the ability to copy the gradle output to the IJ out / eclipse bin folders like FG did.
