### ISSUE TITLE
`EventListenerGroup#mod()` is unusable due to timing

### ISSUE THREAD

**Issue by Shadows-of-Fire** [neoforged/NeoForge#984]
`EventListenerGroup` presumes to permit registration of mod bus events by accessing the mod bus from `mod()`, but will not actually attempt to propagate the event handlers to the mod bus until well after mod bus events have fired (the specific case I had been testing was `RegisterCapabilitiesEvent`).  None of the existing tests use this function, which explains why the gap was allowed to persist thus far.

It isn't immediately obvious how this should be fixed, since the current time at which we call `EventListenerGroupImpl#register` is far too late to be of any use, and probably won't lend well to the concept of per-test enablement / disablement unless that process is moved _much_ earlier.

**Comment by Matyrobbrt** [comment]
This behaviour is.. intended. While NeoForge does not fire bus events during game runtime, it's technically possible for such events to be fired. Any listeners added through the group will always only be enabled during in-world runtime, when the event is enabled to be tested.

For the use of the mod bus as a registration bus, one has to grab the event bus of the framework.
