### ISSUE TITLE
The drawing order of page numbers in CreativeModeInventoryScreen is incorrect

### ISSUE THREAD

**Issue by BloCamLimb** [neoforged/NeoForge#992]
**Minecraft Version:** 1.20.1-1.20.6

**NeoForge Version:** 20.1-20.6

**Description of issue:**
The page number rendering in `CreativeModeInventoryScreen#render` should be moved before `for (CreativeModeTab creativemodetab : currentPage.getVisibleTabs())`.

https://github.com/neoforged/NeoForge/blob/d36fa2da8e6b979505fd532786de6ae5280db281/patches/net/minecraft/client/gui/screens/inventory/CreativeModeInventoryScreen.java.patch#L161-L167

Tooltips have transparency and its Z value is 400, if the tooltip is drawn first, then the page number will be discarded by depth test. Rendering should respect [Painter's algorithm](https://en.wikipedia.org/wiki/Painter%27s_algorithm).

**Comment by TelepathicGrunt** [comment]
Just trying to understand the issue. Is there a visible problem in game? The tab tooltip seems to be rendering over top the page number without anything amiss from what I can tell
![image](https://github.com/neoforged/NeoForge/assets/40846040/3b377b9e-c85f-4aa9-875d-64ce1805b9a3)

**Comment by BloCamLimb** [comment]
The tooltip has an opacity of 240 in the range of 0 through 255 by default, it may not be obvious to see the rendering glitch. Here's the result when changing it to 64 by setting background to 0x40101010 via `RenderTooltipEvent.Color`.
![image](https://github.com/neoforged/NeoForge/assets/14106648/68402e8d-5bb6-462e-b7da-d99232672a35)
This issue is already fixed in Forge, see https://github.com/MinecraftForge/MinecraftForge/issues/9983

**Comment by BloCamLimb** [comment]
@TelepathicGrunt Your PR no longer works after the [1.21 commit](https://github.com/neoforged/NeoForge/commit/f741b728f0c63c5b584512447333e37c6741a294), needs to be fixed again.

**Comment by TelepathicGrunt** [comment]
@BloCamLimb ik but I am busy lately. Someone else will need to make the pr

**Comment by TelepathicGrunt** [comment]
@BloCamLimb Got some time today unexpectedly. Made the PR
https://github.com/neoforged/NeoForge/pull/1544
